### ISSUE TITLE
Problem example for RDIVIDE.

### ISSUE THREAD

**Issue by nickhale** [chebfun/chebfun#1048]
The following is not resolved:
```
>> f = chebfun(@(x) cosh(10*(x-0.2)*2),[0 1])
f =
   chebfun column (1 smooth piece)
       interval       length   endpoint values  
[       0,       1]       31        27  4.4e+06 
Epslevel = 2.207126e-15.  Vscale = 4.443055e+06.
>> g = 1./f
g =
   chebfun column (1 smooth piece)
       interval       length   endpoint values  
[       0,       1]    65537     0.037  2.3e-07 
Epslevel = 1.486140e-13.  Vscale = 1.000000e+00.
```

This is perhaps not surprising as the vscale of 1e6 in `f` is not taken into account when choosing an epslevel for `g`. This could either be fixed by doing so, or by waiting until we have a happiness check capable of resolving the plateau seen below.

![coeffsplot](https://cloud.githubusercontent.com/assets/2035010/3569875/da940b4e-0b46-11e4-80d3-5e6b4c71d62f.png)

Edit: note that this is a long-standing issue from V4 (https://svn.maths.ox.ac.uk/trac/chebfun/ticket/60)

**Comment by aaustin141** [comment]
Resolved with #1562.
