### ISSUE TITLE
strange behaviour of periodic constructor

### ISSUE THREAD

**Issue by trefethen** [chebfun/chebfun#1092]
How do we explain the first of the three images below?  Images 2 and 3 look plausible, different behavior depending on whether the number of points is odd or even.  What's going on with image 1, though?  @mhsnjvd and @hrothgar have been discussing this and if @gradywright knows the answer, perhaps he will tell us.  Here is the code:
```
ff = @(x) abs(sin(pi*x)).^3;
MS = 'markersize'; P = 'periodic'; a = [0 6000 1e-20 1];

subplot(1,3,1), f = chebfun(ff,P); L = length(f)
c = fourcoeffs(f); semilogy(abs(c),'.',MS,4), axis(a)

subplot(1,3,2), f = chebfun(ff,P,L);
c = fourcoeffs(f); semilogy(abs(c),'.',MS,4), axis(a)

subplot(1,3,3), f = chebfun(ff,P,L+1);
c = fourcoeffs(f); semilogy(abs(c),'.',MS,4), axis(a)


```
And here are the images:

![oddity](https://cloud.githubusercontent.com/assets/3601488/3747540/17be3658-17d0-11e4-84d0-f97f194c77aa.png)

**Comment by gradywright** [comment]
It seems to me like this can be closed, unless @trefethen still has some questions.

**Comment by trefethen** [comment]
Thanks @gradywright.
