### ISSUE TITLE
linop/eigs needs a review

### ISSUE THREAD

**Issue by mhsnjvd** [chebfun/chebfun#1189]
The `filter` function in linop/eigs uses coefficients and since the coefficients have now been "reversed"  the code needs to be reviewed. At the moment, to make the code work, we are using a flipud() at line number 449 which can be removed.

**Comment by nickhale** [comment]
I think the whole filter process needs looking at. Profiling a few of the tests suggest that at least 50% of the computational time in all eigenvalue problems is spent here.
