### ISSUE TITLE
Rewrite PDE15S to use coefficients rather than values?

### ISSUE THREAD

**Issue by nickhale** [chebfun/chebfun#1191]
`pde15s()` typically struggles when presented with a problem with little or no diffusion (see #405). My suspicion is that the main cause of this is that the coefficient 'tail' used to determine happiness becomes polluted by noise which leads to intractably large discretisation lengths. It's possible that staying in coefficient space will help to alleviate this problem.

**Comment by nickhale** [comment]
I finally got around to trying this. The figures below are `plotcoeffs()` plots of the Chebyshev coefficients from (a) the current `pde15s()` implementation* and (b) a branch where I stay in coefficient space.

The problem solved is a simple constant-coefficient Dirichlet advection diffusion problem. (I chose this because Dirichlet conditions are trivial to implement and because I couldn't be bothered to implement multiplication in coefficient space - although this can be done as in `@chebtech/times()`.)

![coeffs1](https://cloud.githubusercontent.com/assets/2035010/11146902/f11bf972-8a1a-11e5-8abe-52822605b5a7.png)

**Comment by ajt60gaibb** [comment]
Multiplication in coefficient space won't help the "polluted by noise" problem.  

I only see one plot, not sure what I am looking at...

**Comment by ajt60gaibb** [comment]
This is glorious! :+1:  I assume one can make diffusion even weaker so that `standardchop()` won't work as the plateau becomes higher.   I would be interested to see your code. 

Does this need variable coefficients that are polynomial and known exactly?

**Comment by nickhale** [comment]
I've been working on the branch feature-pde15s-coeffs. So far it only works with constant coefficients. multiplication in coefficient space is there now (but only for term `u.^2` - i was lazy). The following shows that staying in coefficient space alleviates the plateauing problem even here.

`pdefun = @(t,x,u) 0.1.*diff(u,2) + diff(u) - u.^2;`

![coeffs1](https://cloud.githubusercontent.com/assets/2035010/11176436/ac2eaec2-8c45-11e5-8bb8-cab65d661430.png)
![coeffs2](https://cloud.githubusercontent.com/assets/2035010/11176437/b2434b24-8c45-11e5-9985-4232992db66a.png)

**Comment by ajt60gaibb** [comment]
Great!   I am a little surprised this worked for a nonlinear pde.  Any insight?

**Comment by nickhale** [comment]
Continuing to dabble with this. More general nonlinearities seem to behave similarly (`pdefun = @(t,x,u) 0.1.*diff(u,2)+diff(u) - sin(u);`)

Values based:
![pde2](https://cloud.githubusercontent.com/assets/2035010/11425249/2719e9da-945c-11e5-8e73-f6d2b922fe5f.png)

Coefficient based:
![pde1](https://cloud.githubusercontent.com/assets/2035010/11425253/32c44be0-945c-11e5-9e96-a888b5df8758.png)

To compute `sin(u)` I obviously have to switch back to value space and back again, but for some reason this doesn't pollute the tail (even **without** trying to `standardChop` the result on `sin(u)`).

**Comment by nickhale** [comment]
Hmm. But if I try `pdefun = @(t,x,u) 0.1.*diff(u,2)+diff(u) + sin(u);` then coefficients does poorly..

Values:
![pde_values](https://cloud.githubusercontent.com/assets/2035010/11425350/fa000ad2-945c-11e5-81f4-e7e4666f09e4.png)

Coeffs:
![pde_coeffs](https://cloud.githubusercontent.com/assets/2035010/11425354/024aae4a-945d-11e5-95c4-acc95a93dee1.png)

**Comment by ajt60gaibb** [comment]
hmmm...
