### ISSUE TITLE
Overly aggressive tail chopping in CHEBTECH/TIMES().

### ISSUE THREAD

**Issue by nickhale** [chebfun/chebfun#1214]
The following example demonstrates that we might sometimes be throwing away quite a lot of information in `chebtech/times()`. The image below was obtained by inserting calls to `coeffplot()` before and after the `simplify()` call in `chebtech/times()` and running the following code:
```
x = chebfun('x', [0 10]);
f = chebfun(@(x) sin(10*x)-exp(x), [0, 10]);
sin(x).*diff(f,2)
```

![times](https://cloud.githubusercontent.com/assets/2035010/4679219/29c6d31a-55ff-11e4-9b3e-57a4f21e1653.jpg)

**Comment by aaustin141** [comment]
With #1562 merged, we now get the following:
```
>> x = chebfun('x', [0 10]);
>> f = chebfun(@(x) sin(10*x)-exp(x), [0, 10]);
>> sin(x).*diff(f,2)
ans =
   chebfun column (1 smooth piece)
       interval       length     endpoint values  
[       0,      10]      108  -5.1e-13  1.2e+04 
vscale = 1.195532e+04.
>> plotcoeffs(ans)
```
![1214](https://cloud.githubusercontent.com/assets/3380006/8991224/371416e6-36ef-11e5-9d9a-ddf07ba3f6ab.png)

Shall we consider this issue closed?
