### ISSUE TITLE
Multiplication of a matrix by a quasimatrix succeeds with mismatched dimensions!

### ISSUE THREAD

**Issue by bhashemi** [chebfun/chebfun#1215]
I tried to run the following illegal operation of multiplying a 3*3 matrix (on the right) by a quasimatrix of size Inf*3 
```
A = randn(3);
Q = chebfun(@(x) [x cos(x) x.^2]);
AQ = A*Q;
size_AQ = size(AQ)
```
and it does work ending up with an Inf*3 quasimatrix !
```
size_AQ =

   Inf     3
```

**Comment by asgeirbirkis** [comment]
Closed by #1279.
