### ISSUE TITLE
method to get a random chebfun

### ISSUE THREAD

**Issue by hrothgar** [chebfun/chebfun#1226]
Is there any demand for a method to get a random chebfun? I know that I have wanted such a thing in the past. A lot of time we take `sin(x)` or `exp(x)` when we just want any old chebfun. Suppose we had a function `rand` that overloaded MATLAB’s `rand` like this:
```
>> f  = rand(x);     % a random chebfun on the domain of x
>> ff = rand(x, 3);  % a quasimatrix of three random chebfuns on the domain of x
```
Of course, there is debate to be had about what “random” means for a chebfun. But definition of “random” aside, is there interest?

**Comment by aaustin141** [comment]
Does the introduction of `cheb.gallery('random')` in #1319 resolve this issue?

**Comment by trefethen** [comment]
As far as I'm concerned, yes it does.

**Comment by hrothgar** [comment]
I'm happy for this to be closed, too.
