### ISSUE TITLE
would somebody please put in a "doublelength" option?

### ISSUE THREAD

**Issue by trefethen** [chebfun/chebfun#1258]
People - I would be grateful, if it's easily done, if somebody would add what could even be an undocumented feature to the Chebfun constructor pending a full discussion of the right name, capabilities, etc.

`chebfun('exp(x)')`, for example, gives you a chebfun of length 15.  I would like to be able to type
`chebfun('exp(x)','doublelength')` and get exactly the same result as if I had typed `chebfun('exp(x)',30)`.  I would _love_ to have this for talks and indeed I wish I'd had it in every Chebfun talk I've given in the last ten years.  And I very much want to have it in the upcoming year as we do a lot of constructor explorations.

Can somebody make this?  

Thanks.

**Comment by aaustin141** [comment]
Closed in #1327.
