### ISSUE TITLE
Convergence for collocation

### ISSUE THREAD

**Issue by asgeirbirkis** [chebfun/chebfun#1282]
The convergence check for linear ODEs is an ongoing issue. Here's a concrete example showing that for some problems, it keeps too much of the tail, while for other problems, it thinks it's converged too early. I ran the code below on the current version of development, fa6f520.

```matlab
% Define the domain.
dom = [0,1];

% Assign the differential equation to a chebop on that domain.
N = @(ep) chebop(@(x,u) ep.*diff(u,2)+diff(u)+u, dom, 0, 1);

% Set up the rhs of the differential equation so that N(u) = rhs.
rhs = 0;

% Create a CHEBOPPREF object for passing preferences: 
options = cheboppref();
options.discretization = 'collocation';

% Solve for different values of ep, and look at the solution and coefficients
epVec = 10.^(-2:-1:-6);
for epCounter = 1:length(epVec)
    u = solvebvp(N(epVec(epCounter)), rhs, options);
    subplot(length(epVec), 2, 2*epCounter-1)
    plot(u)
    title(sprintf('Solution for ep = %2e', epVec(epCounter)))
    subplot(length(epVec), 2, 2*epCounter)
    plotcoeffs(u);
    ylabel('')
    xlabel('')
end
```

This gives the following image:
![convcolloc](https://cloud.githubusercontent.com/assets/3543429/5203991/7655da5c-7583-11e4-8a1f-4e1633468989.png)

If I change the discretization to ```ultraspherical```, things look much better:

![convultras](https://cloud.githubusercontent.com/assets/3543429/5204014/a31db708-7583-11e4-95eb-fdba6b43e581.png)

I'm not claiming that collocation should do a particularly good job at the last two problems, however, it shouldn't return the solutions it did without realising that something has gone awry/

**Comment by aaustin141** [comment]
With #1562 now merged, I get that @asgeirbirkis's code now gives the following plot using collocation:

![1282-colloc](https://cloud.githubusercontent.com/assets/3380006/8992610/73d8a4e0-36f7-11e5-8dd7-4cc5c9c76df3.png)

This is a marked improvement over the results @asgeirbirkis originally posted and is now much closer to the results using ultraspherical methods, which I get to be

![1282-ultras](https://cloud.githubusercontent.com/assets/3380006/8992621/81dcf6a4-36f7-11e5-8edc-d8c498ad0fd5.png)

Very similar to what we had before.

Can we now close this issue?

**Comment by asgeirbirkis** [comment]
Thanks @aaustin141 for looking into this! I'm happy for this issue to be closed.
