### ISSUE TITLE
Can we restore plotting of deltas as in v4?

### ISSUE THREAD

**Issue by trefethen** [chebfun/chebfun#1288]
The plotting of deltas in v5 has never been fixed.  Can it be fixed so that we get arrows that start on the curve, not on the x axis?  Below are plots comparing v4 and v5 results of plot(diff(exp(x)+sign(x))).  I think the v4 image is much more appropriate, and if we could have that again, it would be great.  This issue has come to my attention again as I update the Guide and encounter an embarrassing image in Section 2.4.
![deltasplot](https://cloud.githubusercontent.com/assets/3601488/5237151/5498caae-7868-11e4-8793-805e7a6f76dc.png)

**Comment by asgeirbirkis** [comment]
Is this closed by #1408?

**Comment by trefethen** [comment]
Looks good to me.  I'll close the issue, with thanks to @mhsnjvd and others.

**Comment by mhsnjvd** [comment]
Yes.

![untitled](https://cloud.githubusercontent.com/assets/890964/6287844/93fc8412-b90c-11e4-836a-f2ebdfa9168c.jpg)
