### ISSUE TITLE
example where v5 is 7 digits less accurate than v4 near singularity

### ISSUE THREAD

**Issue by trefethen** [chebfun/chebfun#1290]
I guess we know that v5 has some anomalous behaviour near singularities.  Here's another example.  In v4, we find
```
>> f = chebfun('log(x)',[0 1],'splitting','on','blowup',2);
>> quaderror = sum(f) + 1
quaderror = 7.915890165577366e-14
```
In v5, the computation is faster, but the answer is much worse:
```
>> f = chebfun('log(x)',[0 1],'splitting','on','blowup',2);
>> quaderror = sum(f) + 1
quaderror = 1.101492894894918e-06
```
I encountered this example in fixing up Gonnet's `quad/BatteryTest` Example for publication.

**Comment by aaustin141** [comment]
Like #1301, I'm now seeing this as resolved with the merging of feature-prescribed-eps (specifically, commit 6e02ae4a).  @trefethen, can you please confirm when you get a chance and close this issue if that is the case?

**Comment by trefethen** [comment]
Looks good, thanks.
