### ISSUE TITLE
trig <-> periodic switch needed in `chebfun` help text

### ISSUE THREAD

**Issue by trefethen** [chebfun/chebfun#1333]
The text you get with `help chebfun` describes the `periodic` flag, and then explains that
```
chebfun(F, 'trig') is the same as chebfun(F, 'periodic').
```
This is obsolete: 'trig' should now be our standard term and 'periodic' can be mentioned as an alternative.  In other words, the roles of 'periodic' and 'trig' need to be interchanged.  @mhsnjvd, would you be able to fix this?

**Comment by nickhale** [comment]
Closed by #1335.
