### ISSUE TITLE
`trigcoeffs(<chebfun>)` gives erroneous result

### ISSUE THREAD

**Issue by trefethen** [chebfun/chebfun#1334]
The `trigcoeffs` command can be used to compute a few exact Fourier coefficients of a non-periodic chebfun, as in this example:
```
>> t = chebfun('t', [0 2*pi]);
>> trigcoeffs(t, 5)
ans =
  -0.0000 - 0.5000i
  -0.0000 - 1.0000i
   3.1416 + 0.0000i
  -0.0000 + 1.0000i
  -0.0000 + 0.5000i
```
That is fine.  However, if you don't specify the number such as 5 above, you get the output corresponding to `tricoeffs(t,length(t))':
```
trigcoeffs(t)
ans =
  -0.0000 - 1.0000i
   3.1416 + 0.0000i
```
This does not make sense mathematically and will readily mislead users as it misled me, though the help text to its credit says it will happen:
```
If F is a smooth CHEBFUN (i.e., with no breakpoints), then trigcoeffs(F) is
equivalent to trigcoeffs(F, LENGTH(F)).
```
I think instead there should be an error, perhaps with this text:
```
"trigcoeffs(<chebfun>,n) is allowed but not trigcoeffs(<chebfun>)"
```
@gradywright, does this make sense to you, and if so are you willing to take care of it?

**Comment by asgeirbirkis** [comment]
Closed by #1357.
