### ISSUE TITLE
Why does sampling stop at 32768, not 65537?

### ISSUE THREAD

**Issue by trefethen** [chebfun/chebfun#1337]
I am confused!  Can somebody explain something basic to me?  The confusion applies in both trigfuns and chebfun's; let's focus on the latter.
Suppose I make a function that evaluates `sign(x)` and also prints the lengths of the `x` vectors called.  I get the following:
```
>> f = chebfun(@foo)
     2
    17
    16
    32
    64
   128
   256
   512
        1024
        2048
        4096
        8192
       16384
       32768
Warning: Function not resolved using 65537 pts. Have you tried
'splitting on'? 
> In chebfun.constructor>constructorNoSplit at 120
  In chebfun.constructor at 63
  In chebfun.chebfun>chebfun.chebfun at 221 
     2
f =
   chebfun column (1 smooth piece)
       interval       length   endpoint values  
[      -1,       1]    65537        -1        1 
Epslevel = 1.507754e-06.  Vscale = 1.
```
I don't get it.  Why are these numbers even, not odd?  And more importantly, why is the last one 2^15, not 2^16?

**Comment by nickhale** [comment]
I agree with @gradywright.

`sum([17 16 32 64 128 256 512 1024 2048 4096 8192 16384 32768]) = 65537`

The initial `2` comes from querying the function handle to test vectorisation (I think).
