### ISSUE TITLE
Make the help text of `chebcoeffs2` clearer

### ISSUE THREAD

**Issue by bhashemi** [chebfun/chebfun#1340]
Here is what we see in the help text of `chebcoeffs2`:
`X = chebcoeffs2(F) returns the matrix of bivariate coefficients such that`
        `F= sum_i ( sum_j X(i,j) T_i(y) T_j(x) )`.

`i` in `T_i(y)` and `j` in `T_j(x)` should start at `0` but MATLAB indices in `X(i,j)` start at `1`. So, I suggest the following instead of the second line above:
        `F= sum_{i=0}^{n-1} ( sum_{j=0}^{n-1} X(i+1,j+1) T_i(y) T_j(x) )`

**Comment by trefethen** [comment]
Yes, that looks sensible to me.

**Comment by aaustin141** [comment]
Closed in #1502.
