### ISSUE TITLE
Automatic subplotting of a quasimatrix

### ISSUE THREAD

**Issue by asgeirbirkis** [chebfun/chebfun#1342]
When working with quasimatrices (and chebmatrices) of decent dimensions, I keep finding myself wanting to do a subplot to look at individual functions on separate plots, rather than all on the same plot. Now, I have to do something like this:

```
>> T = chebpoly(1:10);
>> for i=1:numColumns(T), subplot(2,5,i), plot(T(:,i)), end
```

Should we introduce a subplotting command, that given the dimensions, would do these kind of thing automatically, e.g.

```
>> T = chebpoly(1:10);
>> subplot(2,5,T);
```

**Comment by trefethen** [comment]
My reaction is that this would be an odd thing to do, since MATLAB doesn't have such a feature for plotting columns of a matrix; what makes the Chebfun context so special that one would want to break the analogy?  Perhaps I am missing something about how valuable this would be.

**Comment by asgeirbirkis** [comment]
I guess one of the reason why MATLAB doesn't have this feature is that for them, the third argument to the subplot command is the same datatype as a matrix (which can make it ambiguous whether one is indexing the subplots or calling for this functionality), whereas in our case, the third argument would be a Chebfun datatype, so that we'd always know what to do with the input.

I came across this when working with a quasimatrix with 14 entries. In that case, simply plotting it doesn't really give much information, as the plot is totally cluttered. I can imagine the same situation arising e.g. when solving eigenvalue problems, with more than 10 eigenvalues requested.

If others think that this wouldn't be a valuable feature, I'm happy to live with my own local method for dealing with this.

**Comment by asgeirbirkis** [comment]
I'm finding myself using my local version of this functionality quite frequently, where I've named it gridPlot. I.e.
```
T = chebpoly(1:8);
gridPlot(T, 4, 2);
```
gives me a 4x2 subplot with each column in a single plot. Can anyone else imagine it being useful, in which case, I could submit a pull request for it?

**Comment by trefethen** [comment]
At our group meeting we decided this sounds like a good idea (all lower case though, `gridplot`) -- thanks @asgeirbirkis.  May I urge you to make sure `gridplot` finds its way into our documentation via Examples and/or Guide?

**Comment by asgeirbirkis** [comment]
@trefethen , sure, I'll write an example demonstrating this feature when it goes live, and issue a pull request to the appropriate section(s) of the guide as well.
