### ISSUE TITLE
chebtest chebfun/test_trigcasting fails

### ISSUE THREAD

**Issue by nickhale** [chebfun/chebfun#1345]
Test 14 fails for me because
```
>> norm(round(f) - round(g), inf)
ans =
     1
```

It appears the reason is that the break points of `round(f)` and `round(g)` are off by O(`eps`). Since that's perfectly justified, I think this test needs to change. Possibly testing the domain of `round(f)` and `round(g)` are the same, plus maybe something like that the 1-norm of `round(f)` is the same as the 1-norm of `round(g)`, or something.

**Comment by asgeirbirkis** [comment]
Closed by #1346
