### ISSUE TITLE
Implement a `truncate()` method

### ISSUE THREAD

**Issue by nickhale** [chebfun/chebfun#1350]
There are a few ugly things about how the `trunc` option is currently implemented:
 * Additional input parsing takes place in `chebfun()`, even though we have a sub-method for that.
 * Encapsulation is scetchy at best when the truncation is actually implemented.
 * The truncation machinery is taking up a lot of code in the otherwise clean constructor.

I suggest:
 * Moving the input parsing that takes place in `chebfun()` to `parseInputs`.
 * Introducing a `truncate()` method, which does the appropriate thing.

In addition to tidying the constructor, this would also enable things like:
```
>> s = chebfun(@(x) sign(x), 'splitting', 'on')
>> plot(s, 'b', truncate(s, 10), '--r')
```
![sgn](https://cloud.githubusercontent.com/assets/2035010/5814772/b96d5268-a097-11e4-8815-e9b9d255472f.jpg)

P.S. I'm **not** suggesting that the UI for adding the `trunc` option in the constructor is changed.

**Comment by davidagross** [comment]
I love this idea but have a question about your example.  Why wouldn't `truncate(s,10)` return `s`?  In my mind, we're taking a chebfun (that's split into two parts that each have less than 10 coeffs) and asking to strip off the coeffs higher than the first 10.  In this view, the output is the input.

The naive questions here is: when should truncate() merge split domains before truncating, and why and how?

**Comment by nickhale** [comment]
I was just going for consistency with the current `trunc` option in the constructor:
```
>> chebfun(@sign, 'trunc', 10)
ans =
   chebfun column (1 smooth piece)
       interval       length   endpoint values  
[      -1,       1]       10      -1.1      1.1 
Epslevel = 2.088743e-15.  Vscale = 1.063054e+00.
```

From the help text:
```
  chebfun(F, 'trunc', N) returns a smooth N-point chebfun constructed by
  computing the first N Chebyshev coefficients from their integral form, rather
  than by interpolation at Chebyshev points.
```

I guess my `truncate()` method is equivalent to computing the **global** Chebyshev coefficients via `chebcoeffs()` and then constructing a chebfun from there values:
```
>> s = chebfun(@sign, 'splitting', 'on')
>> c = chebcoeffs(s, 10)
c =
                   0
   1.273239544735163
  -0.000000000000000
  -0.424413181578388
   0.000000000000000
   0.254647908947033
   0.000000000000000
  -0.181891363533595
  -0.000000000000000
   0.141471060526130
>> t = chebfun(c, 'coeffs')
t =
   chebfun column (1 smooth piece)
       interval       length   endpoint values  
[      -1,       1]       10      -1.1      1.1 
Epslevel = 2.088743e-15.  Vscale = 1.063054e+00.
```

**Comment by davidagross** [comment]
Perfect.  I still wasn't thinking of `chebfun` the right way where I assumed we were truncating some computational object that depended on the way it was stored, whereas we are actually truncating the function that our object represents to only be represented with the first N chebpolys.  

I can imagine that there exists a function for which a user would want to use Chebfun's splitting algorithms to determine functions for each subdomain, and then maybe truncate one or some or all of the subdomains separately.  So yes, either making clear that this truncate is always/only global or giving it the feature to truncate only some of the `funs` would be good.
