### ISSUE TITLE
To simplify or not to simplify?

### ISSUE THREAD

**Issue by jaurentz** [chebfun/chebfun#1351]
Should we demand that 

``` matlab
diff(cumsum(f)) = f
```

when f is a chebfun?

Here's a chebfun classic.

``` matlab
>> f = chebfun('sin(x)+sin(x.^2)')
f =
   chebfun column (1 smooth piece)
       interval       length   endpoint values  
[      -1,       1]       23         0      1.7 
Epslevel = 1.110223e-15.  Vscale = 1.682942e+00.
```

Taking the derivative of the integral lowers the degree by 2.

``` matlab
>> g = diff(cumsum(f))
g =
   chebfun column (1 smooth piece)
       interval       length   endpoint values  
[      -1,       1]       21   1.2e-13      1.7 
Epslevel = 1.471987e-13.  Vscale = 1.682942e+00.
```

The norm isn't zero either.

``` matlab
>> norm(g-f,inf)
ans =
   1.1946e-13
```

A quick check and one finds the culprit to be `simplify`. This begs the bigger question, _Do we simplify operations that we know can be done to high relative accuracy?_ Here I mean machine epsilon not the chebfun epslevel.

I believe that one argument for the simplification is that integration increases smoothness and the resulting function can be stored with less coefficients. What if the coefficients that were thrown away were computed to high relative accuracy? Sure, they are below some tolerance, but they most definitely aren't noise. Those coefficients contain valuable information, information that could be used to increase the accuracy of the solution to an ODE or any other operation involving `diff`? 

Is the desire to simplify so strong that we should discard valuable information when the cost of keeping that information is no more than the cost to store the function from which it came? When doing basic linear algebra operations, Matlab keeps numbers at or below machine precision. It doesn't stop after every iteration and zero entries that are below some relative tolerance, noisy or otherwise. 

When constructing a chebfun for the first time there will almost surely be noisy data output from the FFT and the initial simplification removes what it feels is strictly noise. Everything that's left was kept because it contained useful information. Shouldn't we want to hold on to this information whenever we feasibly can? I feel we should think twice every time we try to simplify an already constructed chebfun.

**Comment by davidagross** [comment]
I'll second that sentiment of thinking twice, related to the issues around simplification I was looking at with @kuanxu in singfun and unbndfun having to do with exponents (See #1024 for `simplify` and #1026 for a similar conversation but about boundary root extraction).

**Comment by jaurentz** [comment]
With the recent merger of #1562 feature-standardChop, construction for both approximations and ODEs, as well as simplification have been unified. Some experimenting once again begs the question of whether or not to simplify. Consider the following example:
```matlab
>> f = chebfun('cos(x)')

f =

   chebfun column (1 smooth piece)
       interval       length     endpoint values  
[      -1,       1]       15      0.54     0.54 
vscale = 1.000000e+00.

>> g = chebfun('1e-50*cos(50*x)') 

g =

   chebfun column (1 smooth piece)
       interval       length     endpoint values  
[      -1,       1]       93   9.6e-51  9.6e-51 
vscale = 1.000000e-50.

>> h = f + g                     

h =

   chebfun column (1 smooth piece)
       interval       length     endpoint values  
[      -1,       1]       93      0.54     0.54 
vscale = 1.

>> h2 = simplify(h)

h2 =

   chebfun column (1 smooth piece)
       interval       length     endpoint values  
[      -1,       1]       15      0.54     0.54 
vscale = 1.000000e+00.
```

At one time I would have thought that this behaviour is acceptable but now I feel that it is somewhat undesirable. Maybe we should be calling `simplify` more often.
