### ISSUE TITLE
A comparison of Epslevel and relative error

### ISSUE THREAD

**Issue by bhashemi** [chebfun/chebfun#1355]
Suppose that f is explicitly given and fN = chebfun(f). I made a comparison between the present Epslevels and "relative errors" for 54 different functions f in Chebfun where
RelErr := norm(fN(x) - f(x),inf)/ norm(f(x),inf);
is supposed to give us an estimate of the relative truncation error. Here, x = chebpts(2N+1) chosen as motivated by a discussion about "interstitial error" in Pages 50-55 of Boyd, Solving Transcendental Equations, SIAM, 2014. 

Here is the output:

![untitled](https://cloud.githubusercontent.com/assets/9217439/5837713/571aacea-a179-11e4-85ea-aeb5551ed728.png)

It seems that the difference is mostly about one or two orders of magnitude. The worst case scenario is for functions number 7, 17 and 26. The function number 17 is 
`
f = @(x) cos(5*acos(x))+1e-5*cos(30*acos(x))+1e-10*cos(300*acos(x));
`
where Chebfun currently chops at degree 44 rather than 300. We can possibly cope with this case by designing an alternative constructor. The function number 7 is the following:
`
f = @(x) abs(x+.5)*(x+.5);
`
for which we have "algebraic" convergence. Here, `length(chebfun(f))= 12608` and `Epslevel = 4.5e-13`, while `RelErr = 1.3e-9`. There is a rule of thumb (see, e.g., Page 51 of Boyd's 2001 book) which can help us defining a better Epslevel for functions having algebraic rate of convergence. It roughly suggests that we multiply `| a_N |` by `N`. We have 
`New_Epslevel := N*Epslevel = 5.7e-09`
which is a more realistic value for Epslevel. The same situation applies to function number 26 which is 
`f = @(x) abs(sin(7*(x-.3)))^5` and has algebraic convergence, too.

**Comment by aaustin141** [comment]
`epslevel` has now been deactivated internally, and it is not unlikely that we'll end up completely removing it in the future.  Can we close this issue?
