### ISSUE TITLE
`chebtech2.vals2coeffs` is quadratic, not nlogn

### ISSUE THREAD

**Issue by trefethen** [chebfun/chebfun#1361]
@bhashemi and I have been doing so experiments that show `chebtech2.vals2coeffs` seems to have quadratic rather than nlogn complexity -- or perhaps even worse.  For example, on his new Mac,
```
x = randn(8000); tic, chebtech2.vals2coeffs(x); toc
Elapsed time is 3.652518 seconds.
>> x = randn(16000); tic, chebtech2.vals2coeffs(x); toc
Elapsed time is 38.709279 seconds.
```
What's going on?  The Slowest Fourier Transform in the West!

**Comment by aaustin141** [comment]
I actually can't run the `randn(16000)` example on my machine, as I run out of memory (8 GB RAM) in the call to `vertcat` which doubles things up.

**Comment by trefethen** [comment]
Oops, you've pointed out that we were too hasty. We should have written randn(16000,1).  My bad.  I'll close the issue.
