### ISSUE TITLE
trigtech/plus misbehaving for functions with even length

### ISSUE THREAD

**Issue by hrothgar** [chebfun/chebfun#1367]
I added a constant to a trigfun, and it looks like the constant got added to the wrong Fourier coefficient:
```
f = cheb.gallerytrig('random');
g = f + 20;
plot(f), hold on, plot(g, 'r')
```
![bug_trig_plus](https://cloud.githubusercontent.com/assets/913747/5969089/1f893d9c-a817-11e4-8244-01bbcdadc70b.png)

Is it because this particular function, which I got from gallerytrig, has even length?
```
>> f
f =
   chebfun column (1 smooth piece)
       interval       length   endpoint values trig
[    -3.1,     3.1]      100     0.051    0.051 
Epslevel = 1.110803e-15.  Vscale = 9.994779e-01.
```

**Comment by gradywright** [comment]
You are correct @hrothgar, this is because the length is even.  Looks like `@trigtech/plus` did not get updated when we switched the way we stored coefficients.
