### ISSUE TITLE
Bug when plotting coefficients of even-length trigtech

### ISSUE THREAD

**Issue by hrothgar** [chebfun/chebfun#1371]
As noted in #1327, there are a couple of issues with the coefficients plot of an even-length trigtech:

```
f = chebfun('sin(pi*x)', 'trig', 'doublelength'); plotcoeffs(f)
```
![doublelength_trig](https://cloud.githubusercontent.com/assets/913747/5975066/a7814f3a-a873-11e4-8143-3af21ad6022e.png)

1. The coefficients are misnumbered — is this because the coefficients are supposed to be flipped, reordered the opposite way?
2. The epslevel line doesn't extend all the way out.
3. It might also be nice to set the axes to make the plot symmetric/centered.

**Comment by gradywright** [comment]
1.  Even length trigtechs have one extra negative mode coefficients `c_{-N/2}` corresponding to the mode `exp(1i*pi*x*(-N/2))`.  When the change was made to switch the ordering for how trig coefficients are stored (i.e. from -N/2 to N/2-1 in the case of N even), the code in `@trigtech/plotcoeffs' was not updated to account for where  extra negative mode occurs.

2.  I'm not sure why epslevel does not extend all the way, but will investigate.  

3.  I am fine with doing this.

**Comment by Hadrien-Montanelli** [comment]
@gradywright Any progress? If you haven't started working on it yet, I can take care of if!

**Comment by gradywright** [comment]
@Hadrien-Montanelli I actually fixed this a while ago, but forgot to issue a pull request.  Let me look it over and make sure I caught everything.

**Comment by Hadrien-Montanelli** [comment]
@gradywright Great!
