### ISSUE TITLE
Tidying negative exponents

### ISSUE THREAD

**Issue by nickhale** [chebfun/chebfun#1375]
I think we should strive to return a `chebfun` with positive exponents where possible. For example, I would like the following to have exponents `[0.5 0]` rather than `[-0.5 0]`:

```
>> x = chebfun('x', [0 1]);
>> f = x./sqrt(x)
f =
   chebfun column (1 smooth piece)
       interval       length   endpoint values   endpoint exponents
[       0,       1]        2       NaN        1         [-0.5      0]  
Epslevel = 1.110223e-15.  Vscale = 1.414214e+00.
```

**Comment by aaustin141** [comment]
I probably should have said this before this issue got closed, but in order to do this, we need to call `extractBoundaryRoots`, right?  Doesn't that have the potential for additional loss of accuracy?  If so, is a cosmetic change like this really worth it?  I only ask because we've had lots of problems with `extractBoundaryRoots` in general; indeed, it's kind of a theme that runs through all of our `singfun` woes...

**Comment by nickhale** [comment]
I think it's worth it. My example above which gave NaN at the left wasn't so bad, but consider this (pre-#1376):

```
>> x = chebfun('x', [0 1])
x =
   chebfun column (1 smooth piece)
       interval       length   endpoint values  
[       0,       1]        2         0        1 
Epslevel = 1.110223e-15.  Vscale = 1.
>> x./x.^.7
ans =
   chebfun column (1 smooth piece)
       interval       length   endpoint values   endpoint exponents
[       0,       1]        2      -Inf        1         [-0.7      0]  
Epslevel = 1.110223e-15.  Vscale = 1.624505e+00.
```
The value at the left certainly shouldn't be inf.

Things can be even worse:
```
>> sum(x.^2./x.^1.7)
ans =
   Inf
```

Post-#1376 these all give much more sensible results.

**Comment by kuanxu** [comment]
I believe that we had debate before on whether do `cancelExponents` in @singfun/rdivide.m as well as tons of experiments. There are benefits for including it (as this ticket indicates) and for excluding it (as we all know that `extractBoundaryRoots` is one of the most unreliable functions in `singfun` and one origin of the `singfun` woes). So it's not easy to draw a conclusion which is better. I guess the criterion for the time being could be pass of all tests. As long as all tests pass, leaving it either way is good enough for me.
