### ISSUE TITLE
Ensure real output in CHEBFUN.DCT() et al.

### ISSUE THREAD

**Issue by nickhale** [chebfun/chebfun#1380]
We current make little attempt to ensure that the DCT/DST/IDCT/IDST of real vectors returns a real output. 

(The reason this is required is that we have to use the FFT to compute these, which can introduce small imaginary errors.)

For example:
```
>> chebfun.idst(ones(10, 1))
ans =
  1.264573231231541 - 0.000000000000000i
  0.000000000000000 - 0.000000000000000i
  0.398126284179942 - 0.000000000000000i
  0.000000000000000 - 0.000000000000000i
  0.209829367369638 + 0.000000000000000i
 -0.000000000000000 - 0.000000000000000i
  0.116847450394242 + 0.000000000000000i
  0.000000000000000 + 0.000000000000000i
  0.053386635079703 + 0.000000000000000i
  0.000000000000000 + 0.000000000000000i
```

**Comment by ajt60gaibb** [comment]
Not sure. My original intention for `chebfun.dct()` and its cousins was to not have any input checking.

**Comment by trefethen** [comment]
I don't know the details of this particular matter, but my general view is that Chebfun should not check for special symmetries like even or odd except for one exception: real inputs that mathematically should give real outputs should also do the same computationally.  (This came up in trigfun.)  It is just too confusing and distracting if there are imaginary rounding errors, not to mention the additional annoyance that such errors will change how MATLAB plots things.

**Comment by nickhale** [comment]
@trefethen - I believe that's the case here.
