### ISSUE TITLE
DCT and iDCT duplicated in RATINTERP().

### ISSUE THREAD

**Issue by nickhale** [chebfun/chebfun#1381]
`ratinterp()` has implementations of `dct1`, `dct2`, `idct1`, and `idct2` which aren't consistent with those in `chebfun.dct()` and `chebfun.idct()`. These should probably be removed.

There are two reasons for this (and other recent changes to using `chebfun.dct()`):
 * We don't really want the duplicated code
 * If Matlab ever gives access to the FFTW DCT implementations, this will make it easier to switch too.

**Comment by ajt60gaibb** [comment]
... and the DCT and DST implementations in chebfun/dct and chebfun/dst will get better over time ...

**Comment by aaustin141** [comment]
Closed in #1596.
