### ISSUE TITLE
Testing of chebfun outerproduct

### ISSUE THREAD

**Issue by asgeirbirkis** [chebfun/chebfun#1382]
I'm working on a feature branch restoring the behaviour of calling ```kron``` with three arguments, and getting a ```chebmatrix/linop``` output. Going through the current tests, I noticed that currently, there don't appear to be any test for ```chebfun/outerProduct```, or for the behaviour of calling ```f*g'```. There is a reminder in ```tests/chebfun/test_mtimes``` saying ```% TODO: Test Chebfun2 outerproducts!```, It's worth mentioning that ```test_kron``` also tries them indirectly.

I'm happy to write some as part of my pull request, however, it'd be nice if @ajt60gaibb could confirm that the tests I write are indeed testing the correct things.

**Comment by ajt60gaibb** [comment]
I can take a look at the tests when you are ready.

**Comment by asgeirbirkis** [comment]
Closed via #1385
