### ISSUE TITLE
Solving a periodic ODE with additional constraints

### ISSUE THREAD

**Issue by rothos** [chebfun/chebfun#1389]
The code below solves a parameter-dependent 2nd-order ODE with periodic boundary conditions. There is also an additional condition (y'(0) = 1) to account for the degree of freedom introduced by the parameter.

```
L = chebop(@(t,y,p) diff(y,2) + sin(t).*p, [-pi pi]);
L.bc = @(t,y,p) [ y(pi)-y(-pi);
                  feval(diff(y),pi)-feval(diff(y),-pi);
                  feval(diff(y),0)-1 ];
[y,p] = deal( L \ 0 );
```

The problem is entirely periodic and the solution is smooth, but currently it cannot be solved using trigonometric collocation. Trying to set the default discretization to @trigcolloc gives an error:

```
pref = cheboppref;
pref.discretization = @trigcolloc;

L = chebop(@(t,y,p) diff(y,2) + sin(t).*p, [-pi pi]);
L.bc = @(t,y,p) [ y(pi)-y(-pi);
                  feval(diff(y),pi)-feval(diff(y),-pi);
                  feval(diff(y),0)-1 ];
[y,p] = deal( solvebvp(L,0,pref) );
```

```
Error using chebop/clearPeriodicBCs (line 22)
TRIGCOLLOC only works with periodic boundary conditions.
Error in chebop/solvebvp (line 164)
    [N, L] = clearPeriodicBCs(N, L);
```

**Comment by Hadrien-Montanelli** [comment]
@asgeirbirkis It might be possible, I'll try to look at this next week.
