### ISSUE TITLE
Applying operatorBlocks to ADchebfuns

### ISSUE THREAD

**Issue by asgeirbirkis** [chebfun/chebfun#1390]
This came up wheh @hrothgar and I were investigating the example that lead to #1388. Applying operatorBlocks to ADchebfuns is currently not supported, which might be useful in some cases:

```
>> u = adchebfun(@(x) x);
>> D = operatorBlock.diff([-1 1]);
>> D*u
No appropriate method, property, or field iszero for class adchebfun.
Error in adchebfun/subsref (line 1314)
                    out = f.(index(1).subs);
Error in operatorBlock/mtimes (line 158)
                C.iszero = A.iszero || B.iszero; 
```

**Comment by marjanmoradi** [comment]
i have this problem too, would you mind if you find the answer (how to remove this error) tell it to me?

**Comment by asgeirbirkis** [comment]
@marjanmoradi at the moment, we haven't implemented a fix for this bug, but I'll make sure to comment on this issue once a pull request for it gets issued!
