### ISSUE TITLE
Using Chebfun to compute Fréchet derivatives

### ISSUE THREAD

**Issue by asgeirbirkis** [chebfun/chebfun#1391]
In v4, we were able to compute the derivative of any chebfun with respect to any other chebfun. Due to changes in the code, we lost this capability. Recently, both @hrothgar and @Hadrien-Montanelli have approached me with questions about this functionality which they'd like to have. I suggest we have a method which given a function handle and chebfun inputs returns the Fréchet derivative of the function at the inputs, e.g.

```
f = @(x1,x2) [cos(x1) + diff(x2.^2); x1.^3 + diff(exp(x2))];
x1 = chebfun(@(x) x, [0 2]);
x2 = chebfun(@(x) x, [0 2]);
Jf = diff(f, x1, x2);
```

Essentially, this is what `chebop/linearize` does, but with a user-available syntax. I'm open for suggestion for the name of this proposed method, as well as the calling sequence.

**Comment by hrothgar** [comment]
I like this idea. The syntax and calling sequence you've suggested are fine to me, and `diff` is the natural name for such a method.
