### ISSUE TITLE
Output of chebops with periodic boundary conditions

### ISSUE THREAD

**Issue by jaurentz** [chebfun/chebfun#1400]
Should the output of the following be a chebfun or a trigfun?

```matlab
u = chebfun(@(x) cos(x), [-pi,pi], 'trig');
L = chebop(@(x,u) diff(u) + sin(x).*u,[-pi,pi],'periodic');
L(u)
```

**Comment by mhsnjvd** [comment]
I think it should be a trigfun.

**Comment by asgeirbirkis** [comment]
Same issue as usual, we can't construct ```x``` as trigfun, so ```sin(x)``` wil be a chebfun, and the product of ```sin(x)``` and ```u``` will be a chebfun.

**Comment by aaustin141** [comment]
Can we close this ticket?

**Comment by asgeirbirkis** [comment]
I can't see any way getting around the fact that `x` has to be constructed as a regular `chebfun`, which will inevitable cause `diff(u) + sin(x).*u` to be a standard `chebfun`. The only way around this would be to cast `L(u)` to a `trigfun` before it's returned in `chebop/feval`, but that might have some consequences further down the road...

**Comment by aaustin141** [comment]
Yeah... that was what I was thinking, too.  I don't see a way to do this without making it such that `x` is not a `chebfun` but some object that, when passed through a bunch of function handles, ends up giving us a "recipe" for building a `chebfun`, which we can then later opt to build using `trigtech`, but that may be too complicated to be worth doing.  I vote to close on those grounds.

**Comment by asgeirbirkis** [comment]
I concur.
