### ISSUE TITLE
chebfun2.movie did not make it to v5

### ISSUE THREAD

**Issue by asgeirbirkis** [chebfun/chebfun#1412]
It appears that the the ```chebfun2/movie``` method never made it to v5. There is a ```chebfun/movie``` method which I was unaware of, but the 2D version originally written by @ajt60gaibb seems to be missing.

I've just experimented running the v4 code in v5. It required only a few changes to reflect the changes in the data structure of the ```chebfun2``` objects (as the ```fun2``` class is no more), but with those changes and by bringing the code up to date with the coding style, it should be fairly straightforward to reintroduce this method.

**Comment by ajt60gaibb** [comment]
That's right. I never put `chebfun2/movie` in v4. I had it as a very low priority command. (I would suggest that it is still low priority.)

The main point of `chebfun2/movie` was for presentations to demonstrate how the adaptive 2D constructor works.   It is not really a 2D analogue of the MATLAB command `movie`.  Nowadays, I am not sure if it should be code kept in `Dropbox/chebfun_files` or in development.  (There could be a more natural version of the `chebfun2/movie` command.)

**Comment by trefethen** [comment]
@asgeirbirkis and I just had a chat and we agreed that he will show this to the group at our meeting on Wednesday and we will discuss what seems to be the right thing to do.  Our current feeling is that this is too neat not to have available, but perhaps it would best be renamed with a less cosmic name than "movie".  We hope to have a resolution to propose on Wednesday.

**Comment by ajt60gaibb** [comment]
Great. Perfect.

**Comment by ajt60gaibb** [comment]
What happened to @asgeirbirkis's efforts on the `chebfun2.movie` command (now called `chebfun2.explain')? I wanted to demo it to someone yesterday, thinking it must already be there. Quite embarrassing when I could not find it.

**Comment by asgeirbirkis** [comment]
Matlab 2014a vs b graphics issues held me up. I'm almost there but just have to tie a few loose ends (and find someone to review the code).
