### ISSUE TITLE
waterfall plots of chebfun2 objects have wrong colors

### ISSUE THREAD

**Issue by asgeirbirkis** [chebfun/chebfun#1417]
This came up while working on #1412, and inspired by #1416 I wanted to make an issue out of it to ensure it'd be dealt with. The following reveals that the colours of chebfun2 waterfall plots in Matlab 2014b are not correct, in the sense that rows and columns that belong to the same pivot are plotted in different colours. Futhermore, the pivot points are not plotted in colours that match the lines.
```
>> h = chebfun2(@(x,y) cos((x-.1).*(y-.2)));
>> rank(h)
ans =
     7
>> waterfall(h,'-o'); campos([0 0 10])
```
![chebfun2_waterfall](https://cloud.githubusercontent.com/assets/3543429/6442849/c7deff86-c0ea-11e4-83e5-7cfb3ebec331.png)

**Comment by aaustin141** [comment]
Closed in #1581, but see #1594.
