### ISSUE TITLE
Behaviour of the CHEBFUN/POLY() function.

### ISSUE THREAD

**Issue by nickhale** [chebfun/chebfun#1421]
The `@chebfun/poly()` method is consistent with the built-in `poly()` method, but differs substantially from the new `@chebfun/*coeffs()` methods (which were previously `@chebfun/*poly()`). 

Is it worth implementing a `polycoeffs()` (or perhaps `monocoeffs()`) method?

**Comment by trefethen** [comment]
@nickhale, could you clarify what you mean?  Perhaps give an example of what `poly` and `chebcoeffs` do and what you are proposing `polycoeffs` or `monocoeffs` might do?

**Comment by nickhale** [comment]
Sure:

```
>> f = chebfun(@exp);
>> poly(f)
ans =
  Columns 1 through 11
   0.000000000011710   0.000000000164234   0.000000002087145   0.000000025045352   0.000000275573805   0.000002755738208   0.000024801586936   0.000198412695299   0.001388888888992   0.008333333334132   0.041666666666655
  Columns 12 through 15
   0.166666666666571   0.500000000000001   1.000000000000004   1.000000000000000
>> monocoeffs(f)
ans =
   1.000000000000000
   1.000000000000004
   0.500000000000001
   0.166666666666571
   0.041666666666655
   0.008333333334132
   0.001388888888992
   0.000198412695299
   0.000024801586936
   0.000002755738208
   0.000000275573805
   0.000000025045352
   0.000000002087145
   0.000000000164234
   0.000000000011710
```

The difference is entirely cosmetic, but it does allow easy comparison via:
```
>> [chebcoeffs(f) monocoeffs(f)]]
ans =
   1.266065877752008   1.000000000000000
   1.130318207984970   1.000000000000004
   0.271495339534077   0.500000000000001
   0.044336849848664   0.166666666666571
   0.005474240442094   0.041666666666655
   0.000542926311914   0.008333333334132
   0.000044977322954   0.001388888888992
   0.000003198436462   0.000198412695299
   0.000000199212481   0.000024801586936
   0.000000011036772   0.000002755738208
   0.000000000550590   0.000000275573805
   0.000000000024980   0.000000025045352
   0.000000000001039   0.000000002087145
   0.000000000000040   0.000000000164234
   0.000000000000001   0.000000000011710
```

**Comment by trefethen** [comment]
Ah, I see, thanks.  My feeling is that the convenience of such a command would be outweighed by the confusion it might introduce -- we'd have two different commands with quite different names which produced the same result, except one the flipped transpose of the other.  

If MATLAB had a `monocoeffs` alternative to `poly` that users were already familiar with, that would change my view.

**Comment by nickhale** [comment]
My own confusion occurred when I expected `poly()` to return results in the same form as `chebcoeffs()`.

I don't feel particularly strongly about this.
