### ISSUE TITLE
Improving error messages/warning when solving ODEs with incorrect number of BCs

### ISSUE THREAD

**Issue by asgeirbirkis** [chebfun/chebfun#1433]
This comes out of a discussion with @trefethen , an issue encountered in part of preparation for the ODE book.

If we try to solve an ODE that lacks the right number of BCs, like
```
L = chebop(0,1);
L.op = @(t,y) diff(y);
y = L\0;
```
we get a warning that's not particularly informative:
```
Warning: Matrix is not square!
> In linop.linsolve at 119
  In chebop.solvebvpLinear at 46
  In chebop.solvebvp at 176
  In chebop.mldivide at 47
>>
```
It would be nicer if we could output a message indicating that perhaps the user hasn't specified that right number of BCs.

In the example below, the system actually tries to solve the problem in collocation mode (as it only goes to IVP mode if it sees that one and only one of ```L.lbc``` or ```L.rbc```, and not ```L.bc``` have been assigned a condition).

The IVP mode does a slightly more clever thing, but only kicks in once something has been assigned ```L.lbc```:
``` 
>> L = chebop(@(u) diff(u,2) + u);
>> L.lbc = @(u) u-1;
>> u = L\0
Error using chebop/solveivp (line 184)
The number of initial/final conditions does not match the
differential order(s) appearing in the problem.

Error in chebop/mldivide (line 40)
    [varargout{1:nargout}] = solveivp(N, rhs, pref, varargin{:});
```

In v4, we actually got a more meaningful error:
```
>> cheb4 % change to v4 chebfun
>> L = chebop(0,1);
>> L.op = @(t,y) diff(y);
>> y = L\0;
Error using chebop/solvebvp (line 95)
CHEBOP:solvebvp:BCEmpty'All BCs empty.

Error in chebop/mldivide (line 55)
[varargout{1}, varargout{2}] = solvebvp(BVP,b);
```
So I propose we throw an error if no conditions are given, and furthermore, issue a more meaningful warning to suggest that incorrect number of conditions might have been passed if we encounter a non-square matrix.

**Comment by trefethen** [comment]
Thanks @asgeirbirkis.  As we work on the ODE book it's very fruitful that ODE-related user issues like this are coming up and getting addressed.  I appreciate it.

**Comment by asgeirbirkis** [comment]
With 7f2bdb8b, we now get the following more meaningful errors and warnings when we encounter incorrect number of BCs:

No BCs
```
L = chebop(0,1);
L.op = @(t,y) diff(y);
y = L\0;

Error using chebop/solvebvp (line 102)
All boundary conditions are empty.
Error in chebop/mldivide (line 47)
    [varargout{1:nargout}] = solvebvp(N, rhs, varargin{:}); 
```

Too few BCs in IVP mode
```
L = chebop(@(u) diff(u,2) + u);
L.lbc = @(u) u-1;
u = L\0
Error using chebop/solveivp (line 184)
The number of initial/final conditions does not match the
differential order(s) appearing in the problem.
Error in chebop/mldivide (line 40)
    [varargout{1:nargout}] = solveivp(N, rhs, pref, varargin{:}); 
```

Too few BCs in collocation mode
```
>> L = chebop(@(u) diff(u,2) + u);
>> L.bc = @(u) u(0)-1;
>> u = L\0
Warning: Operator may not have the correct number of boundary conditions.
Matrix is not square. Problem may be ill-posed. 
> In linop.linsolve at 118
  In chebop.solvebvpLinear at 46
  In chebop.solvebvp at 184
  In chebop.mldivide at 47 
```
Too many BCs in collocation mode:
```
 L = chebop(@(u) diff(u) + u);
>> L.bc = @(u) [u(-1)-1; u(1)+2];
>> u = L\0
Warning: Operator may not have the correct number of boundary conditions.
Matrix is not square. Problem may be ill-posed. 
> In linop.linsolve at 118
  In chebop.solvebvpLinear at 46
  In chebop.solvebvp at 184
  In chebop.mldivide at 47 
```
