### ISSUE TITLE
Passing an initial guess with correct dimensions to chebop

### ISSUE THREAD

**Issue by hrothgar** [chebfun/chebfun#1437]
The documentation for chebop states that if the system doesn't correctly identify which variable of an op is a parameter, you can manually specify one by passing an initial guess with the correct dimensions of the solution. However, doing so doesn't seem to work:

```
% Gives an error, as expected:
L = chebop(@(x,u,c) u, [-1 1], @(x,u,c) u(0)-c);
f = chebfun(@exp);
u = L \ [f; 0];

% Gives a different error, but should work:
L.init = [chebfun('x'); 0];
u = L \ [f; 0];
```

See also https://github.com/chebfun/chebfun/issues/1209#issuecomment-63653265.

**Comment by asgeirbirkis** [comment]
One reason is that the last argument to the chebop constructor gets assigned to the .bc field:
```
>> L = chebop(@(x,u,c) u, [-1 1], @(x,u,c) u(0)-c);
>> L.bc
ans = 
    @(x,u,c)u(0)-c
```
So passing a chebmatrix to the rhs of \ in the second chunk of code doesn't match the dimensions of the operator.

Also, I'm still not convinced that we should spend time worrying about problems that are not differential/integral equations.
