### ISSUE TITLE
Displaying operators as equations

### ISSUE THREAD

**Issue by tobydriscoll** [chebfun/chebfun#1443]
The following output doesn't seem right to me.

```
>> chebop(@(y)diff(y))
 
ans =
 
   Linear operator:
      diff(y) = 0

>> chebop(@(y)diff(y).^2)
 
ans =
 
   Nonlinear operator:
      diff(y).^2 = 0
```

An operator isn't an equation, so why is the "= 0" shown?

**Comment by trefethen** [comment]
Yes, I agree, that seems odd.  Thoughts @asgeirbirkis?

**Comment by asgeirbirkis** [comment]
Agreed, another issue related to the displaying of chebops is #1293, I'll deal with both these issues in the same upcoming pull request.
