### ISSUE TITLE
bug in ODE interpretation of BCs

### ISSUE THREAD

**Issue by trefethen** [chebfun/chebfun#1444]
In writing an example in the ODE book I found that the following code produces two identical plots, whereas they should be different:
```
L = chebop(0,50);
L.op = @(t,y) diff(y,2) + y;
subplot(2,1,1), L.lbc = @(y) [y-1; diff(y)]; plot(L\0)
subplot(2,1,2), L.lbc = @(y) [y-1; diff(y,2)]; plot(L\0)
```
Somehow or other, chebfun interprets `diff(y,2)` (also `diff(y,77)`) as the same as `diff(y)`.

Ideally, Chebfun should solve the problem stated.  If that's not feasible, one would hope it would at least detect that `diff(y,2)` has been written and generate an error message.  @asgeirbirkis, can you take a look?

**Comment by asgeirbirkis** [comment]
The Matlab solvers that we employ for solving IVPs don't support the second problem; for an nth order problem, the initial values of the (n-1)st derivatives have to be supplied (although the first order reformulation code supports the initial conditions to be supplied in an arbitrary order). So I think throwing an error is the best we can do here, I have a pull request coming up for that which does so.
