### ISSUE TITLE
Solving a highly nonlinear differential equation which includes a square-root

### ISSUE THREAD

**Issue by ErashMuhs** [chebfun/chebfun#1457]
Hi all together,

I am quite new here and I am currently working the first time with chebfun. I am very astonished about the simplicity and simultaneous strength of the Chebfun-approach and would like to support my PhD-thesis by using this evaluation technique.
 
I have a relatively complex problem which consists of the solve of a highly nonlinear differential equation including a square-root of the operator. I don't want to discuss the problem in detail but tried to simplify it as much as possible and reduced it to the solve of the equation y'=sqrt(y) which has the solution y~x^2.
 
The following code is solving the problem easily:

> N = chebop(0, 10);
> N.op = @(u) diff(u,1) - sqrt(u);
> N.lbc = 1;
> u = solveivp(N,0);

Also the use of the backslash operator solves the equation correctly. (u=N\0); Yet, using solvebvp(N,0) results in the following error-message,
 
> Error using chebtech/extrapolate (line 33)
> Too many NaNs/Infs to handle.
> Error in chebtech/populate (line 128)
>    [values, maskNaN, maskInf] = extrapolate(f, values);
> Error in chebtech2 (line 100)
>            [obj, values] = populate(obj, op, data.vscale, data.hscale, pref);
> Error in chebtech2.make (line 20)
> f = chebtech2(varargin{:});
> Error in chebtech/compose (line 81)
> f = f.make(op, data, pref);
> Error in chebtech2/compose (line 70)
> f = compose@chebtech(f, op, g, data, pref);
> Error in  .^  (line 39)
>	g = compose(f, @(f) power(f, b), [], [], pref);
> Error in  .^  (line 31)
> f.onefun = power(f.onefun, b);
> Error in chebfun/power>columnPower (line 205)
>             g.funs{k} = power(f.funs{k}, b);
> Error in  .^  (line 60)
>            g(k) = columnPower(f, b(k), pref);
>Error in  .^  (line 1010)
>                f.jacobian = operatorBlock.mult(b.*power(f.func, b-1), ...
>Error in adchebfun/sqrt (line 1281)
>            f = power(f, 0.5);
>Error in @(u)diff(u,1)-sqrt(u)
>Error in chebop/solvebvp>@(x,u)N.op(u) (line 71)
>    N.op = @(x, u) N.op(u);
>Error in chebop/feval (line 186)
>    out = N.op(x, u);
>Error in chebop/linearize (line 131)
>    Nu = feval(N, x, u{:});
>Error in chebop/solvebvp (line 96)
>[L, residual, isLinear] = linearize(N, u0, x);
>Error in Test8 (line 6)
>u = solvebvp(N,0);
 
even if the help of "bvpsolve" suggests that "U = solvebvp(N, RHS) has the same effect as U = N\RHS". However, to solve my highly nonlinear equation, I have to fall back on the use of solvebvp or the nonlinear backslash operator which both end up in a similar error. Does someone has a suggestion or an explanation for the discrepancy between those two approaches?

Thanks a lot for your help and best greetings from Germany,

Gregor

**Comment by ErashMuhs** [comment]
I already got an answer (thanks for that!)

> Hi Gregor
>
>It seems that the help text in solvebvp() is slightly outdated.
>In fact the approach now used for IVPs differs significantly
>to that for BVPs. (Asgeir Birkisson can explain the differences
>in detail if required).
>
>Anyway, I believe the reason solvebvp() is failing is because
>the nonlinear solver is using zero as an initial guess, for which
>the Jacobian is singular. You can easily fix this with the following:
>
>   N = chebop(0, 10);
>   N.op = @(u) diff(u,1) - sqrt(u);
>   N.lbc = 1;
>   N.init = 1; % <-- Use u = 1 as initial guess
>   u = solvebvp(N,0)
>
>u =
>   chebfun column (1 smooth piece)
>       interval       length     endpoint values
>[       0,      10]        3         1       36
>epslevel = 1.346401e-15   vscale = 3.600000e+01
>
>What I'm not sure of however, is
> a) why it chooses a guess of 0 rather than 1.
> b) whether we can detect situations like this and throw a more
>     sensible error message.
>Perhaps Asgier has some thoughts on these matters too.
>
>Best regards and greetings from South Africa.
>
>Nick
>

**Comment by aaustin141** [comment]
Resolved with @nickhale's e-mail reply, which is copied above in the previous comment.
