### ISSUE TITLE
A singfun plotting crash related to x-limits.

### ISSUE THREAD

**Issue by aaustin141** [chebfun/chebfun#1464]
The following crashes with an error that seems to come from the part of `singfun.plotData` which is responsible for setting x-limits:
```
>> dom = [2*pi/3, pi];
>> op = @(x) 3./sin(3*(x + pi)/2) - 1./sin((x + pi)/2);
>> f = chebfun(op, dom, 'exps', [0 -1]);
>> plot(f);
Index exceeds matrix dimensions.
Error in singfun/plotData (line 106)
    data.xLim(2) = data.xLine(idxr);
Error in bndfun/plotData (line 20)
    data = plotData(f.onefun);
Error in chebfun/plotData (line 38)
        dataNew = plotData(f.funs{k});
Error in chebfun/plot (line 242)
                newData(k) = plotData(f(k)); 
```
The triggering of this error seems to be somewhat sensitive to the input parameters.  For instance, if I do `dom = [0, pi]` instead, the call to plot succeed, though the construction of the `chebfun` fails.  

The function constructed here is a bit pathological in the sense that it's a "`singfun` which isn't":  there really isn't a pole at `pi`.  In fact, the function has a zero there.  I'm not sure if this has much to do with anything, but at any rate, it shouldn't cause the the call to `plot` to crash.

**Comment by kuanxu** [comment]
@aaustin141 Thanks for pointing this out. The bug is now fixed by #1516 and all tests pass.
