### ISSUE TITLE
Allen-Cahn demo in chebgui is slow

### ISSUE THREAD

**Issue by asgeirbirkis** [chebfun/chebfun#1465]
As pointed out by @trefethen, the Allen-Cahn demo in chebgui runs much slower in v4 than it did in v5.

My investigation leads me to think it’s actually not a v4/v5 issue, but more to do with plotting at each timestep. If I export the problem from the GUI, and run in v5.0, it takes 4.00 seconds, while it takes 4.07 seconds on the current version of development. But if I run the demo straight from the GUI, rather than an m-file, it takes much longer.

These are the times I get when solving the problem in chebgui:
With plotting of every time step enabled: Elapsed time is 1.434559 seconds.
With plotting of every time step disabled: Elapsed time is 8.025111 seconds.

It appears that the slowdown we’re seeing is due to changes we made in order to make the code (and in particular, chebgui) work for 2014b graphics of Matlab.

The code does not do anything special (yet) about periodic BCs in PDEs, so it’s not due to a change in the way we treat those.

For reference, solving the exported script from v4 takes 6.129 seconds, so if we crack this, we’ve actually gained a decent amount of speed!

**Comment by asgeirbirkis** [comment]
These are the speeds I get on the branch whose pull request is #1476, compared with development, running on my laptop:

Allen-Cahn chebgui demo
```
|                       | Development | New branch | 
|In chebgui             |    9.91s    |    3.60s   |
|Exported, plotting on  |    4.68s    |    3.31s   |
|Exported, plotting off |    1.44s    |    1.46s   |
```

Diffusion-reaction coupled PDE chebgui demo
```
|                       | Development | New branch | 
|In chebgui             |    6.93s    |    2.55s   |
|Exported, plotting on  |    4.71s    |    3.74s   |
|Exported, plotting off |    2.42s    |    2.38s   |
```
So pretty significant speedups, the plotting looks much smoother!

**Comment by nickhale** [comment]
Why does the `Exported, plotting on` take so much longer than `In chebgui` for the coupled PDE?

**Comment by asgeirbirkis** [comment]
@nickhale The waterfall plots are actually not included in the timing, in the exported script, I'm measuring time via
```
%% Call pde15s to solve the problem.
tic
[t, sol] = pde15s(pdefun, t, sol0, bc, opts);
toc
```
and in `solveGUIpde.m`, it's measured at
```
try
    tic
    [t, u] = pde15s(DE, tt, u0, bc, opts);
    toc
catch ME
    errordlg('Error in solution process.', 'chebopbvp error', 'modal');
    varargout{1} = handles;
    return
end
```

It doesn't appear to me that it's just a fluke that `chebgui` was faster, I tried running it again now and still got similar results.
