### ISSUE TITLE
Where should we store developer files?

### ISSUE THREAD

**Issue by asgeirbirkis** [chebfun/chebfun#1468]
@nickhale and I were talking about his script for comparing different (git) versions of Chebfun, cf. discussion in #1403.

I like his script, the main question before issuing a pull request is where it should be stored. The script can be categorised as something that's "very useful for Chebfun developers, not so much for the standard user". Other stuff in the same category is the script for publishing examples (currently maintained by @hrothgar), and the nightly-testing scripts (currently maintained by @aaustin141).

Sticking to the philosophy of an open source project, and also for ensuring things don't get lost by only storing them locally, it'd be wise to somehow bring those under version control. The question is how we should do so. I can think of three ways:

1. Create a separate folder in the main Chebfun repo.
2. Store them in the +cheb folder.
3. Create a new git repo, similar to what we have for the guide and examples. E.g. chebfun/developers on Github.

Any thoughts on how best to proceed?

**Comment by aaustin141** [comment]
Generally speaking, I don't think that these sorts of things belong in the main Chebfun repository; of the options listed, 3 sounds the most palatable to me.  Another option might be to upload them as gists and post them on the wiki.

Regarding the specific case of the script that does the nightly testing, I don't see any real reason to post it to GitHub at all.  I don't think most other folks will find it useful.  Moreover, it's set up to work specifically with the infrastructure we have at the MI here in Oxford and would require some modification before somebody else could run it on their own.  (The modifications aren't terribly difficult, but still.)

**Comment by davidagross** [comment]
:+1: on option 3, though I'd add that the nightly testing script could go in a place like that too.  Even if no other people would be able to run it without modification, their contributions could warrant collaboration or modification of those scripts.

**Comment by asgeirbirkis** [comment]
At the Chebfun meeting today (2015/05/06), we decided to go with option 3. @aaustin141 accordingly has created the repository chebfun/dev-tools, cf. https://github.com/chebfun/dev-tools . The plan is to gradually add our development tools there, i.e. we won't put our existing tools there all at once to begin with.

**Comment by nickhale** [comment]
Sounds good.
