### ISSUE TITLE
Testing of chebgui demos

### ISSUE THREAD

**Issue by asgeirbirkis** [chebfun/chebfun#1475]
Currently, we don't test automatically whether all our chebgui demos actually work. As I've only just discovered, eigenvalue problems are broken in chebgui in development, which really shouldn't have been possible to happen (fortunately, they're working on master). I'll run git bisect tomorrow to find out what caused this and hopefully issue a hot-fix pull request addressing it, but in the slightly longer run, we should look to automate the testing of the chebgui demos. This ties in with more extensive testing in general, cf. #1070.

**Comment by nickhale** [comment]
I'm not sure if this is related but when I click the "Test ALL demos" button in `chebgui` I get
```
bvp
pde
eig
TOTAL TIME = 0.0000.
```
This happens both in development and master..
