### ISSUE TITLE
Quasi-Chebyshev interpolation?

### ISSUE THREAD

**Issue by nickhale** [chebfun/chebfun#1499]
The default sampling strategy in Chebfun (at the time of writing) is 2nd-kind Chebyshev points with nested sampling. As a reminder, that means that since the every other node in grids of the size 1, 3, 5, 9, 17, ... 2^n+1, ... also appears in the next grid in the sequence, evaluated function values can be reused.

Quasi-Chebyshev nodes satisfy a similar property, but where the grid sizes grow like 2^{1/3} rather than doubling. (See [Sugiura & Hasegawa, 2011](http://dx.doi.org/10.1090/S0025-5718-2011-02484-1).) Fast FFT-based algorithms are still available for these points.

It might be interesting to see if interpolation at QCNs can be easily implemented in Chebfun and if this can provide any performance improvements (say, when sampling 'expensive' functions).

**Comment by trefethen** [comment]
I'm skeptical about this idea -- a decade of Chebexperience has shown us that even `resample` on or off makes little difference to get excited about.  My feeling is that this is an academic distraction that could add complexity with little benefit.  Of course I am happy to see evidence that this skepticism may be unjustified.
