### ISSUE TITLE
ultraS representations from diffmat() and additional outputs.

### ISSUE THREAD

**Issue by nickhale** [chebfun/chebfun#1509]
As far as I can tell, it isn't possible to obtain ultraS differentiation matrices from `diffmat()`. Is there a reason for this?

Furthermore, it would be useful if the `diffmat()` function returned (optional) additional outputs depending on the type of discretisation requested.

For example:
 (a) The rectangular projection matrix if cheb1 or cheb2 collocation is used.
 (b) The conversion matrices for ultraS representations.

My motivation for the this is mostly the latter, since at the moment I usually have to resort to writing five or six lines of code to generate ultraS diffmats and their conversion matrices by hand. Since Chebfun is probably **the** place to play with ultraS representations^\* it would be nice if this was made more accessible.

^\* In addition to ApproxFun, of course.

Do @ajt60gaibb or @kuanxu have any thoughts?

**Comment by kuanxu** [comment]
@nickhale I totally agree that we should have additional outputs, for both (a) and (b). Both of them are easy to implement, as we have the code in the bitbucket repo for our paper, right?

**Comment by ajt60gaibb** [comment]
What is wrong with  `ultraS.diffmat` and `ultraS.convertmat`?

**Comment by nickhale** [comment]
Because it's not _immediately_ obvious which conversion matrix corresponds to which differentiation matrix, particularly since the help text of `ultras.convertmat` is still wrong:
```
function S = convertmat(n, K1, K2)
%CONVERTMAT  Conversion matrix used in the ultraspherical spectral method.
%   S = CONVERTMAT(N, K1, K2 ) is a private method for constructing conversion
%   matrices. It returns the N-by-N matrix realization of the conversion
%   operator. The matrix S maps N coefficients in a C^{(K1)} basis to N
%   coefficients in a C^{K2} basis. Here, C^{(K)} is the ultraspherical
%   polynomial basis with parameter K.
```
```
>> full(ultraS.convertmat(5,0,0))
ans =
    1.0000         0   -0.5000         0         0
         0    0.5000         0   -0.5000         0
         0         0    0.5000         0   -0.5000
         0         0         0    0.5000         0
         0         0         0         0    0.5000
```

 * (a) The method doesn't appear to be private.
 * (b) If `K1` = `K2` I should expect to get an identity matrix, no?

Also `[D, S] = diffmat(5, 2, [0, 1], 'ultras');` seems nicer than
```
D = 4*ultraS.diffmat(5, 2);
S = ultraS.convertmat(m, 0, 1);
```
?

**Comment by ajt60gaibb** [comment]
Change the code in ultraS.convertmat so the help text is correct?
