### ISSUE TITLE
IVP solver is wrong for short forcing pulses

### ISSUE THREAD

**Issue by tobydriscoll** [chebfun/chebfun#1512]
There is something wrong with the IVP solver with certain forcing functions:

```
t = chebfun('t',[0 2]);
L = chebop(@(t) diff(t)+t,[0 2],1,[]);
u = L\0
```
Obviously, this is just exp(-t). 

If we put in a pulse for the forcing function:
```
>> pulse = 10*(t>1).*(t<1.1);
>> u_p = L \ pulse
u_p =
   chebfun column (3 smooth pieces)
       interval       length   endpoint values  
[       0,       1]       10         1     0.37 
[       1,     1.1]        7      0.37      1.3 
[     1.1,       2]       10       1.3     0.52 

>> difference = norm(u - u_p)
difference =
    0.6394
```
The new solution checks out. But if the pulse duration is too short, the solution doesn't even see it.

```
>> pulse = 20*(t>1).*(t<1.05);
>> u_p = L \ pulse
u_p =
   chebfun column (3 smooth pieces)
       interval       length   endpoint values  
[       0,       1]       10         1     0.37 
[       1,     1.1]        6      0.37     0.35 
[     1.1,       2]        9      0.35     0.14 
  Vscale = 1.  Total length = 25.

>> difference = norm(u - u_p)
difference =
     0
```

**Comment by nickhale** [comment]
This seems to be an issue with the MATLAB IVP solvers in general, rather than being Chebfun specific:
```
b = 1.04;
pulse = @(t) 10*(t > 1).*(t < b);
dydu = @(t,u,p) -u + pulse(t);
dom = [0, 1, (1+b)/2, b, 2];
sol = ode45(dydu, dom, 1, 0);
tt = linspace(0,2,1000);
uu = deval(sol, tt);
plot(tt, uu)
```

**Comment by tobydriscoll** [comment]
The ode solvers have a MaxStep property that could be set to, say, no more than a third of the length of the smallest subinterval.

**Comment by tobydriscoll** [comment]
Never mind, that's a terrible idea. MATLAB recommends the stop/restart trick in the docs:

"To make sure that the solver doesn't step over some behavior that occurs only once during the simulation interval. If you know the time at which the change occurs, break the simulation interval into two pieces and call the solver twice. If you do not know the time at which the change occurs, try reducing the error tolerances RelTol and AbsTol. Use MaxStep as a last resort."

I think that we should do this--the lack of robustness would be disturbing.

**Comment by nickhale** [comment]
One of the big performance gains in `pde15s()` from V4 to V5 was avoiding exactly this issue (i.e., bailing out of the ODE solver and restarting). However, there we were doing that 100s of times (one per time step) in every problem. I guess here it would just be once per interior breakpoint (if there is one).

It's annoying that the MATLAB solvers don't allow adding waypoints (i.e., t values which **must** be evaluated). 

FTR, I got around the problem in `pde15s()` by using passing handle in `odeset`s `.Events` field which is called at the end of each successful time step.

**Comment by asgeirbirkis** [comment]
We actually propagate breakpoint information for coefficients when we do the first order reformulation, so the stop/restart trick is definitely an option. I'll investigate this further.

**Comment by asgeirbirkis** [comment]
OK, via the restarting trick, I've got this problem sorted on a local branch.

However, we need to decide whether we only apply this trickery when problems are solved via chebop \, or whether we also apply it on the regular chebfun.ode113 etc methods. If we use it in the standard methods, those would become more than simple overloads of the standard Matlab methods, but at the same time, it would be weird to deliberately not use the best version of the code that we can just to respect that we're overloading the Matlab methods.

**Comment by asgeirbirkis** [comment]
On https://github.com/chebfun/chebfun/tree/fix-chebop-shortPulses , this example now runs as follows:
```
>> t = chebfun('t',[0 2]);
>> L = chebop(@(t) diff(t)+t,[0 2],1,[]);
>> u = L\0
u =
   chebfun column (1 smooth piece)
       interval       length     endpoint values  
[       0,       2]       12         1     0.14 
vscale = 1.
>> pulse = 20*(t>1).*(t<1.05);
>> u_p = L \ pulse
u_p =
   chebfun column (3 smooth pieces)
       interval       length     endpoint values  
[       0,       1]       10         1     0.37 
[       1,     1.1]        5      0.37      1.3 
[     1.1,       2]       10       1.3     0.51 
vscale = 1.325349e+00.   Total length = 25
>>  difference = norm(u - u_p)
difference =
    0.6486
```

For some reason, GitHub isn't allowing me to upload a plot of the solution, will try that again later.

**Comment by asgeirbirkis** [comment]
Here's the plot that GitHub wouldn't allow me to upload last night:
![shortpulse](https://cloud.githubusercontent.com/assets/3543429/9757085/3e684938-56d6-11e5-8972-b3996c750dc5.jpg)
