### ISSUE TITLE
What should we return if user calls f.epslevel?

### ISSUE THREAD

**Issue by asgeirbirkis** [chebfun/chebfun#1513]
Currently on the master branch, we try to give meaningful answer when a user enquires the epslevel of a function (although exactly how meaningful it is, and what the actual meaning is is debatable):
```
>> f = chebfun(@(x) sin(100*x));
>> f.epslevel
ans =
   1.1057e-14
```

However, with the merge of #1474, which disabled epslevels but didn't remove them, it is still possible to enquire a `chebfun` about its epslevel, however now, the result will be (even more) gibberish:
```
>> f = chebfun(@(x) sin(100*x));
>> f.epslevel
ans =
   2.2204e-16
```

Given the chance that there actually might be some users using the epslevel information, should we at least issue a warning if someone asks about the epslevel of a chebfun?

**Comment by trefethen** [comment]
Good idea.  The warning could say something along the lines of "epslevel now always returns machine epsilon and will be removed from Chebfun in the future".
