### ISSUE TITLE
chebellipseplot and the estimated strip of analyticity/chebstrip for a trigfun 

### ISSUE THREAD

**Issue by kuanxu** [chebfun/chebfun#1518]
This issue was encountered when @aaustin141 and I were investigating the stability of trigonometric barycentric formulae. For example:
```
f = chebfun(@sin, [0, 2*pi], 'trig')
chebellipseplot(f)
```
gives an ellipse, instead of a strip, which is not very reasonable. 
![ellipse](https://cloud.githubusercontent.com/assets/3542751/7898828/c9a52100-0704-11e5-952e-ce7cb0a947ef.png)

Should we make `chebellipseplot` work for both trig and non-trig cases by returning a strip for the trig case and an ellipse for the polynomial case? Or we throw an error when a trigfun is passed to `chebellipseplot` and create a new function (maybe called `chebtripplot`) to handle the trig case?

Notice that though @mhsnjvd has implemented `trigstripplot` in `@trigtech` to handle the actual computation of the strips, it has never been used.  

@aaustin141, @mhsnjvd, @Hadrien-Montanelli, @gradywright, Comments?

**Comment by aaustin141** [comment]
This is essentially a naming problem.  We encountered it once before with `plotcoeffs`, and I'd vote that we solve it the same way.  What we need is a function with a name along the lines of `plotRegionOfAnalyticity` (NB:  I'm not actually proposing this as the name; it's just an example.) which, maybe after some preprocessing for arguments to `plot`, delegates the responsibility for drawing the region to the techs.  The techs can then draw whichever region is appropriate for them.

**Comment by trefethen** [comment]
Thank you @aaustin141.  I like this idea and may I suggest the name `plotregion`?  (For consistency with  other Matlab/Chebfun conventions and `plotcoeffs`, it would not be `plotRegion`.)

Regarding what we tell users, however, I have a concern that I shall spell out in a new issue #1519 in a moment.

**Comment by kuanxu** [comment]
@aaustin141 and @trefethen Points taken. I'm on it.

**Comment by gradywright** [comment]
Just for the record, I created `fourstripplot`, which then became `trigstripplot` after the name change four-->trig.  Any implementation issues are my fault.

I do remember testing the method and finding the original estimate for the boundary (given by `a`) gave better results than the one that #1519 uses.  I recall getting the estimate from @trefethen's trapezoidal rule paper.

**Comment by kuanxu** [comment]
@gradywright Sorry for messing up with the true author! 

Actually, I tried to re-derive your estimate with @trefethen's trapezoidal rule and the trigfun paper. But I failed. The estimate you gave is `2/N(k)/pi*log(4/EPS+1)`. I couldn't see why the `+1` in log(4/eps+1) is helpful, neither the factor `4`. In fact, `N(k)` in your code is the degree of the trigonometric interpolant. If, instead of the degree, but the length (=degree+1) is used, I can always get better estimate. In fact, best estimate is always when `length+1` is used. But no theory backs this up. My understanding is no matter how carefully this estimate is designed, it can not deliver a very accurate estimate for all functions. It's just an estimate. The factor `4` and `+1` doesn't have any impact on the asymptotic behavior of the estimate.

**Comment by gradywright** [comment]
I used (3.24) of @trefethen's trapezoidal rule paper to get the estimate.  You are right that the term + 1 makes little difference, I think what I was going for in including it was so that others would be able to tell where the estimate comes from.  Clearly I failed with that.

**Comment by kuanxu** [comment]
@gradywright Thanks for pointing out that. I see why you have `2/N(k)/pi*log(4/EPS+1)` from (3.24). 

But my understanding is that (3.24) is the error bound for the trapezoidal rule, not for interpolation. If you look at Eqn (8.6) of ATAP or section 3 (p. A3011-A3012) of [Webb etal. 2012](http://epubs.siam.org/doi/abs/10.1137/110848797), you'll probably find that Eqn (4.2) of [Wright etal. 2015](https://people.maths.ox.ac.uk/trefethen/trigpaper.pdf) is more proper for estimating the width of the analyticity strip. Comments?
