### ISSUE TITLE
When and where to cut solutions of linear BVPs

### ISSUE THREAD

**Issue by asgeirbirkis** [chebfun/chebfun#1531]
@jaurentz spotted some peculiar behaviour of the solution process for linear BVPs (and thus, for the solving of Newton updates) which he brought to my attention, and I'm now convinced this is necessary fixing. It can be summarized as follows:

In `linop/linsolve` (lines 147-149), while iterating over different discretizations, we repeatedly call
```
% Test the happiness of the function pieces:
[isDone, epslevel, vscale, cutoff] = ...
    testConvergence(disc, u(isFun), vscale(isFun), prefs);
```
This gets repeated until ```isDone = true```, however, nothing gets done with the value of the `cutoff` variable. This is actually meaningful information, as it tells us where `plateauCheck` has decided it's correct to cut. Instead, we take all the computed collocation values, and pass to the chebfun constructor via
```
v = disc.toFunctionOut(values(:,k));
```
in line 171, which means that we end up with a `chebfun` of a way too long length (as we're passing a vector to the constructor, so no simplification takes place) -- even though we've found out above where it should be cut!

This results in `linop/linsolve` returning a too long `chebfun`, which we then try in various `chebop` methods to simplify at various points, which doesn't always work because of the last few coefficients of the solution when solved with collocation to be too large (`ultraS` manages to avoid that problem).

Take for example this problem, the exported "Interior layers (linear)" from chebgui:
```
dom = [-1 1];
N = chebop(@(x,u) .0005.*diff(u,2)+x.*(x.^2-0.5).*diff(u)+3.*(x.^2-0.5).*u, dom);
N.bc = @(x,u) [u(-1)+2; u(1)-4];
options = cheboppref();
options.discretization = 'collocation';
u = solvebvp(N, 0, options);
plotcoeffs(u)
hold on
semilogy([240 240],[1e-20 1e5],'k--')
```
This results in the following figure, where we've plotted with a black dashed line where `plateauCheck` told us to cut.
![plateaucut](https://cloud.githubusercontent.com/assets/3543429/8087316/03fe7e92-0f92-11e5-9fb0-f0ed6057a03a.png)

This is also the source of the behaviour we observe when solving nonlinear problems, where the length of the Newton updates has always been suspicious, like we see when we export "Interior layers, nonlinear" from chebgui:
```
dom = [0 1];
N = chebop(@(x,u) .01.*diff(u,2)+u.*diff(u)-u, dom);
rhs = 0;
N.bc = @(x,u) [u(0)+7./6; u(1)-3./2];
options = cheboppref();
options.display = 'iter';
options.discretization = 'collocation';
u = solvebvp(N, rhs, options);


Iter.   || du ||   Contraction    stepsize   len(du)   len(u)
--------------------------------------------------------------
 01     7.97e-01     6.72e-01     2.75e-01    128       128 
 02     4.93e-01     6.31e-01     6.88e-01    256       256 
 03     2.93e-01     8.15e-01      1.0000     512       512 
 04     1.53e-01     2.66e-01      1.0000     512       512 
 05     5.10e-02     3.34e-01      1.0000     724       724 
 06     5.79e-03     1.13e-01      1.0000     724       724 
 07     7.66e-05     1.32e-02      1.0000     724       724 
 08     3.22e-08     4.21e-04      1.0000     128       724 
 09     6.55e-11     2.03e-03      1.0000     128       724 
--------------------------------------------------------------
```

@jaurentz and I thus suggest we actually chop during `linop/linsolve`, one approach would be to pass the `cutoff` information into the `toFunctionOut` methods. We'd be interested to hear thoughts from others, particularly @tobydriscoll and others who have worked on the ODE side of the code.

**Comment by trefethen** [comment]
I agree, and these tails have often embarrassed me in talks.

There's a (happy) complication: @jaurentz and I are engaged in trying to modify Chebfun's ODE chopping strategy more fundamentally, giving it and the constructor and `simplify` all the same chopping rules (currently called `standardChop`, though that may evolve).  If we are successful, a solution to this problem reported in this issue will be part of that success.

**Comment by jaurentz** [comment]
Can we not also unify the behavior for IVPs? Shouldn't these all be fundamentally the same?

**Comment by aaustin141** [comment]
Can this issue be closed, now that `standardChop()` has been merged?

**Comment by asgeirbirkis** [comment]
Thanks @aaustin141 for bringing this up, [line 168](https://github.com/chebfun/chebfun/blob/development/%40linop/linsolve.m#L168) of `linop/linsolve` now gets passed the `cutoff` information like this issue was calling for, so closing it!
