### ISSUE TITLE
waterfall after solving a PDE takes a long time to be displayed

### ISSUE THREAD

**Issue by asgeirbirkis** [chebfun/chebfun#1538]
@trefethen and I were playing with the PDE solvers of Chebfun last week, and noticed that it takes the waterfall plots we often show after solving a PDE a long time to be actually displayed. At least this is the case for Matlab 2014b on a Mac.

For example, try running the following periodic Allen-Cahn PDE.  Notice that the output from the second `toc` doesn't really represent what goes on, i.e. it gets executed long before the figure is actually shown. My wall clock time is around 10 sec.

```
dom = [-3.5 3.5];
x = chebfun(@(x) x, dom);
u0 = -1 + 2*(exp(-17*(x + 2.6).^2) + exp(-15*(x + 1.3).^2) + ...
    exp(-13*x.^2) + exp(-11*(x - 1.3).^2) + exp(-9*(x - 2.6).^2)); 
pdefun = @(t,x,u) 0.01*diff(u,2) + u - u.^3;
bc = 'periodic';
t = linspace(0 , 80, 100);
opts = pdeset('Ylim', [-1.2,1.2]);
tic
[t, u] = pde15s(pdefun, t, u0, bc, opts);
toc
figure, waterfall(u, t, 'LineWidth', 2)
xlabel('x'), ylabel('t')
toc

Elapsed time is 8.335158 seconds.
Elapsed time is 8.945338 seconds.
```

**Comment by aaustin141** [comment]
Now that #1660 has been handled, can we close this issue?
