### ISSUE TITLE
Why is chebtech/qr not done like this? 

### ISSUE THREAD

**Issue by ajt60gaibb** [chebfun/chebfun#1542]
Hi @nickhale and @trefethen,

Is this a viable way to do `qr()` in `chebtech`?   On my machine it is x2 slower than the `chebtech2/qr()`, but with a bit of Nick Hale magic that could change.  It is certainly a simple approach. 

Idea:  Use the Legendre basis to relate the continuous QR to the discrete QR. Then, use discrete `qr()`.

```
function [Q, R] = myqr( A )
chebA = cheb2leg( A.coeffs );               % Get Legendre coefficients of array-valued chebtech
D = diag( 1./sqrt((0:size(legA, 1)-1)+.5) );% Orthonormalization constants.
[ Qleg, R ] = qr( D*legA, 0);               % Discrete QR
Q = chebtech2( { [], leg2cheb( D\Qleg ) } );% Construct continuous QR
Ds = diag( sign( diag( R ) ) );             % Ensure diagonals of R are of +ve sign.
R = Ds * R; Q = Q * Ds;
end
```

You can check that it computes the right thing with this code: 
```
A = chebtech2(@(x) [cos(100*x.^2), sin(100*x)]); 
[Qexact, Rexact] = qr( A );
[Q, R] = myqr( A ); 
normest( A - Q * R )
normest(Q - Qexact)
normest(R - Rexact)
```

**Comment by aaustin141** [comment]
To be clear---`chebtech` already does QR; there aren't specific `chebtech1` and `chebtech2` overrides for the `qr` method.  What you're suggesting is that we move to doing QR in coefficient space instead of in value space like it currently is, right?

**Comment by ajt60gaibb** [comment]
`chebtech1` and `chebtech2` both use the same Chebyshev basis so the code above works equally in both cases. 

Yes. I was asking why not use Legendre coefficients rather than values taken at Legendre points.

**Comment by nickhale** [comment]
Your way is certainly viable. I would expect the timings to be about the same. (You can probably speed up your code a little by doing the multiplication by `Ds` before you construct the `chebtech2`. Also the multiplication by diagonal matrices might be made faster using sparse or bsxfun.)

Values requires:
 * ndct, idlt and leg2cheb
Coeffs requries:
 * cheb2leg and leg2cheb

Since the idlt is a transposed cheb2leg, this would suggest your approach would be marginally faster (although the ndct is so fast that you probably wouldn't notice). If we has a _really_-fast indct, then values would definitely be preferable.

The advantage of the values-based approach is that it's the same as we use for small n.

**Comment by ajt60gaibb** [comment]
OK. And, this way will be a handful of lines. 

Here, the code is the same for small `n` because then `cheb2leg` and `leg2cheb` already use the direct approach.

**Comment by nickhale** [comment]
If you get rid of the fluff then the existing approach is also just a couple of lines. 

The code could be the same for the values approach also, but we don't do so in order to take advantage of caching (which is mostly for the benefit of Chebfun2).

**Comment by ajt60gaibb** [comment]
Ah, OK.   @nickhale, if you tell me coefficients is worth it then I can implement something.     

Two reasons why coefficients may be better: 

1. It may (very!) slightly more accuracy.   In principle one could use the decay in the columns to derive a better than 16-digit absolute QR in coefficient-space. Not very important, I suspect. 

2. It fits more neatly at the `chebtech` level because everything else is in coeff space. Again, a weak argument.

**Comment by nickhale** [comment]
I'm not sure it's worth it. 

As a side note, perhaps it's worth doing the *small* n in coefficient space. I image it's faster to set up the Vandermonde matrix using Legendre recurrence than it is to form the barycentric matrix?

**Comment by ajt60gaibb** [comment]
OK. Let's stop the discussion here then.  Thanks!  And nice to keep in mind. 

I did a few tests and my updated code is roughly the same speed as what is implemented already.  I'll post it in case we need it in the future: 

```
n = size(A.coeffs, 1); 
s = sqrt((0:n-1)'+.5);
legA = cheb2leg( A.coeffs );                % Get Legendre coefficients of array-valued chebtech
legA = bsxfun(@times, legA, 1./s ); % Orthonormalization constants.
[ Qleg, R ] = qr( legA, 0);               % Discrete QR
Ds = diag( sign( diag( R ) ) );             % Ensure diagonals of R are of +ve sign.
R = Ds * R; Qleg = Qleg * Ds;
Qleg = bsxfun(@times, Qleg, s );
Q = chebtech2( { [], leg2cheb( Qleg ) } );% Construct continuous QR
```

I do not think it is worth doing anything just for small `n`.
