### ISSUE TITLE
chebfun2 with periodic functions in only one dimension?

### ISSUE THREAD

**Issue by jrus** [chebfun/chebfun#1544]
As far as I can tell it’s only possible to have Chebfun2s be non-periodic or periodic in both dimensions at once (“rectangle mode” and “torus mode”). Is there any way to make it periodic in only one dimension (“cylinder mode”)?

**Comment by gradywright** [comment]
This is not possible yet, but we are working on it.  Once #1471 is merged, this feature will be added.

**Comment by ajt60gaibb** [comment]
Since #1471 has now been merged, one can now do this by making a subclass of the abstract class `separableApprox`.

**Comment by jrus** [comment]
Is there a summary explanation of how the in-progress `spherefun` / `diskfun` work? It seems from a cursory glance like they just loop twice over the domain and then try to ensure that the overlapping parts have the same values? [I haven’t really looked too closely though.]

I was trying to think about ways in which you could build a chebfun2-style approximation in cases where slices along the axes intersect in multiple places (so you can’t just naïvely take the tensor product and divide out by the value at the intersection). For instance, perhaps the function could be split into an even part and an odd part. The even part could take an approximation just the same way as for a rectangle or torus domain. The odd part would need some kind of additional compensating odd function in the product.

**Comment by ajt60gaibb** [comment]
@jrus: See here, http://arxiv.org/abs/1510.08094.

**Comment by jrus** [comment]
Thanks! Seems like another great paper.

**Comment by mkitti** [comment]
Does #2328 resolve this, @danfortunato @ajt60gaibb ?

**Comment by danfortunato** [comment]
Seems to!
