### ISSUE TITLE
exporting chebfuns as piecewise cubic beziers for plotting

### ISSUE THREAD

**Issue by jrus** [chebfun/chebfun#1545]
Currently anything related to plotting seems to happen through Matlab’s plotting system. This has the advantage of being familiar to Matlab users, presumably relatively straight-forward to implement, and easy to export as vectors or bitmaps. The resulting vectors (postscript format) files aren’t ideal though. Matlab applies very heavy rounding of point positions, to only a few significant figures, and every curve ends up with a very large number of points.

For example, here’s a screencap zoomed in on a pretty, colorful plot from Alex Townsend’s thesis:
<img width="586" alt="screen shot 2015-09-07 at 2 14 27 am" src="https://cloud.githubusercontent.com/assets/83411/9722594/e141e6b4-5564-11e5-893f-5db0182db59c.png">

This isn’t as big a problem for printing at normal zoom levels where the effect is only slightly visible, but it still noticeably slows down on-screen PDF rendering, especially on a slow machine:
<img width="348" alt="screen shot 2015-09-07 at 1 42 04 pm" src="https://cloud.githubusercontent.com/assets/83411/9722684/6ac2cfa6-5566-11e5-88e5-ccf8b8417cc4.png">

I assume most plots ultimately end up either on a web page or else in a PDF/postscript/SVG file (for printing or other use). All of these formats natively support cubic bézier curves (basically 2d cubic polynomials in terms of some parameter), as well as much higher precision than Matlab natively exports. Matlab’s many linear segments approach makes a lot of sense considering Matlab’s normal usage, in which everything is discretized, and plotted functions are arbitrary black boxes without a priori known derivatives or conditions on smoothness. It strikes me that chebfuns would be much better plotted using béziers though, especially for any purpose that requires very high resolution output, or wants to minimize file size or compute power required for plot drawing. Resulting output would also be useful in many other contexts.

The most obvious brute-force way to turn (smooth non-singular) chebfuns into béziers is to pick some maximum tolerated error, and then break the chebfun into tiny pieces by repeatedly bisecting its domain interval until each piece can be represented as a cubic polynomial within the allowed error. A real-valued chebfun f(t) representable as a cubic polynomial can be treated as a parametrized 2D function where x(t) = t and y(t) = f(t), while a complex-valued or 2d-vector-valued chebfun can be left as is, with the bezier segment parametrized in terms of the domain.

This is easy enough for me to implement myself for my own purposes, as a one-off, and I can get perfectly acceptable pictures out of it. But it’s still nowhere near ideal in terms of number of segments, not sufficient to handle functions with singular values or singular derivatives, and carefully handled bézier export is probably something that other people could benefit from having provided out of the box.

Even for smooth chebfuns and even assuming we want to output béziers with x(t) = t (which might be useful in contexts other than plotting, e.g. for defining [moving position in an animation](https://developer.mozilla.org/en-US/docs/Web/CSS/timing-function) or if some existing software needs a lookup table defined via piecewise cubic segments), there’s surely a better method than repeated bisection for partitioning the interval into as few segments as possible within the acceptable tolerance. Ideally, it would be kind of nice to be able to ask for _either_ a specific number of segments _or_ a desired maximum error, and receive an acceptable partition. I’m guessing there’s some existing body of literature with known algorithms to solve this problem, as plenty of people have been using bézier curves for practical purposes for a long time. As an outsider I am not familiar with that literature though and I don’t know where to look.

More generally, it might be desirable to make curves where the control points aren’t evenly spaced along the x axis, i.e. curves not parametrized in terms of the function input. This is a requirement for any curve with a singular derivative (like sqrt(x), etc.), but could also reduce the number of segments even for smooth functions. In such cases the tolerance would instead be some 2-dimensional distance between the function and the nearest point on the curve, the derivatives would likely need to match at the endpoints but the bézier control arms could be arbitrary lengths, and it might be useful to impose constraints on arclength or curvature w/r/t to the original function (human vision is pretty good at detecting lumpiness in curves). This is a somewhat more demanding problem, but I suspect there might also be relevant literature here.

Finally, for some uses it might be nice to export a chebfun as a piecewise linear function, again with arbitrary partition based on either a desired number of segments or a desired tolerance. There are many use cases where existing software tools or mathematical techniques require a piecewise linear function, but it’s still advantageous to use as few segments as possible. Again I’m guessing there are known techniques for this optimization, but I’m not familiar with them. Anyone have pointers?

Sorry for the extended comment. I’d be happy to offer some help with this, especially as relates to the browser context and SVG, as I have a bunch of diagrams I would like to make with Chebfun and embed in web pages, and I’m not satisfied with the existing plot options. I’m not sure if there should be a goal to support full plotting or just some tools for exporting the data as bézier control points in such a way that it’s easy to turn into a vector drawing using external tools.

**Comment by jrus** [comment]
Well, there seems to be a pretty enormous number of relevant papers here, and I’m slightly lost, but it seems like this algorithm could work if trying to get a (at least locally optimal; not sure it hits a global optimum) min-max C1 spline approximation, if implemented with the appropriate modifications to work with continuous functions and integrals instead of discrete sums.

Might be useful sometimes to use a bicubic Hermite interpolant (i.e. with function values and derivatives matching at the knot points) rather than this kind of approximant; perhaps both would be useful. I’ve only skimmed here, and at 1AM my eyes are glazing over with the mathematical formalism and Fortran code, so I’ll come look more carefully another day. There’s obviously been a great deal more work since these papers were written, so perhaps you folks in the approximation theory community know some better sources.

http://ftp.cs.wisc.edu/debooron/tr20.pdf
http://ftp.cs.wisc.edu/Approx/tr21.pdf

**Comment by jrus** [comment]
For the case where the line is all we care about (not the specific parametrization), Raph Levien’s PhD thesis has some nice material, starting from page 135:
http://www.levien.com/phd/thesis.pdf

Specifically, he wanted to convert piecewise clothoids to piecewise bézier segments, with applications to font rendering.

One interesting thing is his error metric. Rather than judging a bézier approximant based on distance from the original curve, he fixes arclength and then tries to minimize the least squares angle error integrated over arclength. This guarantees visual smoothness.

Considering Chebfun’s speed at doing function composition/etc., computing the reparametrization of a vector-valued chebfun in terms of arclength and then computing angle as a function of arclength should be reasonably fast.

**Comment by asgeirbirkis** [comment]
Hi Jacob,

Thanks for getting in touch! I don't think anyone of the current Chebfun team is  a graphic expert enough to be able to help out with the implementation of your ideas for generating curves for plotting; however, if you write your own implementation and generate graphics for embedding in web pages, please send us links to the results!

Best,
Asgeir

**Comment by jrus** [comment]
Okay, I’ll see what I can come up with. This more takes spline experience / polynomial approximation experience than graphics expertise per se, but I can at least implement a relatively inefficient and suboptimal first try. The results should still be useful in places where Matlab’s standard plot export doesn’t cut it.

**Comment by jrus** [comment]
I was trying to see if I could reparametrize a function in terms of arclength, but that involves taking the inverse of the cumulative arclength function, and it turns out that taking inverses is one operation that is potentially *very* slow in chebfun. There’s not too much about inverting functions in the user guide. Is there anywhere else I should look for more info about `inv`? Accurately reparametrizing in terms of arclength might just be a bad idea overall if there’s no reasonably quick algorithm for inverting a monotonic chebfun.

**Comment by jrus** [comment]
So as a first pass, I think I can compute signed curvature as a function of the parameter, and split at each place where the curvature has an extremum or inflection point. Next, subdivide until the 5th chebyshev coefficient at each segment is less than some threshhold. Finally, plot each segment as a 2 dimensional Bézier which has matching endpoints, derivatives at the endpoints, two equally-long “control arms”, and the same arclength as the original curve. This is definitely not going to be completely optimal in terms of number of points, but should be pretty quick to compute and not *too* far off. Or in any event it’ll be dramatically better than standard Matlab plot output.

**Comment by jrus** [comment]
It might be worth having doing 2 different things.

 1. Make piecewise (C¹) Hermite cubic polynomial segments parametrized the same as the original Chebfun. It’s pretty easy to test for error on an interval in a fast and parallelizable way (and just subdivide by bisection to get within tolerance) by just taking 8 chebyshev values on an interval, fft to get coefficients, sum the coefficients >4 and if the sum is beyond some threshold then bisect the interval and try again. My thinking is to first make breaks at all the extrema and inflection points, and then start subdividing from there. For complex or vector-valued chebfuns, just check the threshold for each dimension separately. I’ll try to post some code and pictures soon; this seems to work reasonably well.

    To get closer to an optimum number of cubic segments for a given tolerance, or to an optimum error for a given number of segments, the standard approach is apparently to take `cumsum(abs(diff(f, 4)) .^ .25)`, and divide it equally between the segments (see the papers linked a few posts up about “good” variable knots). I think this is going to be substantially slower than just doing recursive subdivision until a threshold is met though, and probably isn’t too often essential. Even more fully optimizing the knot positions than that is a tricky nonlinear optimization problem and probably not worth it.

    Possibly could also support linear, quadratic, or quintic segments, as they’re also somewhat frequently used in various existing systems. Lots of software is built around piecewise linear lookup tables, and quintic curves show up in CAGD.

    Unfortunately one-dimensional (`y = f(x)`) parametric polynomials can’t support everything because they blow up at singularities. So this isn’t a robust method for plotting any arbitrary chebfun. More robust and accurate plotting takes reparametrizing the curve....

 2. Make piecewise “geometrically continuous” (G²) cubic bézier curves (`(x, y) = f(t)`), by reparametrizing the function on each segment to match the position, tangent direction, and signed curvature of the original chebfun at each endpoint. For any given convex segment this can be done as recommended in the paper in the previous post. To make sure the segments are all “nice”, we can first insert breaks at every extremum or zero of signed curvature. What I don’t yet know how to do is make a computationally cheap test for the quality of fit between the original function and the approximation. Possible computationally expensive tests include the maximum error in angle as a function of arclength, or max distance between the two curves.

**Comment by jrus** [comment]
Okay, I finally found the thread of literature on this topic. It seems to start with
http://www.sciencedirect.com/science/article/pii/0167839688900039

What that paper says is something that seemed fairly obvious to me, but anyway, it says that you can bound the best reparametrized degree k approximation to some original parametric polynomial curve by just looking at the maximum error of an approximation that doesn’t touch the parametrization. So if you can subdivide enough to have a "good" approximation under the same parametrization (where good means the L∞ norm falls within the desired tolerance), then you know that when you optimize the parametrization your curve will also fall within the same tolerance.

This is a fairly weak seeming conclusion, but it’s probably a reasonable approach when the polynomial is somewhat “nice”. It probably works well in its original context of a reduction from polynomials of degree 7 down to 5 or 15 down to 7 or whatever. I think it’s a bit less useful when we have source polynomials with a degree in the thousands, because in that case reparametrizing could make a much bigger difference in error, so the error bound using the original parametrization doesn’t say very much, and using it as a guide could result in splitting into far smaller pieces than necessary.

But the paper has been cited 100+ times, so maybe there are some other ideas in later work.

**Comment by jrus** [comment]
Sorry folks, I got sucked down the rabbit hole of reading papers, instead of writing code. Probably skimmed a few hundred.

Anyway, here’s some simple code (just naïve brute force) to recursively subdivide a chebfun until all the segments can be represented by a cubic polynomial to within some threshold:

```matlab
function knots = cubic_bezier_knots(cfun)

threshhold = 1e-4;

unitcheb9pts = (chebpts(9) + 1) ./ 2 ; % chebpts on interval (0, 1)

% start the knot list off with all the extrema and inflection points
knots = unique([domain(cfun) roots(diff(cfun))' roots(diff(cfun, 2))']);

% each interval of the form [startpoint; width]
intervals = [knots(1:end-1); knots(2:end) - knots(1:end-1)];
while ~isempty(intervals)
    
    % make an array with 8 chebpts for each interval
    cheb9pts = bsxfun(@plus, bsxfun(@times, unitcheb9pts, intervals(2,:)), ...
                             intervals(1,:));
    cheb9vals = cfun(cheb9pts);
    cheb9coeffs = chebtech2.vals2coeffs(cheb9vals);
    residual = sum(abs(cheb9coeffs(5:end, :)), 1); % terms beyond cubic
    
    % make two new intervals for each interval which failed before
    intervals = intervals(:, residual > threshhold);
    intervals(2, :) = intervals(2, :) / 2;  % half the original width
    midpoints = sum(intervals, 1);
    intervals = [intervals, [midpoints; intervals(2,:)]];
    
    % add midpoints to the set of knots
    knots = [knots midpoints];
end

knots = unique(knots);  % sort the final knots

end
```

Then after we have the knot positions, we can make Bézier segments out of the C1 Hermite cubic polynomial which interpolates the values of the original chebfun and its first derivative at those endpoints.

**Comment by jrus** [comment]
There’s probably a cleaner way to write this, but here’s some code for spitting out bézier control points:

```matlab
function controlpts = hermite_c1_cubic_control_points(cfun, knots)

cdiff = diff(cfun);

controlpts = zeros(8, length(knots) - 1);
interval_third = (knots(1, 2:end) - knots(1, 1:end-1)) ./ 3;

controlpts(2, :) = real(cfun(knots(1, 1:end-1), 'right'));
controlpts(8, :) = real(cfun(knots(1, 2:end), 'left'));
controlpts(4, :) = controlpts(2, :) + ...
                   interval_third .* real(cdiff(knots(1, 1:end-1), 'right'));
controlpts(6, :) = controlpts(8, :) - ...
                   interval_third .* real(cdiff(knots(1, 2:end), 'left'));

% for real valued functions, we have f = (x, y(x)); for complex valued functions
% we have f = (real(y(x)), imag(y(x)))
if isreal(cfun)
    controlpts(1, :) = knots(1, 1:end-1);
    controlpts(7, :) = knots(1, 2:end);
    controlpts(3, :) = controlpts(1, :) + interval_third;
    controlpts(5, :) = controlpts(7, :) - interval_third;
else
    controlpts(1, :) = imag(cfun(knots(1, 1:end-1), 'right'));
    controlpts(7, :) = imag(cfun(knots(1, 2:end), 'left'));
    controlpts(3, :) = controlpts(1, :) + ...
                       interval_third .* imag(cdiff(knots(1, 1:end-1), 'right'));
    controlpts(5, :) = controlpts(7, :) - ...
                       interval_third .* imag(cdiff(knots(1, 2:end), 'left'));    
end

end
````

**Comment by jrus** [comment]
Testing if I can embed a SVG directly here in an html image src attribute in a github comment:

<img src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4KPCEtLSBHZW5lcmF0b3I6IEFkb2JlIElsbHVzdHJhdG9yIDE3LjAuMCwgU1ZHIEV4cG9ydCBQbHVnLUluIC4gU1ZHIFZlcnNpb246IDYuMDAgQnVpbGQgMCkgIC0tPgo8IURPQ1RZUEUgc3ZnIFBVQkxJQyAiLS8vVzNDLy9EVEQgU1ZHIDEuMS8vRU4iICJodHRwOi8vd3d3LnczLm9yZy9HcmFwaGljcy9TVkcvMS4xL0RURC9zdmcxMS5kdGQiPgo8c3ZnIHZlcnNpb249IjEuMSIgaWQ9IkxheWVyXzEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHg9IjBweCIgeT0iMHB4IgoJIHdpZHRoPSIxMDAwcHgiIGhlaWdodD0iMTAwMHB4IiB2aWV3Qm94PSIwIDAgMTAwMCAxMDAwIiBlbmFibGUtYmFja2dyb3VuZD0ibmV3IDAgMCAxMDAwIDEwMDAiIHhtbDpzcGFjZT0icHJlc2VydmUiPgo8cmVjdCBmaWxsPSIjMjg2MDVFIiBzdHJva2U9IiNGRkZGRkYiIHN0cm9rZS13aWR0aD0iMzAiIHdpZHRoPSIxMDAwIiBoZWlnaHQ9IjEwMDAiLz4KPHBhdGggZmlsbD0iIzNBMkUyNSIgc3Ryb2tlPSIjQzAwMDAwIiBzdHJva2Utd2lkdGg9IjEwIiBkPSJNOTEzLjMzMyw0OTguMzMzYzAsNTQuNTQyLTE3LjM0OSwxMDguOTEtNDguMjkzLDE1Mi41ODUKCWMtMzAuOTQ0LDQzLjY3Ni03NS4yNjMsNzYuMzkxLTEyMy40LDkyLjM4OWMtNDguMTM3LDE1Ljk5Ny05OS43NTEsMTUuMjA4LTE0My44MTktMC43NjVzLTgwLjI4My00Ni45NjYtMTAxLjE1NS04NC43NTgKCXMtMjYuMjY5LTgyLjA2NC0xNS42MjktMTIxLjcyYzEwLjY0LTM5LjY1NiwzNy4yMTUtNzQuMzY1LDczLjEwOC05NS4yMTFjMzUuODkzLTIwLjg0NSw4MC44MTYtMjcuNjM0LDEyMy45ODUtMTcuNjg2CglzODQuMjM5LDM2LjU5OCwxMTMuMTY0LDc1LjE2NWMyOC45MjUsMzguNTY3LDQ1LjQ2LDg4LjgwNCw0NC44NjgsMTQwLjYyNGMtMC41OTIsNTEuODE5LTE4LjM0NiwxMDQuODc0LTUwLjUyOSwxNDguMzQzCgljLTMyLjE4Myw0My40NjktNzguNjAyLDc3LjA2Mi0xMzAuMjgzLDk0LjEzYy01MS42ODIsMTcuMDY3LTEwOC4yOTQsMTcuNTA4LTE1OC42ODQsMS44NTRzLTk0LjIzNy00Ny4yNy0xMjMuMjU4LTg3LjM4CglzLTQzLjA1My04OC40MDctNDAuNDI5LTEzMy44ODRjMi42MjQtNDUuNDc3LDIxLjgzNS04Ny43OTMsNTEuOTQxLTExNy40YzMwLjEwNi0yOS42MDcsNzAuODM5LTQ2LjI4NiwxMTEuNzQ1LTQ2LjI4NgoJczgxLjYzOSwxNi42NzksMTExLjc0NSw0Ni4yODZjMzAuMTA2LDI5LjYwNyw0OS4zMTgsNzEuOTIzLDUxLjk0MSwxMTcuNGMyLjYyNCw0NS40NzctMTEuNDA4LDkzLjc3NC00MC40MjksMTMzLjg4NAoJcy03Mi44NjgsNzEuNzI1LTEyMy4yNTgsODcuMzhzLTEwNy4wMDIsMTUuMjE0LTE1OC42ODQtMS44NTRjLTUxLjY4Mi0xNy4wNjctOTguMS01MC42NjEtMTMwLjI4My05NC4xMwoJcy00OS45MzYtOTYuNTI0LTUwLjUyOS0xNDguMzQzYy0wLjU5Mi01MS44MTksMTUuOTQzLTEwMi4wNTcsNDQuODY4LTE0MC42MjRzNjkuOTk1LTY1LjIxNywxMTMuMTY0LTc1LjE2NQoJczg4LjA5Mi0zLjE1OSwxMjMuOTg1LDE3LjY4NnM2Mi40NjgsNTUuNTU1LDczLjEwOCw5NS4yMTFjMTAuNjQsMzkuNjU2LDUuMjQzLDgzLjkyNy0xNS42MjksMTIxLjcycy01Ny4wODcsNjguNzg1LTEwMS4xNTUsODQuNzU4CglzLTk1LjY4MiwxNi43NjItMTQzLjgxOSwwLjc2NWMtNDguMTM3LTE1Ljk5Ny05Mi40NTYtNDguNzEzLTEyMy40LTkyLjM4OVM4MCw1NTIuODc1LDgwLDQ5OC4zMzNzMTcuMzQ5LTEwOC45MSw0OC4yOTMtMTUyLjU4NgoJczc1LjI2My03Ni4zOTEsMTIzLjQtOTIuMzg5YzQ4LjEzNy0xNS45OTcsOTkuNzUxLTE1LjIwOCwxNDMuODE5LDAuNzY0czgwLjI4Myw0Ni45NjYsMTAxLjE1NSw4NC43NThzMjYuMjY5LDgyLjA2NCwxNS42MjksMTIxLjcyCgljLTEwLjY0LDM5LjY1Ni0zNy4yMTUsNzQuMzY2LTczLjEwOCw5NS4yMTFjLTM1Ljg5MywyMC44NDUtODAuODE2LDI3LjYzNC0xMjMuOTg1LDE3LjY4NgoJYy00My4xNjktOS45NDgtODQuMjM5LTM2LjU5OC0xMTMuMTY0LTc1LjE2NXMtNDUuNDYtODguODA0LTQ0Ljg2OC0xNDAuNjI0czE4LjM0Ni0xMDQuODc0LDUwLjUyOS0xNDguMzQzCglzNzguNjAxLTc3LjA2MiwxMzAuMjgzLTk0LjEzczEwOC4yOTQtMTcuNTA4LDE1OC42ODQtMS44NTRjNTAuMzksMTUuNjU0LDk0LjIzNyw0Ny4yNywxMjMuMjU4LDg3LjM4czQzLjA1Myw4OC40MDcsNDAuNDI5LDEzMy44ODQKCXMtMjEuODM1LDg3Ljc5My01MS45NDEsMTE3LjRjLTMwLjEwNiwyOS42MDctNzAuODM5LDQ2LjI4Ni0xMTEuNzQ1LDQ2LjI4NnMtODEuNjM5LTE2LjY3OS0xMTEuNzQ1LTQ2LjI4NgoJYy0zMC4xMDYtMjkuNjA3LTQ5LjMxOC03MS45MjMtNTEuOTQxLTExNy40Yy0yLjYyNC00NS40NzcsMTEuNDA4LTkzLjc3NCw0MC40MjktMTMzLjg4NHM3Mi44NjgtNzEuNzI1LDEyMy4yNTgtODcuMzgKCWM1MC4zOS0xNS42NTQsMTA3LjAwMi0xNS4yMTQsMTU4LjY4NCwxLjg1NGM1MS42ODIsMTcuMDY3LDk4LjEsNTAuNjYxLDEzMC4yODMsOTQuMTNjMzIuMTgzLDQzLjQ2OSw0OS45MzYsOTYuNTI0LDUwLjUyOSwxNDguMzQzCglzLTE1Ljk0MywxMDIuMDU3LTQ0Ljg2OCwxNDAuNjI0Qzc2Mi4zNjksNTM2LjksNzIxLjMsNTYzLjU1LDY3OC4xMzEsNTczLjQ5OGMtNDMuMTY5LDkuOTQ4LTg4LjA5MiwzLjE1OS0xMjMuOTg1LTE3LjY4NgoJYy0zNS44OTMtMjAuODQ1LTYyLjQ2OC01NS41NTUtNzMuMTA4LTk1LjIxMWMtMTAuNjQtMzkuNjU2LTUuMjQzLTgzLjkyNywxNS42MjktMTIxLjcyczU3LjA4Ny02OC43ODUsMTAxLjE1NS04NC43NTgKCXM5NS42ODItMTYuNzYyLDE0My44MTktMC43NjRjNDguMTM3LDE1Ljk5Nyw5Mi40NTYsNDguNzEzLDEyMy40LDkyLjM4OUM4OTUuOTg1LDM4OS40MjQsOTEzLjMzMyw0NDMuNzkyLDkxMy4zMzMsNDk4LjMzMyIvPgo8L3N2Zz4K">

**Comment by nickhale** [comment]
Hi @jrus. This looks neat!

I took a quick look at your code and the only (utterly trivial) comment I have is that you could use `unitcheb9pts = chebpts(9, [0, 1]);` rather than doing the scaling manually.

I tried to rummage through MATLAB's `contour` method, but it seems the part that determines what levels to use is buried in a .p file. (I didn't even realise they were still using those!). Presumably the easy thing to do is just produce a contour plot and grab the `.LevelList` property of the plot handle.

**Comment by jrus** [comment]
I spent some time yesterday working on the reverse problem: taking an arbitrary SVG path made up of linear, quadratic, or cubic bézier curve segments, and converting it to a chebfun. This should allow some more interesting types of art and lettering to be used as demonstrations than what can be produced by the `scribble` function.

* * *

This paper about using the chebyshev basis to interpolate cubic bézier curves has some of the same ideas expressed as my code up-thread:
http://graphicsinterface.org/wp-content/uploads/gi1991-3.pdf

Namely, it notes that a cubic polynomial in chebyshev basis is close to linear when the sum of absolute values of the last two coefficients fits within some error tolerance. (My code above did the same sort thing bounding the distance of a degree 8 polynomial to cubic.)

[Side note: for what it’s worth, I think in practice a degree 6 polynomial (i.e. found by interpolating at 7 chebychev points) may work just as well as a degree 8 polynomial, and should save a lot of evaluations, since at each binary subdivision of the interval, 3 of the points can be reused, so each subdivision takes only 4 new evaluations compared to 7 new evaluations in my scheme above (actually my code above just recomputes and does 9 new evaluations per interval, but in principle..). The degree 6 DCT-I (to find coefficients from values) is also a fair amount less work than the degree 8 DCT-I.]
