### ISSUE TITLE
some kind of portable standard chebfun data format for export

### ISSUE THREAD

**Issue by jrus** [chebfun/chebfun#1546]
One thing that could be pretty neat is a limited implementation of Chebfun in other programming languages that supported nothing but function evaluation, and possibly a small number of other features. A sort of “Chebfun viewer” library, as it were.

There are many places where it might be nice to use a Chebfun outside of Matlab, just treated as a black-box function, without necessarily a need to use it for quadrature, root finding, PDE solving, or whatever. It’s obviously possible (and not inordinately hard) to just explicitly implement a specific set of polynomial evaluations, but when there are multiple pieces, non-standard intervals, trigfuns or singfuns, or especially chebfun2s, it starts getting slightly tricky.

As one example, it might be pretty nice to have an implementation in Javascript for use in a browser. There are a bunch of places where people currently use slow univariate or bivariate functions in their JavaScript code that could be sped up by using barycentric interpolation of well chosen polynomials instead. In particular, there are a bunch of places where the right chebfun2 could be very handy. One example I’m thinking of is the [map projections in D3](https://github.com/d3/d3-geo-projection/) ([code](https://github.com/d3/d3-geo-projection/blob/master/d3.geo.projection.js)), some of which are extremely slow, especially when drawing complicated coastlines and trying to animate things.

It could also be handy for sending to a fast implementation written in C, C++, Rust, or whatever, optimized to efficiently take advantage of CPU caches and SIMD or possibly the GPU. The Chebfun library running in Matlab could potentially bundle one of its chebfuns up and send it to a fast implementation in a different process or even on a remote server somewhere for evaluation.

For interoperation with the partial chebfun ports implemented in Julia or Python or for future ports to other languages, or even for saving and loading chebfuns entirely within Matlab, e.g. emailing saved chebfun files around from person to person, I think it would be nice to have a standard serialization format, instead of exporting Matlab objects or uninterpreted raw data. In particular, having a carefully defined serialization format should help guarantee that a saved chebfun can be opened on different versions of Matlab, or future versions of chebfun, without breaking.

Edited section: After a couple hours of research, I think the best option would be to build on top of the HDF5 metaformat, which is fairly widely adopted in the scientific computing community. There are at least a dozen other possible choices of metaformats to build on, but HDF5 seems to have a Mathworks-supported Matlab implementation [it’s the basis for recent versions of Matlab .MAT format] and implementations in a wide range of other languages and environments, and at a glance seems to be plenty flexible to support the kinds of structures that might be needed to represent chebfuns, chebops, generic matlab arrays, chunks of matlab code, images, or whatever else might be nice to wrap into a little bundle.
https://en.wikipedia.org/wiki/Hierarchical_Data_Format
https://www.hdfgroup.org/HDF5/
https://www.hdfgroup.org/HDF5/doc/index.html

I’d be happy to help with implementation here if you folks are interested. If not, no worries. I can understand that you already have plenty on your plates, and you may want to reserve the right to continue radically changing your implementations and internal object structures. I can always just roll something for myself.

**Comment by asgeirbirkis** [comment]
Hi Jacob,

Since Chebfun is (currently) so heavily dependent on Matlab, we believe that it's most straightforward to stick to the mat format for exporting Chebfun objects from Matlab to files. You're correct that HDF5 is widely adopted in the scientific computing community, however, until we see evidence that Chebfun implementations in other languages are gaining traction and that it'll be necessary to have a file format that works between languages, we don't believe that it's worth implementing the chebfun data format you describe, in particular, taking into account that it would tie our hands regarding implementations and internal object structures.

Best,
Asgeir

**Comment by jrus** [comment]
I wonder how easy it is to parse .mat files and figure out all the relevant features of a chebfun from some environment other than Matlab.

If I end up needing to evaluate chebfuns in a webpage or C program at some point, I can always just implement something narrowly tied to the specific use.

I do think at some point you’d get a worthwhile advantage from a clearly specified standard storage format. Given that there are already partial chebfun clones in Python and Julia, and at some point there will likely be faster (at least partial) implementations in Fortran or C or as GPU programs, and I could certainly imagine partial implementations popping up in e.g. Javascript (for the browser), or Swift or Java (for mobile devices), I think you’d ultimately save some trouble by having a spec, since the alternative is typically having people run out and build ad-hoc non-interoperable custom solutions.

But in any case, it’s definitely not something that needs to be done right away, so it’s probably reasonable to table this for the moment.

**Comment by jrus** [comment]
I’m not working on this precisely yet, but I’ve been implementing some bits and pieces in JavaScript, and the speed is actually impressively reasonable at this point.

For example, Clenshaw’s rule for real-valued input is easy to implement (here’s a coffeescript version):
```coffeescript
clenshaw = (coeffs, eval_pts) ->
    for x in eval_pts
        x2 = 2 * x
        n = coeffs.length-1
        b_even = 0                                # b_{n+2}
        b_odd = if n % 2 then coeffs[n--] else 0  # b_{n+1}
        for i in [n..2] by -2
            b_even = coeffs[i]   + x2 * b_odd  - b_even # b_i
            b_odd  = coeffs[i-1] + x2 * b_even - b_odd  # b_{i-1}
        coeffs[0] + x * b_odd - b_even
```
...which compiles to JavaScript something like:
```var clenshaw = function(coeffs, eval_pts) {
  var b_even, b_odd, i, n, x, x2, _i, _j, _len, _results;
  _results = [];
  for (_i = 0, _len = eval_pts.length; _i < _len; _i++) {
    x = eval_pts[_i];
    x2 = 2 * x;
    n = coeffs.length - 1;
    b_even = 0;
    b_odd = n % 2 ? coeffs[n--] : 0;
    for (i = n; i >= 2; i -= 2) {
      b_even = coeffs[i] + x2 * b_odd - b_even;
      b_odd = coeffs[i-1] + x2 * b_even - b_odd;
    }
    _results.push(coeffs[0] + x * b_odd - b_even);
  }
  return _results;
};```

For small numbers of points, the lower Javascript function call overhead makes this handily beat the Chebfun version. At very large numbers of points, I get speed only a bit slower than Matlab running on one logical core, and I think there’s some slowdown in the JS version due to constantly pushing results to a variable-length array. Of course, Matlab’s vectorized operations get parallelized pretty well, so on my laptop with 4 logical cores, the Matlab version ends up around 4 times faster. I didn’t try putting the Javascript version in multiple web workers, using JS typed arrays, or implementing with asm.js.

For now I’m going to just come up with my own ad-hoc minimalistic data format for a piecewise-chebtech chebfun, and maybe write a simple matlab function for converting to such a format. The main goal is to get reasonable (fast, accurate) browser plotting working, first for a relatively static picture, and then later maybe including fancy features like panning and zooming with the mouse, hovering to see function values, etc.
