### ISSUE TITLE
coding conventions for whitespace/commas in arrays

### ISSUE THREAD

**Issue by jrus** [chebfun/chebfun#1605]
Looking at [wiki/Coding-style-conventions](https://github.com/chebfun/chebfun/wiki/Coding-style-conventions) there’s a suggestion to format arrays like:
```matlab
A = [ 1, 4, 7, x+5 ] * c/2;
B(:,[ 2, 3, end-1 ]) = z;
C = [ [ A; A-1 ], [ A.*2; A.*4 ], [ A+6; A ] ];
```

But reading the Chebfun codebase, it seems to be just as common (if not more common) to instead write:
```matlab
A = [1 4 7 x+5] * c/2;
B(:,[2 3 end-1]) = z;
C = [[A; A-1] [A.*2; A.*4] [A+6; A]];
```
or 
```matlab
A = [1, 4, 7, x+5] * c/2;
B(:,[2, 3, end-1]) = z;
C = [[A; A-1], [A.*2; A.*4], [A+6; A]];
```
and I also see some with spaces before and after semicolons like:
```matlab
D = [1 ; 2 ; 3];
```

Should style be made consistent throughout (perhaps just for new code or code already being modified for some other reason, to avoid polluting the git history) with one or another of those styles preferred, or should the local style be left to the discretion of individual authors, and the style guide changed to reflect that?

**Comment by nickhale** [comment]
I think we decided that this particular convention could be left at the discretion of the author. I've updated the wiki accordingly.

**Comment by jrus** [comment]
What about “Commas and semicolons will never be preceded by a space” and “Elements of vectors, matrices or cell arrays will always be separated by commas”?
