### ISSUE TITLE
`'trunc'` is very slow

### ISSUE THREAD

**Issue by trefethen** [chebfun/chebfun#1607]
In chapter 9 of ATAP, which I'm lecturing on tomorrow, some Chebyshev coefficients are computed with `'trunc'` to get projection as opposed to interpolation.  This has become very slow, e.g.:
```
>> tic, chebfun(@(x) sign(x),'trunc',100); toc
Elapsed time is 8.229960 seconds.
```
I am sure it was a good deal faster a few years ago.  Why is this so slow?

I've checked the complexity, and it grows linearly with the number of coefficients you request, which is reasonable.  So we seem to have the right exponent but a very poor constant.

**Comment by aaustin141** [comment]
I can't reproduce this slowdown.  To the contrary, I find that we've made `trunc` _faster_ than it was before.  Last year around this time, the current version of Chebfun was v5.0.1.  Running the following code
```matlab
Ntrials = 5;
t_total = 0;

chebfun(@(x) sign(x), 'trunc', 100);
for (k = 1:1:Ntrials)
        tic();
        chebfun(@(x) sign(x), 'trunc', 100);
        t = toc()
        t_total = t_total + t;
end

avg_time = t_total/Ntrials
```
under both v5.0.1 and development on R2013b and R2015b, I get the following table of average times:
```
v5.0.1 on R2013b              6.94 s
development on R2013b         5.15 s
v5.0.1 on R2015b              3.23 s
development on R2015b         2.36 s
```
The worst-case times aren't much different.

**Comment by trefethen** [comment]
Curious.  Last time I taught from ATAP was two years ago, so I would have been using v4.  Would you be able to check this in v4?

**Comment by aaustin141** [comment]
Here are the times for v4:
```
v4 on R2013b                  5.32 s
v4 on R2015b                  2.28 s
```
These are comparable to the ones we see running under development right now, though v5.0.1 was a bit slower.

**Comment by trefethen** [comment]
Interesting!  Well maybe I'm wrong about this.  I'll close the issue.  @aaustin141, thanks for this amazingly speedy investigation.
