### ISSUE TITLE
failure of ATAP Ex. 8.4(c) and proposed change to `sampletest`

### ISSUE THREAD

**Issue by trefethen** [chebfun/chebfun#1610]
An impressive feature of Chebfun is that it does a pretty good job with functions involving 0/0 like sin(x)/x.  In exercise 8.4(c) of ATAP there's a function of this kind, log((x+3)/4)/(x-1), with a 0/0 singularity at x=1.  In v4 this worked, but now it doesn't:
```
>> chebfun(@(x) log((x+3)/4)./(x-1));
Warning: Function not resolved using 65537 pts. Have you tried 'splitting on'? 
> In chebfun.constructor>constructorNoSplit at 120
  In chebfun.constructor at 63
  In chebfun.chebfun>chebfun.chebfun at 219 
```
Yet if you construct with 20 or 200 or 2000 points, it looks fine, with a beautiful clean coefficient plateau.  @jaurentz has investigated and found that the problem is that whereas in v4 `sampletest` was basically a sanity test, checking an arbitrary point not on a grid, in v5 `sampletest` is a stringent indeed.  In particular it tests the points 1-1e-12 and -1+1e-12 with a tolerance O(1e-12).

I propose that we (@jaurentz and I) modify `sampletest` to bring it closer to what it used to be.  A practical reason is to make Chebfun again work on Exercise 8.4(c) and such examples.  But there is also a conceptual reason.  As people know, @jaurentz and I have spent a lot of the last year trying to make Chebfun construction simpler, and in particular, to put pretty much the whole construction process in a single place where we can explain it and think about it and reason about it (and discuss it in a publication, in preparation), namely `standardChop`.  The current `sampletest` violates this organization and thus is an aspect of confusing constructor complexity that still persists.  Note that the very presence of the numbers 1e-12 is a reflection of the kind of arbitrariness that we have been trying to reduce - why 1e-12?

I hope nobody will object if @jaurentz and I go ahead and prepare a modified and less stringent `sampletest`.  If anybody knows particular arguments why the v4 `sampletest` was not stringent enough, would you let us know?  Thanks.

**Comment by aaustin141** [comment]
Now that #1614 has been merged, can this be closed?

**Comment by nickhale** [comment]
Looks good to me.
```
>> chebfun(@(x) log((x+3)/4)./(x-1))
ans =
   chebfun column (1 smooth piece)
       interval       length     endpoint values  
[      -1,       1]       19      0.35     0.25 
```
