### ISSUE TITLE
Typing error in JACPTS().

### ISSUE THREAD

**Issue by LourencoPeixoto** [chebfun/chebfun#1621]
Hi chebfun team,

I believe that there are two typing errors in jacpts().

Line 557:
`32*(mu-1)*(83*mu.^2-983*mu+3779)/15./a8.^5 - ...`
I believe that the correct is:
`32*(mu-1)*(83*mu.^2-982*mu+3779)/15./a8.^5 - ...`
See NIST, 2010 (10.21.19), and Royal Society, 1960, Math. tables, Vol X Bessel functions pt. II page xxxvii.

Line 565:
`t = phik + ((a^2-.25)*(1-phik.*cot(phik))./(8*phik) - ...`
I believe that the correct is:
`t = phik + ((a^2-.25)*(1-phik.*cot(phik))./(2*phik) - ...`
See NIST, 2010 (18.16.8).

Isn't it?

Cheers.

**Comment by nickhale** [comment]
Hi @LourencoPeixoto 

Excellent spot - thanks!
