### ISSUE TITLE
Syntax for evaluating derivatives

### ISSUE THREAD

**Issue by asgeirbirkis** [chebfun/chebfun#1624]
One thing that's been causing many of us frustrations for a long time is that we can't use syntax such as `u'(0)` to evaluate the first derivative of `u` at `x=0`. Instead, one has to use a more cryptic syntax like `feval(diff(u),0)`, which is not particularly intuitive. We have had to use this syntax in various examples, papers, and in the upcoming ODE book.

To rectify this, and enable us to use more attractive syntax in the ODE book, I suggest introducing a new `chebfun` method `deval`, for evaluating derivatives of chebfuns at point(s). The inputs would be a chebfun, points to evaluate at, and the order of the derivative (with default value 1). For example
```
u = chebfun(@sin);
deval(u, 1) % u'(1)
deval(u, .5, 2) % u''(.5)
deval(u, 0.1:0.01:0.2) % u'(0.1:0.01:0.2)
```
Note that there exists a Matlab method `deval` for evaluating structs returned from solvers such as `ode113`, this would not be the analogue of that method. I'm very open for suggestions for alternative names, input arguments etc (or even alternative approaches), but if no one complains, I should be able to code this up fairly soon.

**Comment by jrus** [comment]
In some other programming language you’d just write `diff(u)(0)`, but in Matlab of course that’s illegal syntax, and you need to write `du = diff(u); du(0)`.

I think getting around that deficiency by adding an extra shortcut function is more confusing than helpful, as it creates extra things for someone to learn, and chebfun already has quite a learning curve. You’d potentially need to add an extra `deval.m` file in about 20 places in the project.

One other note: when you start trying to combine deval with e.g. chebfun2, the function signature is going to start getting crazy.

**Comment by asgeirbirkis** [comment]
Yes, the `diff(u)(0)` syntax would also have been an attractive option, although as you point out, Matlab doesn't support it (while you get away with it with curly brackets). The  `du = diff(u); du(0)` approach is not fit for the purpose I have in mind (though perfectly fine in other situations), as I want to evaluate derivatives inside anonymous functions, which don't support sequences of statements.

I'm not sure how much it adds to the learnings curve, compared with the current approach which requires learnings about `feval` (which we don't expect most users to be familiar with, `()` would be the standard syntax for evaluation).

**Comment by jrus** [comment]
Matlab’s inability to effectively compose various features is endlessly frustrating, and makes for so much hoop jumping.

What if you do something like `u(0, 'diff')`?

**Comment by trefethen** [comment]
I am eager to us to find a good syntax.  I like what @asgeirbirkis proposes but wonder if `deriv` should be the name rather than `deval`.  As always I am trying to think what makes sense for a user.

I have another related concern that comes up far more often when people use Chebfun ODEs, including every time you solve a 2nd-order IVP.  To impose two initial conditions, currently you have to write e.g.
```
L.lbc = @(y) [y-1; diff(y)-2];        % option A
```
Of course this is logical and I wouldn't want to eliminate it, but I wonder if users could be offered a more obvious option.   Could we think about simpler possibilities?  One might imagine for example
```
L.lbc1 = @(y) y-1;               % option B
L.lbc2 = @(y) diff(y)-2;
```
but actually I'm wondering about going further, since 90% of the time users want to prescribe y and y'.
One might also think along the lines of
```
L.lbcval = 1;                     % option C
L.lbcderiv = 2;
```
Discussion is needed of pros and cons and extensibility to systems and other things too... but in any case let me emphasize that in writing the ODE book I find that option A is an awkward point of current Chebfun syntax.

**Comment by asgeirbirkis** [comment]
One thing that might have been attractive was to allow array valued `lbc` to allow something similar to option B above but more general (and easier to maintain and implement), e.g.
```
L.lbc(1) = @(y) y;
L.lbc(2) = @(y) diff(y)-2
```
Unfortunately, Matlab doesn't allow arrays of function handles and recommends using cell arrays instead:
```
>> a(1) = @(y) y-1;
>> a(2) = @(y) 2*y
Nonscalar arrays of function handles are not allowed; use cell arrays instead. 
```
but I don't think we want users to use cell arrays.

So here's a pretty alternative approach, aimed at achieving something like option C. To me, `lbc` and `rbc` indicate a link with boundary value problems (they're after all called boundary conditions). For IVPs, we could simply have an `ic` field for specifying initial conditions (and a corresponding `fc` field for a final-value problems), that way, something simple like
```
L.ic = [1; 2]
```
would work. The ordering should be (for a problem with left endpoint `a`),
```[y(a), y'(a), ...]```
and for coupled systems, 
```[u(a), u'(a), ..., v(a), v'(a), ...]```
This is similar to how initial conditions are specified for the Matlab ODE solvers. I think this should fit well in with the first order reformulation algorithms, where significant effort is spent to get conditions specified via `L.lbc` precisely to the form of `L.ic` above.

**Comment by jrus** [comment]
> Unfortunately, Matlab doesn't allow arrays of function handles and recommends using cell arrays instead:

If you control the type of the `L.lbc` object, you can in principle overload its subsasgn method to do whatever you like.

**Comment by jrus** [comment]
Instead of `deriv` or `deval`, how about `diffval`?
