### ISSUE TITLE
Bug in FLAG=1 inside ASY1 from the command JACPTS. 

### ISSUE THREAD

**Issue by LourencoPeixoto** [chebfun/chebfun#1634]
Comparing some results from JACPTS and ULTRAPTS I could realize that the option `flag=1` in ASY1 from JACPTS() https://github.com/chebfun/chebfun/blob/fix-jacpts/jacpts.m (lines 364 and 389) sometimes is not the best choice. (The same problem occurs with the current version from JACPTS https://github.com/chebfun/chebfun/blob/development/jacpts.m)

*The results here are from JACPTS updated with #1623.*

Let's check the following results where `x0` and `w0` means that the points and weights were computed with `flag=0` in ASY1:

```
EDU>> [x, w] = jacpts(4e5, .1, .1);
EDU>> [x0, w0] = jacpts(4e5, .1, .1);
EDU>> norm((x0-x),inf)

ans =

     1.500022328571049e-12

EDU>> norm((w0-w)./w,inf)

ans =

     2.500130150826675e-04
```
In fact it means that the results are different in double precision. Now comparing using sum:
```
EDU>> sum(w*x)

ans =

    -7.496447906873982e-12

EDU>> sum(w0*x0)

ans =

     5.551115123125783e-17
```
but the exact value is `0`,
```
EDU>> sum(w*x.^2)

ans =

   0.589744113285009

EDU>> sum(w0*x0.^2)

ans =

   0.589744113292487
```
but the exact value is: `0.589744113292487`.

More examples:
```
EDU>> [x, w] = jacpts(4e5, -.1, .1);
EDU>> [x0, w0] = jacpts(4e5, -.1, .1);
EDU>> norm((x0-x),inf)

ans =

     1.500022328571049e-12

EDU>> a = find(abs((x0-x))>1e-12);
EDU>> length(a)

ans =

      107077

EDU>> norm((w0-w)./w,inf)

ans =

     1.697996552432114e-04
```
its sums:
```
EDU>> sum(w*x)

ans =

   0.203328147653992

EDU>> sum(w0*x0)

ans =

   0.203328147692610

EDU>> sum(w*x.^2)

ans =

   0.691315702116099

EDU>> sum(w0*x0.^2)

ans =

   0.691315702154875
```
And the exact values are:
`0.203328147692611` and `0.691315702154873`, respectively.

Once more:
```
EDU>> [x, w] = jacpts(2e5, .2, .2);
EDU>> [x0, w0] = jacpts(2e5, .2, .2);
EDU>> norm((x0-x),inf)

ans =

     5.250022638847440e-12

EDU>> a = find(abs((x0-x))>1e-12);
EDU>> length(a)

ans =

       87788
``` 
The sums:
```
EDU>> sum(w*x)

ans =

    -1.693903350918902e-11

EDU>> sum(w0*x0)

ans =

     1.110223024625157e-16

EDU>> sum(w*x.^2)

ans =

   0.526777573435884

EDU>> sum(w0*x0.^2)

ans =

   0.526777573452608
```
The exact values are: `0` and `0.526777573452608`, respectively.

Check yourself:
`n=4e5` with `alpha=.100001` and `beta=.1`;
`n=4e5` with `alpha=beta=-.15`;
`n=3e5`, `4e5` with `alpha=beta=.2`.

If we use `flag=1` in every `feval` in ASY1 the results become worse: 

```
EDU>> [x1, w1] = jacpts(2e5, .2, .2);
EDU>> sum(w1*x1)

ans =

     7.672765485522426e-06

EDU>> sum(w1*x1.^2)

ans =

   0.526785120523960
```
Furthermore I didn't find any example in which the `flag=1` is better than `flag=0`. I couldn't explain the reasons for it. Then until this problem is fixed I recommend use `flag=0` in ASY1. (The same seems occur in ULTRAPTS command, so this command has been using `flag=0` in ASY1 too).

**Comment by nickhale** [comment]
The flag is required for one final 'extended precision' computation to really nail the weights. the problem was that it wasn't quite picking up the correct sign of the values in some cases, hence giving these errors. I thought we mentioned this in the paper, but I can't find it right now.

I've pushed a fix and a test to the `fix-jacpts` pull request (#1623).

**Comment by LourencoPeixoto** [comment]
Great! Now it's ok!

**Comment by nickhale** [comment]
Cool - thanks again for pointing this out @LourencoPeixoto!
