### ISSUE TITLE
What should the single output behaviour from RATINTERP be?

### ISSUE THREAD

**Issue by nickhale** [chebfun/chebfun#1638]
When a user invokes `r = ratinterp(f, np, nq)` what is returned is a chebfun representation of the numerator `p` in the rational interpolant. This confused me for a while, as I was expecting a single output 
call to return the function handle `r = @(x) p(x)/q(x)` (since by itself `p` is not so useful?).  

The same is true of `chebpade()`. Note that `padeapprox()` returns the function handle as the first output.

Edit: `pade()` --> `padeapprox()`.

**Comment by mhsnjvd** [comment]
I think for the single output case the function handle should be returned.

**Comment by trefethen** [comment]
I agree.  Thanks for spotting this, @nickhale.  @mhsnjvd, I hope you can help make it happen.

**Comment by mhsnjvd** [comment]
Thanks  @nickhale !
