### ISSUE TITLE
Problem with chebfun/diff

### ISSUE THREAD

**Issue by bhashemi** [chebfun/chebfun#1641]
Let's try the following example in Chebfun2:
``
ff = @(x,y) x.^2 + x.*y.^2; f = chebfun2(ff); g = simplify(f);`` 
``
gx = diff(g,1,2); gx(0,0)``
``
ans =
    1
``
while this should be zero! There is nothing wrong with ``simplify`` here as can be seen by comparing ``plotcoeffs(f)`` with ``plotcoeffs(g)``. It seems that ``diff`` is responsible for this bug.

**Comment by aaustin141** [comment]
Can confirm this is some bug in `diff`.  Here's a simpler example that illustrates the issue:
```matlab
f = chebtech2(@(x) 1 + x + x.^2);
g = chebtech2(@(x) 1 - x + 2*x.^2);
Q = horzcat(f, g);
[get(diff(f), 'coeffs'), get(diff(g), 'coeffs')]
get(diff(Q), 'coeffs')
```
Running this prints the following:
```
ans =
   1.000000000000000  -1.000000000000000
   2.000000000000000   4.000000000000000
ans =
   1.000000000000000                   0
   2.000000000000000   6.000000000000000
```
The second columns of these matrices should be the same, but they aren't.  The coefficients in the first matrix that we obtained by differentiating `g` before making it the second column of a quasimatrix are correct, so it looks to me like this is some sort of issue with how we've vectorized this across columns.
