### ISSUE TITLE
Refactoring of ***PTS() methods

### ISSUE THREAD

**Issue by nickhale** [chebfun/chebfun#1645]
With the introduction of `ultrapts()` there's now considerable code overlap between the `legpts()`, `jacpts()`, and `ultrapts()` methods. I suggest refactoring these into a `quadpts()` method. 

To be clear, the `legpts()`, etc, methods would still exist, but simply be wrappers for a call to `quadpts()`.

Edit: Alternatively we bundle all the code in to `jacpts()`, since the others are a special case of this anyway. However, `quadpts()` might eventually allow for other non-Jacobi nodes and weights.

**Comment by LourencoPeixoto** [comment]
@nickhale , I proposed some modifications in JACPT and ULTRAPTS to they call the other particular cases. See #1650, and #1651.
