### ISSUE TITLE
unify "vscale" and "vertical scale" etc. displays

### ISSUE THREAD

**Issue by trefethen** [chebfun/chebfun#1646]
Chebfun and Chebfun2 currently display functions inconsistently:
```
>> chebfun(@(x) exp(x))
ans =
   chebfun column (1 smooth piece)
       interval       length     endpoint values  
[      -1,       1]       15      0.37      2.7 
vscale = 2.718282e+00.
>> chebfun2(@(x,y) exp(x))
ans =
   chebfun2 object: (1 smooth surface)
       domain                 rank       corner values
[  -1,   1] x [  -1,   1]        1     [0.37  2.7 0.37  2.7]
vertical scale = 2.7 
>> 
```
Please can somebody make these consistent?  (1) I don't care about "vscale" vs. "vertical scale" so long as they are the same in both cases; our team discussion yesterday voted for "vertical scale".  (2) Let's remove the colon after "chebfun2 object".  (3) Both vscales should be displayed in the same numerical format.

**Comment by asgeirbirkis** [comment]
Closed by #1658.
