### ISSUE TITLE
Remove "SEPARABLEAPPROX" from Chebfun2 help texts

### ISSUE THREAD

**Issue by trefethen** [chebfun/chebfun#1647]
Unfortunately we've discovered that a number of Chebfun2 help texts now point the user to SEPARABLEAPPROX (see below for examples).  This is inappropriate as there has never been any agreement to replace Chebfun2 at the user level by separableApprox.  separableApprox was introduced as a class, not a user command.  

I am not sure what the right solution is, but I am afraid this has to be sorted out before we can release V5.3.  In the current state, much of the Chebfun2 documentation is no longer correct.  Perhaps @gradywright, @ajt60gaibb, and @aaustin141 can work out a solution?
```
>> help chebfun2/abs
 abs Absolute value of a SEPARABLEAPPROX.
    abs(F) returns the absolute value of a SEPARABLEAPPROX. This function does not work
    if the function passes through or becomes numerically close to zero.

Help for chebfun2/abs is inherited from superclass separableApprox

>> help chebfun2/sin
 sin   Sine of a CHEBFUN2.

Help for chebfun2/sin is inherited from superclass separableApprox

>> help chebfun2/contour
 contour  contour plot of a SEPARABLEAPPROX.
    ...
```

**Comment by aaustin141** [comment]
Here are the two options on the table at the moment:
 - Rewrite the help text in the `separableApprox` to refer to `chebun2

**Comment by aaustin141** [comment]
Here are the two options on the table at the moment:
 - Rewrite the documentation for `separableApprox` to refer to `chebfun2` instead.  This will not work once spherefun and diskfun come along.
 - Add the factored-out methods back to `chebfun2` and have their bodies be empty except for the help text.  This duplicates documentation, which is bad, but we can live with it.  A more annoying problem is that it doesn't quite work this way:  the method bodies can't be empty.  We have to manually invoke the `separableApprox` superclass method in each case.  While it's reasonable to expect to have to do this, it does mean that we will incur additional overhead for each `chebfun2` method call, and it seems both strange and undesirable to me to take a hit (however small) on performance for reasons related to documentation.

I think this is something about which we may want to write to MathWorks to see if there's anything that can be done.

**Comment by trefethen** [comment]
I am happy to defer to the views of @aaustin141, @gradywright, and @ajt60gaibb, but let me express my immediate thought.  That is that on the face of it, option (b) seems the only really sensible one, given that `spherefun` is going to be with us any day now; but that we need *some* solution before V5.3 can be released, so that if (b) is a big effort to implement and (a) is much easier as a temporary stop-gap, I could live with us doing (a) in V5.3 temporarily and moving over to (b) not long thereafter as `spherefun` arrives.

**Comment by ajt60gaibb** [comment]
Can I add a possibility?   Can we overload the `help` command in the `chebfun2` class so that it grabs the `separableApprox` help text and replaces SEPARABLEAPPROX by CHEBFUN2.   `spherefun` and `diskfun` would do the same.

**Comment by nickhale** [comment]
No. 

Although it's possible to override the `help` method by placing one higher in the path (I just tried this) it's not possible to the subsequently call the built-in `help`:
```
>> builtin('help')
Error using builtin
Cannot find builtin function 'help' 
```

It doesn't make sense to talk about 'overloading' the `help` method either, as it always takes a string input.

**Comment by aaustin141** [comment]
@ajt60gaibb:  We considered something like that in the meeting, but remember that people don't type, e.g., `help(chebfun2())`.  They type `help chebfun2`, which is the same as `help('chebfun2')`.  That is, `help` is called with a string argument instead of a `chebfun2` object, so we can't overload it.

**Comment by ajt60gaibb** [comment]
Darn.

**Comment by aaustin141** [comment]
@nickhale:  `help` isn't actually a built-in:  you can `edit help` and see what it does internally.  (If you trace through things, you'll find that it calls the undocumented built-in `helpfunc`.)  I did this yesterday to see if there was anything from it that we could use to construct a solution, but I didn't come up with anything.

We _could_ in principle create our own `help` by copying the built-in `help`, adjusting it a bit, and placing it higher up on the path like you suggest, but in general, I am extremely strongly against distributing code that shadows functions that from core MATLAB, as that's not a very polite thing to do.

**Comment by aaustin141** [comment]
OK.  I've (or, rather, `sed` has) done the bulk of the work for implementing the second option described above.  See the newly-pushed `fix-chebfun2-docs` branch.  There are only 6 files that require individual attention, and they look to me like they were things that should have been moved from `chebfun2` into `separableApprox` a while back but weren't.  On the assumption that there was a reason for this, I haven't touched them.  The files are:
 - `@chebfun2/diffx.m`
 - `@chebfun2/diffy.m`
 - `@chebfun2/fred.m`
 - `@chebfun2/volt.m`
 - `@chebfun2/chebpolyplot.m`
 - `@chebfun2/chebpolyplot2.m`

@ajt60gaibb / @gradywright:  can one of you two take a look of these and do something about them?

**Comment by trefethen** [comment]
Thank you @aaustin141!

**Comment by ajt60gaibb** [comment]
Thanks @aaustin141. Yes, we did not move these commands from CHEBFUN2 because we were unsure of the right algorithm or appropriate name for SEPARATEAPPROX. 

I vote for leaving them at the CHEBFUN2 level for now.

**Comment by ajt60gaibb** [comment]
I have updated the help text for those six commands. Thanks, @aaustin141.

**Comment by gradywright** [comment]
I also vote for leaving them at the CHEBFUN2 level for now.  There is some discussion about these methods in #1471 and why we did not want to promote them to the `separableApprox` level.
