### ISSUE TITLE
tolerances for ODE IVP and BVP solvers

### ISSUE THREAD

**Issue by trefethen** [chebfun/chebfun#1649]
I would like to rationalize tolerances for our ODE IVP and BVP solvers in two respects during the next couple of weeks, because of the combination of the V5.3 release and the depature from Oxford in a month of @asgeirbirkis.  Along with him and myself, @jaurentz is also involved in this discussion.  Here are the two respects:

_1.  Making everything scale-invariant._  A principle of Chebfun is that computations are scale-invariant.  An exception (as we've only just recently realized) is currently ODE IVP solvers, which are scale-dependent since they use an `absTol` as well as a `relTol`.  One might think that one could simply set `absTol=0` to make things scale-invariant, but intriguingly, Matlab does not permit this.  We have received some comments from ODE suite authors Shampine and Reichelt about this, but my instinct remains that Chebfun can aim for true scale-invariance.  We may find that we can do well enough by setting `absTol = realmin`, which would make us scale-invariant so long as solutions are bigger than about 1e-280.  Or @asgeirbirkis may propose a more fundamental solution involving inspection of the data that drive an ODE IVP.  

_2. Unifying IVP and BVP tolerances._  Currently our BVPs are solved by spectral discretizations by default with `tol=1e-10` in the call the `standardChop` (tighter by a factor of 200 in computing Newton corrections), whereas our IVPs use slightly different tolerances (further complicated by the presence of `absTol` as well as `relTol`).  I believe IVP and BVP default tolerances should be identical unless a strong reason is found why they should be non-identical; I am not aware that any of us have identified such a reason.  (Chebfunners will know that I feel stronglyabout the general principle that analogous matters A and B in Chebfun should always be handled the same way, except where we identify a compelling reason to make them different.) 

I propose then that we begin by experimenting with `absTol = realmin` and the relative tolerances of IVP solutions made identical to those of BVP solutions; and that further, we explore a bit whether `1e-10` is really the right level or it should be a little smaller.  @jaurentz has begun such expperiments.

**Comment by trefethen** [comment]
@jaurentz and I have been discussing this further.  We now realize that the `realmin` idea isn't as appealing as we thought because Chebfun IVP solutions will somehow need to scale relative to a *global* size of the function, not a local one; specifying `absTol=realmin` in Matlab `ode113` amounts to the latter, and is thus inappropriate.

So: we need to have a chat with @asgeirbirkis!

**Comment by asgeirbirkis** [comment]
One complication is certainly that we don't get a full idea of the global scale of the problem until we reach the final time -- take a problem such as y'=y, y(0) = 1 on [0, 1] and anything happening close to the left endpoint will not have knowledge about what is about to happen closer to the right endpoint (obviously, more extreme examples could be constructed easily).

One idea might be to start solving the problem with a loose `relTol` and `absTol=realmin` to get a rough idea of the scale of the solution, staying only in the discrete setting. This would then give an idea of the _global_ scale of the solution, allowing us to specify a meaningful `absTol` to solve the problem for the second time and actually construct a `chebfun` to be returned.
