### ISSUE TITLE
Incorrect nullity of a linear operator when using NULL()

### ISSUE THREAD

**Issue by nickhale** [chebfun/chebfun#1653]
The following should have nullity 2, but only a single chebfun is returned:
```
>> L = chebop(@(r,u) (r-0.7).*diff(u, 2)-diff(u)-3*u,[1, 10]);
>> null(L)
u =
   chebfun column (1 smooth piece)
       interval       length     endpoint values  
[       1,      10]       32  -5.8e-06     -1.2 
vscale = 1.175962e+00.
```

The problem is that the chosen dimension isn't large enough to pick up the second null vector, and the first null vector satisfies the happiness check at this dimension.

A simple fix is to lower the tolerance for a 'zero' singular value:
```
>> L = chebop(@(r,u) (r-0.7).*diff(u, 2)-diff(u)-3*u,[1, 10]);
>> pref = cheboppref();
>> pref.errTol = 1e-9;
>> u = null(L, pref)
u =
   chebfun column1 (1 smooth piece)
       interval       length     endpoint values  
[       1,      10]       64       1.7  -0.0032 
vscale = 1.666859e+00.
   chebfun column2 (1 smooth piece)
       interval       length     endpoint values  
[       1,      10]       64    0.0074     -1.2 
vscale = 1.175987e+00.
```
but perhaps it might be better to determine what the nullity **should** be by inspecting the differential order and the number of supplied boundary conditions or to allow a requested/target number of singular values, in a similar way to `eigs()`.

(Thanks to James Mathews @ Cambridge Centre for Analysis for bringing this to my attention.)

**Comment by jaurentz** [comment]
Matlab's `null` command is based on the SVD. Just like we only support `eigs` and not `eig` for linear operators, I believe we should only support `svds` and not any command that depends on `svd`. Once we had `svds` in place we could simply remove the `null` command.

**Comment by nickhale** [comment]
I disagree with this for three reasons:
 * There's no reason why one couldn't have a `null()` algorithm based on `svds()` rather than `svd()`. 
 * The continuous analogue of `null()` is quite clearly defined.
 * In the continuous case it's actually a lot easier to compute the null-space than it is to try and compute an SVD (or partial SVD by `svds()`). In particular, in the past we only really had success with computing the SVD of compact operators (If memory serves, the left-singular functions tend to be very noisy for differential operators). This might change if we can work with adjoints, but I don't know where that stands at the moment.

**Comment by nickhale** [comment]
As a partial fix to this, I've pushed a branch `fix-null`. On this branch you can pass an additional argument, i.e., the requested number of null vectors, the `null()`. Doing this gives
```
>> L = chebop(@(r,u) (r-0.7).*diff(u, 2)-diff(u)-3*u,[1, 10]);
null(L)
ans =
   chebfun column (1 smooth piece)
       interval       length     endpoint values  
[       1,      10]       32  -5.8e-06     -1.2 
vertical scale = 1.2 
>> null(L,2)
ans =
   chebfun column1 (1 smooth piece)
       interval       length     endpoint values  
[       1,      10]       63      -1.7   0.0032 
vertical scale = 1.7 
   chebfun column2 (1 smooth piece)
       interval       length     endpoint values  
[       1,      10]       63   -0.0072      1.2 
vertical scale = 1.2 
```

This isn't ready for a PR yet. I just propose it as a proof off concept.
