### ISSUE TITLE
Parsing of ODE systems broken by unary operators

### ISSUE THREAD

**Issue by tobydriscoll** [chebfun/chebfun#1663]
```
 pp = chebop( @(t,x,y) [diff(x) + x; diff(y) + y],[0 30]);
 pp.lbc = @(x,y) [x-1;y-0.9];
 plot(pp\0)
```

All is well. But:

```
pp = chebop( @(t,x,y) [diff(x) +x; diff(y) + y],[0 30]);
pp.lbc = @(x,y) [x-1;y-0.9];
plot(pp\0)

Dimensions of matrices being concatenated are not consistent.

Error in @(t,x,y)[diff(x),+x;diff(y)+y]

Error in treeVar.toFirstOrder (line 58)
    fevalResult = funIn(t, args{:});

Error in chebop/solveivp (line 121)
        treeVar.toFirstOrder(N.op, rhs, N.domain);

Error in  \  (line 49)
    [varargout{1:nargout}] = solveivp(N, rhs, pref, varargin{:});
```

**Comment by asgeirbirkis** [comment]
Thanks @tobydriscoll , will investigate and fix!

**Comment by asgeirbirkis** [comment]
@tobydriscoll I don't think this is a `treeVar` issue, but just standard unsupported Matlab syntax:
```
>> [1 + 2; 3]
ans =
     3
     3
>> [1 +2; 3]
Dimensions of matrices being concatenated are not
consistent. 
```

**Comment by nickhale** [comment]
I concur with Asgeir. (One of my students just ran in to this very same Matlab issue in her numerical methods computer test.)

**Comment by jrus** [comment]
If you want to be able to distinguish these without looking at the whitespace, you can always wrap any expressions in parenthesis, and separate array elements with commas. e.g.
```matlab
pp = chebop( @(t,x,y) [(diff(x) +x); diff(y) + y],[0 30]);
```

**Comment by asgeirbirkis** [comment]
@tobydriscoll Are you OK with this being closed?

**Comment by asgeirbirkis** [comment]
@tobydriscoll I noticed this issue when working on #2191 as it relates to unary operators, however, I think they're unrelated, and this is more of a fundamental Matlab issue. Should we close this ticket?
