### ISSUE TITLE
need a global simplifying tolerance option for quasimatrices

### ISSUE THREAD

**Issue by trefethen** [chebfun/chebfun#1666]
@bhashemi and @jaurentz and I have realized that if `simplify` is to work properly in Chebfun2 and Chebfun3, it has to be able to simplify all the columns of a quasimatrix relative to the scale of the largest, not individually.  Here is an illustration of the problem.  Suppose you make any old chebfun2, like this one:
```matlab
>> f = chebfun2(@(x,y) x.*sin(x.*y)./(3-x.*y.^2));
>> plotcoeffs(f)
```
Below is the first of the two plots that results from this `plotcoeffs` command.  What you see is that the "right" simplification has not taken place.  (Essentially the same picture is produced even in the new branch by @bhashemi that calls `simplify`: see #1249 and #1644.)  

A possible syntax -- any ideas for a better one? -- would be:
```matlab
simplify(A,'globaltol')
```
What this would do is simplify all the columns of the quasimatrix A using the same effective tolerance (Chebfun `eps` in this illustration since we haven't overridden it) relative to the biggest column of A.

@jaurentz has kindly agreed to do this.

![globalfig](https://cloud.githubusercontent.com/assets/3601488/11277188/5e677b5c-8edd-11e5-9e31-d2b46a3b75c7.png)

**Comment by aaustin141** [comment]
Closed in #1668.
