### ISSUE TITLE
Tighter tolerance causing issues in linop.null().  (Example ode-eig/NullSpace crashes.)

### ISSUE THREAD

**Issue by aaustin141** [chebfun/chebfun#1687]
The example `ode-eig/NullSpace` crashes on current development with the following output:
```
Warning: Boundary conditions are not supported in FEVAL(N, DIM). 
> In chebop/feval (line 64)
  In chebop/subsref (line 46)
  In NullSpace (line 72) 
Error using opDiscretization/matrix (line 28)
Must specify one dimension value for each subinterval.
Error in chebmatrix/matrix (line 52)
[varargout{1:nargout}] = matrix(d);
Error in chebop/feval (line 83)
    A = matrix(L, n, pref); % has n rows but maybe more columns
Error in chebop/subsref (line 46)
        varargout{1} = feval(N, idx{:});
Error in NullSpace (line 72)
norm(L(v)) 
```
Bisection reveals that the issue was introduced in the recently-merged e3e32cf0.  Previously, the tolerance that would get passed to `getNullVectors()` in [this line](https://github.com/chebfun/chebfun/blob/e3e32cf01361f04b67875bc7dda80d4a42fe519c/%40linop/null.m#L72) in `@linop/null.m` was `1e-10`.  Now, it's `5e-13`.  This causes the `nullity` output of this function to be zero when we run [this line](https://github.com/chebfun/examples/blob/c3d6f0cc218354fd310258b38d60f9af2b7d4ebf/ode-eig/NullSpace.m#L69) of the example.  The computed `v` is then empty, and that causes issues when we go to compute `L(v)` later [here](https://github.com/chebfun/examples/blob/c3d6f0cc218354fd310258b38d60f9af2b7d4ebf/ode-eig/NullSpace.m#L72).

There also seem to be differences in the nullities found during some of the other computations earlier in the example, so we're probably getting wrong answers for those at the moment, just not crashes.

**Comment by nickhale** [comment]
See also: #1653

**Comment by asgeirbirkis** [comment]
A quick fix would be to multiply the new tolerance by a factor of 200 to get back to the previous state of passing a tolerance of `1e-10`, essentially reverting the changes made by @jaurentz in e3e32cf.

However, given #1653, would it be more sensible to try to fix the `linop/null` code like @nickhale suggests?

If we just want the example to stop crashing for now, the first fix would certainly be the quickest to implement.
