### ISSUE TITLE
Can we call simplify on components of [u,v] = N\f?

### ISSUE THREAD

**Issue by trefethen** [chebfun/chebfun#1689]
Chebop solves ODEs in quasimatrix mode, so that if you have several components of the solution of a problem, they all come out with the same length:
```
L = chebop(@(t,u,v) [diff(u,2)+u; diff(v,2)+100*v],[0,10]);
L.lbc = @(u,v) [u-1; diff(u); v-1; diff(v)];
[u,v] = L\0;
length(u)
ans =   86
length(v)
ans =   86
```
Often the various components may have very different natural lengths, however:
```
length(simplify(u))
ans =  26
length(simplify(v))
ans =  86
```
Could we change things so that when users specify outputs componentwise in this `[u,v] = ...` fashion, `simplify` is applied to each output before it is returned?  (In principle I guess I'd suggest the same for the outputs of `deal`, though `deal` is hardly needed by users any more now that we have `[u,v] = ...`.)  Perhaps @asgeirbirkis would be willing to implement this if @jaurentz or others have no objection.

**Comment by asgeirbirkis** [comment]
Yes, this would be a pretty straightforward fix, although should we be concerned this'd mean that the outputs from

```
[u,v] = L\0;
```
and
```
uv = L\0;
[u, v] = deal(u, v);
```
would be different?

**Comment by nickhale** [comment]
What if `deal()` also simplifies?

**Comment by asgeirbirkis** [comment]
![image](https://cloud.githubusercontent.com/assets/3543429/11745116/9912388c-a00d-11e5-873b-e0c5239f46af.png)

Yes, as long as it's documented, and we could have a 'nosimplify' option! I'll quickly implement this.
