### ISSUE TITLE
Allow 'scaled jumps' when solving BVPs. 

### ISSUE THREAD

**Issue by nickhale** [chebfun/chebfun#1694]
We can enforce jumps in the following way:
```
A = chebop(@(x,u) diff(u,2) - u, [-1,1]);
A.lbc = 1;
A.rbc = 0;
A.bc = @(x,u) [jump(u,0,1) ;  % jump of 1 in solution at zero
               jump(diff(u),0,1)];
u = A\0
plot(u)
```

But what if we wanted to enforce `u(0,'left') + 10*u(0,'right') = 1`? Currently this doesn't seem to be supported by `adchebfun/feval()` or `adchebfun/jump()`.

**Comment by trefethen** [comment]
This strikes me as a rather arcane thing to add to Chebfun.  On the principle that every additional feature makes a code ever so slightly more difficulty to document and maintain, maybe we should let this idea lie unless it seems there's really a need for it?
