### ISSUE TITLE
CHEBAMTRIX vs CHEBFUN2V

### ISSUE THREAD

**Issue by Hadrien-Montanelli** [chebfun/chebfun#1699]
Vertical concatenation with `chebfun` objects creates `chebmatrix` objects

```
 g = chebfun('x'); [g;g]

ans =
   2 x 1 chebmatrix of block types:
    'chebfun'    
    'chebfun'    
```

When `f` is a `chebfun2`, the vertical concatenation of `f` and `f` with `;` creates a `chebfun2v` object

```
f = chebfun2(@(x,y) cos(x.*y)); [f;f]

ans =
   chebfun2v object (Column vector) containing:

   chebfun2 object (1 smooth surface)
       domain                 rank       corner values
[  -1,   1] x [  -1,   1]        7     [0.54 0.54 0.54 0.54]
vertical scale =   1 

   chebfun2 object (1 smooth surface)
       domain                 rank       corner values
[  -1,   1] x [  -1,   1]        7     [0.54 0.54 0.54 0.54]
vertical scale =   1 
```

The triple concatenation `[f;f;f]` also works:

```
[f;f;f]

ans =
   chebfun2v object (Column vector) containing:

   chebfun2 object (1 smooth surface)
       domain                 rank       corner values
[  -1,   1] x [  -1,   1]        7     [0.54 0.54 0.54 0.54]
vertical scale =   1 

   chebfun2 object (1 smooth surface)
       domain                 rank       corner values
[  -1,   1] x [  -1,   1]        7     [0.54 0.54 0.54 0.54]
vertical scale =   1 

   chebfun2 object (1 smooth surface)
       domain                 rank       corner values
[  -1,   1] x [  -1,   1]        7     [0.54 0.54 0.54 0.54]
vertical scale =   1 
```

`chebfun2` objects, since they represent vector fields with two or three components, don't support more than three components:

```
[f;f;f;f]

Error using chebfun2v (line 110)
More than three components is not supported.
Error in separableApprox/vertcat (line 34)
        F = chebfun2v( varargin{:} );
Error in chebfun2/vertcat (line 16)
[varargout{1:nargout}] = vertcat@separableApprox(varargin{:}); 
```

`chebfun2v` objects can also be created via

```
 chebfun2v(f,f)

ans =
   chebfun2v object (Column vector) containing:

   chebfun2 object (1 smooth surface)
       domain                 rank       corner values
[  -1,   1] x [  -1,   1]        7     [0.54 0.54 0.54 0.54]
vertical scale =   1 

   chebfun2 object (1 smooth surface)
       domain                 rank       corner values
[  -1,   1] x [  -1,   1]        7     [0.54 0.54 0.54 0.54]
vertical scale =   1 
```

To create a `chebmatrix` with `chebfun2` objects, one can type:

```
F = chebmatrix(f); F(2) = f

F =
   1 x 2 chebmatrix of block types:
    'chebfun2'    'chebfun2'  
```

Here is my question: should vertical concatenation with `chebfun2` objects create a `chebmatrix`? One could still create `chebfun2v` objects with `chebfun2v(.,.)`. This question arises in the solution of time-dependent PDEs (branch `feature-spinop`), where one need to give an initial guess, and everything would be clearer and simpler if `;` could create a `chebmatrix` for `chebfun`, `chebfun2`, and `chebfun3` objects.

**Comment by ajt60gaibb** [comment]
I am not against this, though I have not thought about the implications.  When we were designing Chebfun2, chebmatrices were not around. If the syntax does not feel right now, then it can be changed. 

The reason we have `chebfun2v` objects instead of vector-valued `chebfun2` objects is because the set of operations that one is typically interested in (vector calculus and surfaces) are very different than scalar-valued functions.  I would hope that `chebfun2v` objects remain as a separate class.

**Comment by trefethen** [comment]
I'm afraid I'm uncomfortable with chebmatrices -- they exist, but they have never become part of our standard operation.  Though you would think this kind of thing would be rather at the heart of Chebfun, chebmatrices are currently only mentioned once in the Chebfun guide and in two of the Examples.  It's a safe bet that hardly anybody on earth is very clear on the distinctions of concept and syntax between array-valued chebfuns, arrays of chebfuns, and chebmatrices.

Accordingly I would urge that we not modify or extend chebmatrices much without some pretty broad discussions.  Hopefully the work being initiated by @jaurentz on block operators (picking up on previous work by @hrothgar) will probably play into this.

**Comment by Hadrien-Montanelli** [comment]
Well, `spin` does uses `chebmatrix` objects for systems of equations, as we as `\` for ODEs. In fact, the whole `solvebvp` solver relies on `chebmatrix` objects, so they really are part of the software. The question here is whether `;` should create `chebfun2v` or `chebmatrix` objects.

**Comment by ajt60gaibb** [comment]
Any decision made on this?
