### ISSUE TITLE
`plotcoeffs` for Chebfun2

### ISSUE THREAD

**Issue by trefethen** [chebfun/chebfun#1706]
@hashemi has been developing Chebfun3 (which should reach GitHub in a few weeks), and one thing we find is that's is very nice for `plotcoeffs(f)` of a chebfun3 to put all three plots in a single figure, not 3 separate figures.  Similarly it would be very nice for `plotcoeffs(f)` of a chebfun2 to put both plots in a single figure, not 2 separate figures.  I wonder if @ajt60gaibb or @hashemi could make this happen?

**Comment by ajt60gaibb** [comment]
I assume you mean with subplots. If so, I have done this change in 
https://github.com/chebfun/chebfun/tree/feature-plotcoeffs-subplots

@bhashemi, is @separableApprox/plotcoeffs.m analogous to your chebfun3 version in `feature-plotcoeffs-subplots` now?

**Comment by bhashemi** [comment]
Yes. Shall we make a pull request for this?

**Comment by ajt60gaibb** [comment]
Done.

**Comment by bhashemi** [comment]
This issue can be closed since the pull request #1708 is merged.

**Comment by jrus** [comment]
One note: I’m pretty happy having these in separate plots when looking at a laptop screen where I want to blow each plot up and examine the details, whereas plotting them in a single view is definitely preferable on a larger desktop display.

* * *

On the subject of chebfun2 plots, is there an easy way to set the color scheme of the various lines, without pulling out the rows and columns manually and re-plotting myself? My Matlab plotting knowledge is pretty slim, so all I could figure out to do is change all the lines to the same color.

**Comment by ajt60gaibb** [comment]
There is no way to plot the various lines in user prescribed colors.  It either users MATLAB's default different colors or one single color given by the user.

**Comment by jrus** [comment]
Oh well. I’ve taken to saving the data and making ad-hoc plots using Javascript in a browser when I need to change the color scheme.
