### ISSUE TITLE
A Lebesgue command for trigonometric interpolation

### ISSUE THREAD

**Issue by ajt60gaibb** [chebfun/chebfun#1717]
A `lebesgue` command for trigonometric interpolation would be very useful.  The syntax could even be 
```
[L, c] = lebesgue(linspace(-pi,pi,n), 'trig')
```
as defined in https://en.wikipedia.org/wiki/Trigonometric_interpolation.

**Comment by trefethen** [comment]
I agree!  @aaustin141...?

Of course the output will be a chebfun, not a trigfun.

**Comment by aaustin141** [comment]
I've got this partially implemented now.  I'll try to finish it off tonight and issue a pull request for it tomorrow.

**Comment by trefethen** [comment]
As discussed today with @aaustin141, my view is that the trig Lebesgue command only needs to work for an odd number of points; it could throw an error message of the number of points is even.  Even-point trig interpolants make sense maybe for equispaced points, but for nonequispaced points they make less sense.  See comment #3 in Section 1 of the Wright, et al. trig paper, <https://people.maths.ox.ac.uk/trefethen/trigpaper.pdf>.
