### ISSUE TITLE
Distinction between infinity norm and maximum norm in chebfun2

### ISSUE THREAD

**Issue by bhashemi** [chebfun/chebfun#1720]
We know that, as continuous analogues of matrix norms, the 1-norm and the infinity-norm of a `chebfun2` object $f$, each correspond to integration in one of the two dimensions. But, this is not the way these are implemented in `separableApprox/norm`. In particular, currently the infinity norm is mixed with the maximum (Chebyshev) norm, as saying
`
norm(f,'inf')
`
runs the same algorithm as saying
`
norm(f,'max')
`
I suggest that we do the following:
1- Correct the code for the infinity norm.
2- Add the capability of computing the 1-norm to chebfun2.

**Comment by trefethen** [comment]
I'm not sure I agree.  A chebfun2 can be interpreted as an operator, but in Chebfun, I don't think that's its primary interpretation: namely, a function of two variables.

I certainly agree that it would be good to have the operator 1- and infty-norms available; I'm just not sure whether `norm(f,'inf')` is the right syntax.  Should we have some other syntax?  The choices `norm(f,'operatorinf')` and `norm(f,'operator1')` strike me as not so appealing.

**Comment by jrus** [comment]
Trivial side note: From the docstring at the top of `separableApprox/norm.m`
```matlab
%    NORM(F, inf) = global maximum in absolute value.
%    NORM(F, max) = global maximum in absolute value.
%    NORM(F, min) = NOT IMPLEMENTED
```
Presumably the second argument in all of these should be a string, like `NORM(F, 'max')`

**Comment by ajt60gaibb** [comment]
Help text fixed in #1723. 

I think that `norm(f,'inf')` and  `norm(f,'max')` should remain as the absolute maximum value of `f`. 

Before the syntax, what is the algorithm for the operator inf- and 1-norm?

**Comment by bhashemi** [comment]
How about the following two functions which are a trivial modification of an algorithm suggested by Nick?
``function norm1 = norm1(f) ``
``% Operator 1-norm of a chebfun2``
``% Wanted: maximum column integral of abs(f)``
``dom = f.domain(3:4);``
``slices = chebfun(@(x) sum(abs(f(x,:)))',dom,'splitting','on');``
``norm1 = max(slices);``
``end``
and
``function norminf = norminf(f) ``
``% Operator Inf-norm of a chebfun2``
``% Wanted: maximum row integral of abs(f)``
``dom = f.domain(1:2);``
``slices = chebfun(@(y) sum(abs(f(:,y))),dom,'splitting','on');``
``norminf = max(slices);``
``end``

**Comment by ajt60gaibb** [comment]
Is this fast enough for whatever you need it for?

**Comment by bhashemi** [comment]
@ajt60gaibb , I don't need it for a specific application, at least right now. Even though it could be slow for some functions, but I think still it's cool to have these two capabilities in Chebfun.

**Comment by ajt60gaibb** [comment]
Sure. I agree.
