### ISSUE TITLE
abstractQR is slow, any ideas?

### ISSUE THREAD

**Issue by ajt60gaibb** [chebfun/chebfun#1732]
We are finding that the `abstractQR` command is disappointingly slow. For example, compare

```
n = 7; 
T = chebpoly(0:n); 
tic, [Q1, R1] = qr( T ); toc 
Elapsed time is 0.009698 seconds.
```
to
```
P = legpoly(0:n)*diag(sqrt((0:n)+.5)); 
innerProduct = @(u,v) sum(conj(u).*v); 
tic, [Q2, R2] = abstractQR(T, P, innerProduct); toc
Elapsed time is 4.858631 seconds.
```

That is a factor of `500`!  If I select `n=20`, then `abstractQR` takes `44` seconds, while `QR` takes under a second. When I profile the code, the most significant cost is in `isempty` commands. 
The most expensive lines in `abstractQR` are lines `28` and `36` that do arithmetic operations on quasimatrices (as opposed to calculating inner-products).

**Comment by nickhale** [comment]
I'm not sure this is a problem with `abstractQR()` per se, but rather that this is an obvious place where we do repeated arithmetic operations on quasimatrices - which is actually where the problem lies.

**Comment by aaustin141** [comment]
Are you running the latest version of MATLAB (R2015b)?  MathWorks took a huge scoop out of overhead in the latest version.  On my machine, I get that `abstractQR` takes about 5.4 seconds for `n = 20`.  Granted, it's still about 1000x slower than plain `qr` (which I get takes about 0.003 seconds), but it's a big improvement over the 44 seconds you're reporting (and my machine is not exactly new).

> When I profile the code, the most significant cost is in `isempty` commands.

If I replace the body of every `isempty()` function with a statement that just always returns `false`, I can improve my `abstractQR` timing to about 4.7 seconds (0.7 s, about a 13% improvement).  Optimistically, I could shave off another few tenths of a second by getting rid of empty funs entirely (see #1305, #1733), but that's not going to lead to the kind of significant speedup I think you're hoping for here.

**Comment by ajt60gaibb** [comment]
I was running MATLAB R2014b. I believe my 2011 laptop is just 10 times slower than yours.   

Would it be better to have an `abstractQR` at the chebtech level so it can be computed via a discrete QR?

**Comment by aaustin141** [comment]
R2014b or R2015b?  It's R2015b that has all the overhead-reducing improvements.  (As a data point:  just switching to R2015b nearly halved the time it took my machine to finish a full run of the tests.)

**Comment by ajt60gaibb** [comment]
R2014b.  Spherefun and diskfun needs `abstractQR` to work for array-valued functions for `n<=200` columns. I think we may have to explicitly convert it to a discrete QR, just like `chebtech/qr`.

**Comment by aaustin141** [comment]
A related issue:  I just realized that QR for `trigtech`-based chebfuns is considerably slower than it is for `chebtech`-based ones.  Compare:
```
>> K = 75;
>> T = chebpoly(0:K);
>> tic(); [Q, R] = qr(T); toc()
Elapsed time is 0.007191 seconds.
>> tic(); [Q, R] = qr(T); toc()
Elapsed time is 0.007239 seconds.
>> tic(); [Q, R] = qr(T); toc()
Elapsed time is 0.007183 seconds.
```
with
```
>> K = 75;
>> P = trigpoly(0:K);
>> tic(); [Q, R] = qr(P); toc()
Elapsed time is 0.345735 seconds.
>> tic(); [Q, R] = qr(P); toc()
Elapsed time is 0.342935 seconds.
>> tic(); [Q, R] = qr(P); toc()
Elapsed time is 0.350221 seconds.
```
It seems `trigtech` also needs a discrete QR implementation.  (Currently, it uses the continuous Householder QR via `abstractQR()`.)

**Comment by ajt60gaibb** [comment]
OK. I ended up replicating the `abstractQR` command for the specific cases of the disk and sphere inner products. Once it was a specific inner product, a weighted discrete QR can be used.  Only a factor `200` speed up in some cases...
