### ISSUE TITLE
Forbid empty CHEBFUN (CHEBTECH, TRIGTECH, etc.) objects?

### ISSUE THREAD

**Issue by nickhale** [chebfun/chebfun#1733]
If you've ever profiled some Chebfun code, you've undoubtedly noticed that a painful amount of time is spent in the `isempty()` methods. (See, for example, #1732.)

I propose that we explicitly forbid the construction of empty objects within Chebfun (perhaps with the exception of `chebop`), which should help to alleviate this problem.

**Comment by aaustin141** [comment]
This is a duplicate of #1305.

**Comment by ajt60gaibb** [comment]
How about allow empty objects that interface with the user, but not empty chebtechs, trigtechs, etc.?

**Comment by aaustin141** [comment]
Closed as a duplicate of #1305.
