### ISSUE TITLE
Wrong line colors from plot() under "hold on".

### ISSUE THREAD

**Issue by aaustin141** [chebfun/chebfun#1741]
Consider the following plot of `x`, `x^2`, and `x^3`, created using plain MATLAB:
```matlab
x = linspace(-1, 1, 32.');

figure(1);
clf();
hold on;
plot(x, x);
plot(x, x.^2);
plot(x, x.^3);
hold off;
```
![builtin](https://cloud.githubusercontent.com/assets/3380006/12745785/0a326baa-c993-11e5-9016-df61ccd5e602.png)

I would expect the Chebfun plot generated by the following code to look identical, but it's not.  The color of the line for `x^3` is wrong:
```matlab
x = chebfun(@(x) x);

figure(2);
clf();
hold on;
plot(x)
plot(x.^2)
plot(x.^3)
hold off;
```
![chebfun](https://cloud.githubusercontent.com/assets/3380006/12745786/0a3c90b2-c993-11e5-99a0-90475516565a.png)

I'm running this on MATLAB R2015b.  Note that if I create the Chebfun plot using a quasimatrix via `plot([x x.^2 x.^3])`, the colors come out fine.

**Comment by nickhale** [comment]
`plot(x, '-', x.^2', '-', x.^3, '-')` is also fine.
