### ISSUE TITLE
Calling constructor on a trigfun

### ISSUE THREAD

**Issue by gradywright** [chebfun/chebfun#1745]
Suppose we do
```
f = chebfun(@(x) cos(pi*x),'trig')

f =

   chebfun column (1 smooth piece)
       interval       length     endpoint values trig
[      -1,       1]        3        -1       -1 
vertical scale =   1 
```
Then for some reason we do
```
g = chebfun(f)

g =

   chebfun column (1 smooth piece)
       interval       length     endpoint values  
[      -1,       1]       29        -1       -1 
vertical scale =   1 
```
Now `g` is not a trigfun.  I seem to recall that the default behavior used to be to make `g` a trigfun since `f` is a trigfun, that is the constructor respects the type of the tech.  If memory serves me right @mhsnjvd made this change some time ago.

Looking through the code in a bit more detail it looks like if we call `chebfun(f)` where `f` is already a chebfun then we go through the whole construction process again.  Is this the desired behavior?

**Comment by mhsnjvd** [comment]
I recall the opposite, i.e. when you call ```chebfun(f)``` where ```f``` is a trigfun, it constructs a chebfun from scratch using the default chebtech and this was desired because it gave us an easy way to switch from trig to cheb whenever operations on a ```trigfun``` give rise to discontinuities or destroy periodicity. For example, for ```abs(f)``` where ```f``` is a ```trigfun```.

**Comment by aaustin141** [comment]
> Looking through the code in a bit more detail it looks like if we call chebfun(f) where f is already a chebfun then we go through the whole construction process again. Is this the desired behavior?

See issue #77.  Yes, this is what we want to do.  At the very least, there are several examples that make use of this functionality, and I'm pretty sure it's in ATAP as well.

**Comment by aaustin141** [comment]
Can we close this issue?

**Comment by gradywright** [comment]
Thanks for the responses @mhsnjvd and @aaustin141.  I will close the issue since this is the desired behavior.  

However, note that redoing the construction process and not respecting the tech type slows down `minandmax2@separableAppprox` in `spherefun`.  We might be able to work around this in another way.
