### ISSUE TITLE
Colors are wrong on chebop quiver() plot.

### ISSUE THREAD

**Issue by aaustin141** [chebfun/chebfun#1750]
In the world of c999cee5 and beed5a68 (and, more specifically, the latter), the colors on a chebop quiver() plot are no longer correct.  The best way to see this is just to run the ode-nonlin/ChebopQuiver example and observe the rainbow-colored output:

![quivcolors](https://cloud.githubusercontent.com/assets/3380006/12847639/a1855ae6-cc0c-11e5-84d6-82837613d952.png)

**Comment by nickhale** [comment]
@aaustin141 - to me this this seems a 'bug' in the example rather than in `quiver()` or `plot()`. (I.e., this behaviour should be expected post-2014b.)

**Comment by aaustin141** [comment]
You're completely right.  Sorry; I must have been asleep at the wheel when filing this ticket because it has nothing to do with `quiver()` at all.  The example is calling `plot()` repeatedly, and in R2014b and later, the rule is that the new calls to `plot()` pick up in the color cycle where the last one left off instead of restarting it as was done in previous versions.  The fact that the colors were coming out "right" before should have been a tip to us that we were doing something wrong with them previously!

I'll close this ticket and file a corresponding in the examples repository.
