### ISSUE TITLE
2-norm and Frobenius norm of a chebfun2

### ISSUE THREAD

**Issue by bhashemi** [chebfun/chebfun#1757]
I agree that the Frobenius norm of $f(x,y)$ is

```
sqrt(sum2(f.^2)) = sqrt( sum( svd( f ).^2 ) )
```

Also, I don't complain setting the Frobenius norm as defualt in `chebfun2/norm`. But,  I believe we should at-least allow a user to get the correct 2-norm if she/he explicitly inputs `norm(f,2)`, where by correct 2-norm I mean the largest singular value. Currently, chebfun2 considers `norm(f,2)` to be the same as `norm(f,'fro')`.

**Comment by trefethen** [comment]
I am not happy with `norm(f,2)` giving the operator 2-norm, because the basic notion of a chebfun2 is that it is a function of 2 variables, not an operator, so this syntax might cause confusion.  How about a scheme along the following lines?
```
norm(f, 'fro') - Frobenius norm

norm(f, 'operator2') - operator 2-norm    [or some other suitable string]

norm(f, 2) - error message along the following lines: "2-norm not supported -- use 'fro' or 'operator2' "

**Comment by ajt60gaibb** [comment]
I like the idea of returning an error for `norm(f, 2)` and asking the user for more information.
