### ISSUE TITLE
chebfun2v.subsref() does not recurse properly.

### ISSUE THREAD

**Issue by aaustin141** [chebfun/chebfun#1769]
Say I want to look at the `pivotValues` of the first component of a `chebfun2v`.  This does not work:
```
>> f = chebfun2(@(x, y) sin(x.*y));
>> F = [f ; f ; f];
>> F(1).pivotValues
ans =
   chebfun2 object (1 smooth surface)
       domain                 rank       corner values
[  -1,   1] x [  -1,   1]        6     [0.84 -0.84 -0.84 0.84]
vertical scale = 0.84
```
It's returned `F(1)` itself, not its `pivotValues`.  I can get around this by doing
```
>> F1 = F(1);
>> F1.pivotValues
ans =
  Columns 1 through 3
   0.841470984807897  -0.026807319671605   0.000079636405080
  Columns 4 through 6
  -0.000000269450587   0.000000000229048  -0.000000000000091
```
but this is annoying, especially if you want to look at the `pivotValues` of each component in turn.

I thought I could also do the following as a work-around, but it crashes, too:
```
>> F.components{1}.pivotValues
Undefined variable "index" or class "index".
Error in chebfun2v/subsref (line 34)
            t2 = index(2).type; 
```
This crash occurs because of a mistyped variable name on [this line](https://github.com/chebfun/chebfun/blob/85c89cd1f49ec24f9994730e0ecc20ca444612b1/%40chebfun2v/subsref.m#L34) of `chebfun2v.subsref()`.  If I fix that (change it to `t2 = ref(2).type`), it _still_ crashes:
```
>> F.components{1}.pivotValues
Struct contents reference from a non-struct array object.
Error in chebfun2v/subsref (line 42)
                varargout = {subsref(out, ref(3:end))}; 
```
The reason this crash occurs is because [these lines](https://github.com/chebfun/chebfun/blob/85c89cd1f49ec24f9994730e0ecc20ca444612b1/%40chebfun2v/subsref.m#L37-L39) incorrectly assume that the only alternative to a reference of type `'.'` is one of type `'()'`; they've forgotten about `'{}'`.

EDIT:  While we're at it, [this comment](https://github.com/chebfun/chebfun/blob/85c89cd1f49ec24f9994730e0ecc20ca444612b1/%40chebfun2v/subsref.m#L33) makes no sense.  `.^` and `.*` get dispatched to `power()` and `times()`, respectively, not `subsref()`.

**Comment by ajt60gaibb** [comment]
I started a `fix-chebfun2-subsref` branch, along with a test `chebfun2v/test_subsref`.  I got `F(1).pivotValues` working, but not `F.components{1}.pivotValues`.

**Comment by aaustin141** [comment]
Does the following patch (applied against your `fix-chebfun2-subsref` branch) not do the trick?
```diff
diff --git a/@chebfun2v/subsref.m b/@chebfun2v/subsref.m
index 3a9e0e2..9708403 100644
--- a/@chebfun2v/subsref.m
+++ b/@chebfun2v/subsref.m
@@ -27,25 +27,8 @@ indx = ref(1).subs;
 switch ( ref(1).type )
     
     case '.'
-        if ( numel( ref ) == 1 )
-            % This is a get call to get a property. 
-            varargout = { get(F, indx) };
-        else
-            %  
-            t2 = ref(2).type;
-            if ( strcmp(t2,'.') )
-                out = get(F, indx, ref(2).subs{:});
-            else
-                out = get(F, indx);
-                out = out( ref(2).subs{:} );
-            end
-            if ( numel(ref) > 2 )
-                varargout = {subsref(out, ref(3:end))};
-            else
-                varargout = { out };
-            end
-        end
-        
+        % This is a get call to get a property. 
+        varargout = { get(F, indx) };
     case '()'
         if ( length(indx) > 1 )
             x = indx{1}; 
```
I don't think that the conditional block inside the handler for `'.'`-type references is necessary.  At the very least, `else` clause is not exercised in any of the tests.  Once you've grabbed the property the caller has asked for, should you not just recurse immediately for any remaining subscript references?  I don't understand what post-processing the `else` clause

With your changes, and with that patch in place, the following code now works as expected:
```
>> f = chebfun2(@(x, y) sin(pi*x).*cos(pi*y), 'trig');
>> F = [f ; f ; f];
>> class(F(1).cols.funs{1}.onefun)
ans =
trigtech
>> class(F.components{1}.cols.funs{1}.onefun)
ans =
trigtech
```

**Comment by ajt60gaibb** [comment]
Great. That simplifies that block.  Definitely want to immediately recurse. That's why I added the last line 3 lines, which throws away the first argument of the `ref` variable and then procedures to recursively apply the remaining `subsref` call.

**Comment by ajt60gaibb** [comment]
Can this be closed now?

**Comment by aaustin141** [comment]
I thought you were still working on this?  I haven't seen a pull request yet for `fix-chebfun2-subsref`.
