### ISSUE TITLE
chebfun2 does not properly respect tech type when periodic functions are involved.

### ISSUE THREAD

**Issue by aaustin141** [chebfun/chebfun#1774]
`chebfun2` only works "properly" with periodic functions when the default preferences have been altered.  For instance, if I use `.*` to multiply two `chebfun2` objects based on `trigtech`, the result is a `chebfun2` based on `chebtech` unless the default `tech` has been set to `trigtech`.  See [this comment](https://github.com/chebfun/chebfun/pull/1772#issuecomment-186202296) and [this comment](https://github.com/chebfun/chebfun/pull/1772#issuecomment-186369086) on #1772 for specific examples.

**Comment by gradywright** [comment]
See also #1067.

**Comment by aaustin141** [comment]
Thanks @gradywright:  I had a feeling that there was already a ticket about this out there somewhere, but somehow, I didn't run across it when I was searching through the issues earlier.  I'll close this as a duplicate of that one and add a comment to that ticket instead.
