### ISSUE TITLE
Strange chopping in chebfun2 constructor

### ISSUE THREAD

**Issue by jaurentz** [chebfun/chebfun#1776]
Constructing the following `chebfun2` leads to a strange coefficient plot:
```matlab
>> f = chebfun2(@(x,y) exp(sin(pi*(x+3*y)))); plotcoeffs(f)
```
![strangecoeffs](https://cloud.githubusercontent.com/assets/7694954/13397200/cf94e478-def0-11e5-9973-31edee551661.png)
This should be no problem for `standardChop`.

**Comment by aaustin141** [comment]
Closed in #1777.
