### ISSUE TITLE
Some spherefun commands still have separableApprox help text

### ISSUE THREAD

**Issue by ajt60gaibb** [chebfun/chebfun#1786]
There are still spherefun commands for which the help text includes the word `separableApprox` instead of `spherefun`.  This is because the file has not been replicated in the `@spherefun` folder. 

A quick search suggests that the following commands are culprits: 

`abs`, `cdr`, `chol`, `exp`, `horzcat`, `imag`, `integral`, `isempty`, `isreal`, `isequal`, `iszero`, `ldivide`, `length`, `log`, `max`, `max2`, `mean`, `mean2`, `median`, `min`, `min2`, `minandmax2`, `minus`, `mldivide`, `mrdivide`, `mtimes`, `power`, `prod`, `qr`, `rank`, `rdivide`, `real`, `sin`, `sinh`, `sqrt`, `std`, `std2`, `sum`, `tan`, `tand`, `tanh`, `times`, `trace`, `uminus`, and `uplus`.

**Comment by gradywright** [comment]
Closed by #1820.
