### ISSUE TITLE
use `cummax` in `standardChop`

### ISSUE THREAD

**Issue by trefethen** [chebfun/chebfun#1793]
Folkmar Bornemann has looked at `standardChop` and noted that it computes a cumulative maximum without calling Matlab's built-in code for that, `cummax`.  @jaurentz, I am taking the liberty of assigning to you the project of fixing this.  Of course it's a small matter, but perfection is to be strived for in this bit of code I think as it is (a) at the heart of Chebfun and (b) to appear in a journal paper.

Thanks.

**Comment by aaustin141** [comment]
Closed in #1794.
