### ISSUE TITLE
spherefun/Poisson and spherefun/Helmholtz should use trigspec 

### ISSUE THREAD

**Issue by ajt60gaibb** [chebfun/chebfun#1798]
Currently `spherefun/Poisson` and `spherefun/Helmholtz` make their own `trigspec` operators.  This is unnecessary. 

They should use `trigspec` directly. 

One problem is that `trigspec.diffmat(n,1)` has a zero `(1,1)` entry if `n` is even.  In `spherefun/Poisson` and `spherefun/Helmholtz` we would prefer for this not to be the case. See also #1799.

**Comment by ajt60gaibb** [comment]
@Hadrien-Montanelli, are you planning to add a flag into `trigspec.diffmat` to make this possible?

**Comment by Hadrien-Montanelli** [comment]
Sure @ajt60gaibb, thanks for the reminder, I'll do it this week.

**Comment by Hadrien-Montanelli** [comment]
@ajt60gaibb I've just issued a pull request.

**Comment by gradywright** [comment]
Can this issue be closed @ajt60gaibb and @Hadrien-Montanelli?

**Comment by ajt60gaibb** [comment]
Yes. I think so.
