### ISSUE TITLE
Chebfun2 failures in Matlab 2016a

### ISSUE THREAD

**Issue by jaurentz** [chebfun/chebfun#1800]
`cheb/test_gallery2` and `chebfun2/test_plotting` fail on my Mac with Matlab 2016a.

**Comment by jaurentz** [comment]
The plotting bugs don't seem to be limited to Matlab 2016a. The following tests fail on my machine running Matlab 2015b:
```matlab
   cheb/test_gallery2.m
   chebfun/test_plot.m
   chebfun2/test_plotting.m
   chebfun2/test_surf.m
   chebfun2v/test_plotting.m
```

**Comment by ajt60gaibb** [comment]
Still failing? Can you easily fix yourself?  I do not see these failures.

**Comment by ajt60gaibb** [comment]
I just tried all this on MATLAB 2016a.  I don't see any of these failures now so I'm closing.
