### ISSUE TITLE
Fixed polynomial degree of a chebfun2

### ISSUE THREAD

**Issue by ajt60gaibb** [chebfun/chebfun#1801]
It used to be the case that `chebfun2( F, [m, n] )` did this: 

```
chebfun2(F, [m n]) returns a representation of a bivariate polynomial of 
  degree m in x and n in y. The polynomial is compressed in low rank form 
  and the rank k is still determined adaptively (satisfying k<=min(m,n)+1).
```

In the latest development code we get an error, though (maybe this is due to the recent changes in #1765?):   
```
chebfun2(@(x,y) x, [5 5]) 
Error using chebfun2/constructor>parseInputs (line 579)
Domain not valid or fully determined.
Error in chebfun2/constructor (line 36)
[op, dom, pref, isEqui, fixedRank, vectorize] = parseInputs(op,
varargin{:});
Error in chebfun2 (line 57)
            f = constructor(f, varargin{:}); 
```

**Comment by aaustin141** [comment]
Are there no tests for this syntax?

**Comment by ajt60gaibb** [comment]
Yes, there is one test.  Further investigation reveals that 

```
f = chebfun2( @(x,y) cos(x.*y), [10 11]);
[m,n] = length(f)
m =
    10
n =
    11
```
works, but if `m = n` then we have
```
f = chebfun2( @(x,y) cos(x.*y), [10 10]);
Error using chebfun2/constructor>parseInputs (line 579)
Domain not valid or fully determined.
Error in chebfun2/constructor (line 36)
[op, dom, pref, isEqui, fixedRank, vectorize] = parseInputs(op,
varargin{:});
Error in chebfun2 (line 57)
            f = constructor(f, varargin{:});
```

**Comment by bhashemi** [comment]
I guess the first condition in [this line](https://github.com/chebfun/chebfun/blob/development/%40chebfun2/constructor.m#L573) is irrelevant and should be removed. That could be relevant if `m` and `n` represent the domain in 1D, but not the degrees here. Shall I make this change?

**Comment by ajt60gaibb** [comment]
Great! Yes, please.  Thanks, @bhashemi.

**Comment by bhashemi** [comment]
Ok @ajt60gaibb . How about [this other line](https://github.com/chebfun/chebfun/blob/development/%40chebfun2/constructor.m#L576)? Shouldn't we replace it with
``
[xx, yy] = chebfun2.chebpts2(d(1)+1, d(2)+1);
``
unless we change the help text to say `m` and `n` are lengths, not degrees.

**Comment by ajt60gaibb** [comment]
Yes, the help text should say `lengths`, not `degrees` because we have 
``` 
f = chebfun(@(x) x, 10) 
length( f ) 
ans = 
      10 
```
