### ISSUE TITLE
Calling chebfun constructor in `chebfun2/sample`

### ISSUE THREAD

**Issue by bhashemi** [chebfun/chebfun#1808]
Currently in `Chebfun2/sample`, we do the following:
```
[C, D, R] = cdr( f ); 
Cvals = sample(chebfun(C), m);
Rvals = sample(chebfun(R), n);
```
My point is only about the parts `chebfun(C)` and `chebfun(R)` in the last two lines above. `C` and `R` are already quasimatrices. Is it needed to call the 1D chebfun constructor again on `C` and `R`? The point is that our goal here is just to sample `C` and `R`. Do we gain anything by calling the constructor one more time? This troubles me particularly when I make a cross-section of a Chebfun3 (so a Chebfun2). Why not just say the following?
```
[C, D, R] = cdr( f ); 
Cvals = sample(C, m);
Rvals = sample(R, n);
```
This change solves my issue in Chebfun3 and also none of the whole chebfun tests fail with this. Following #1807, is this related to trigfun-chebfun conversions? @ajt60gaibb,  would you (and possibly others) please give me a hint on this?

**Comment by ajt60gaibb** [comment]
I though this was needed to convert `trig` to `nonperiodic`. For example 
```
f = chebfun(@(x) sin(pi*x), 'trig')
f =
   chebfun column (1 smooth piece)
       interval       length     endpoint values trig
[      -1,       1]        3  -6.3e-17  1.8e-16 
vertical scale = 0.87 
>> chebfun(f)
ans =
   chebfun column (1 smooth piece)
       interval       length     endpoint values  
[      -1,       1]       22  -4.4e-16  4.3e-16 
vertical scale =   1 
```
By doing this, the command `sample` always returns the function on a Chebyshev tensor grid.  

Of course, the behavior of `sample` could be changed so that periodic chebfun objects are evaluated at equally-spaced tensor grids.

**Comment by aaustin141** [comment]
#1766 and #1768 may have some relevant discussion.

**Comment by gradywright** [comment]
I agree with @bhashemi in his original post.  Doing
```
[C, D, R] = cdr( f ); 
Cvals = sample(chebfun(C), m);
Rvals = sample(chebfun(R), n);
```
Is computationally wasteful.  `sample` is called every time `vscale` is called, which results in completely unnecessary overhead.  This happens, for example, every time `compression_plus` is called.  Additionally, the current implementation is responsible for a number of warnings that are being generated when `chebtest` is run in development.  See for example `tests/chebfun2v/test_twocomponents`.

I think `sample` should just return the values on whatever grid makes the most sense for the underlying tech.

**Comment by gradywright** [comment]
Here is an example illustrating the overhead associated with the current implementation of `chebfun2/sample`:
```
>> f = chebfun2(@(x,y) exp(-(10*x.*y).^2));
>> g = chebfun2(@(x,y) exp(-(10*(x-0.2).*y).^2));
```
Time for `f+g` on `development` branch:
```
>> tic, h = f+g; toc
Elapsed time is 0.100074 seconds.
```
Time for `f+g` on branch `fix-chebfun2-sample`
```
>> tic, h = f+g; toc
Elapsed time is 0.043789 seconds.
```

**Comment by ajt60gaibb** [comment]
I am happy with the functionality of `sample` to change for periodic chebfun2 objects to achieve this speed up.
