### ISSUE TITLE
Enforcing even/odd symmetries in trigfun (and Chebfun)

### ISSUE THREAD

**Issue by trefethen** [chebfun/chebfun#1814]
We already force the trigfun of a real function to be real (this required taking action, as the FFT introduces complex errors).  We don't, however, force the trigfun or the chebfun of an even or odd function to preserve that symmetry.

In the case of chebfuns, you have to look hard to find the loss of symmetry.  The first integer k for which cos(k*x) doesn't come out even is 1471 (at least on @jaurentz's Mac).  Similarly the first integer k for which sin(k*x) doesn't come out odd is 1429.

With trigfuns, however, the anomalies appear immediately.  cos(pi*x) is not even, and sin(pi*x) is not odd.  This is a "cosmetic" problem but a rather glaring one.  We propose to fix it for trigfuns, and while we're at it, likely do the same for chebfuns even though in that case the problem arises more rarely.

Here is our plan: (a) understand where the losses of symmetry are introduced; (b) either fix this, or work around it by making Chebfun test the input samples for symmetry and when it finds it, impose the appropriate symmetries on the output.  To be concrete: sampling cos(k*x) at chebpts(n) gives a perfectly even vector regardless of k and n.  The problem is that somewhere along the line, Chebfun loses that symmetry.

We'd be glad for comments on this project -- e.g. from @gradywright, who was probably the one who enforced reality for trigfuns of real functions.

One reason this is on our minds is that we've been working on tidying up the anomalies in `plotcoeffs` when it deals with coefficients that are exactly zero.  For example, the code
```
subplot(2,1,1), plotcoeffs(chebfun('cos(1470*x)'),'.')
subplot(2,1,2), plotcoeffs(chebfun('cos(1471*x)'),'.')
```
at present produces the figures below.  Our plotcoeffs work will improve the plotting of the first figure; the present issue is concerned with eliminating the disparity between the first and second figures.
![cosfig](https://cloud.githubusercontent.com/assets/3601488/14522904/e282e444-0228-11e6-84f6-1b407bdf6fa7.png)

**Comment by jaurentz** [comment]
It appears that the problem is that Matlab's `fft` does not preserve symmetry. See the following example:
```matlab
>> x = linspace(-1,1,100)'; x = (x-x(end:-1:1))/2; % enforce symmetry
>> vals = sin(pi*x); norm(vals+vals(end:-1:1)) % test symmetry (should be zero)
ans =
     0
>> cfs = fft(vals(1:end-1)); norm(real(cfs)) % test symmetry (should be zero)
ans =
     5.627286959121491e-15
>> cfs2 = fft(ifftshift(vals(1:end-1))); norm(real(cfs)) % test symmetry (should be zero)
     5.627286959121491e-15
```
So even when the input is exactly odd `fft` still introduces rounding errors. This suggests that we will have to manually test for even/odd symmetries in `vals2coeffs` and make the appropriate corrections to the outputs.

**Comment by trefethen** [comment]
And in addition, as your code shows but your words don't mention, also `linspace` does not enforce symmetry.  So we'll have to symmetrize `linspace` as well as do even/odd testing in `vals2coeffs`.

**Comment by gradywright** [comment]
I am really interested in this enhancement.  Odd/even symmetries in trigonometric expansions appear all over the place in Spherefun and are important to preserve (the same is true for Chebyshev expansions in  Diskfun).  What you are observing has greatly annoyed me since working on Spherefun, almost to the point where I thought about writing a `costech` and `sintech` subclass of `trigtech`.  At the core of my frustration is the point @jaurentz illustrated: the `fft` in Matlab does not preserve even/odd symmetries.  

Here is a related example to the one by @jaurentz illustrating this, but in the inverse direction.
```
>> cfs = 1./(1 + (-10:10).^2);   % Coefficients for even Fourier expansion
>> vals = fft(ifftshift(cfs));   % Get the corresponding values
>> norm(imag(vals))              % Imaginary part should be exactly zero
ans =
     3.843264103237619e-16
>> norm(vals(2:end)-vals(end:-1:2))  % vals should be exactly even
ans =
     7.686528206475237e-16
```
So, testing for symmetries may also be necessary in `coeffs2vals`.

**Comment by gradywright** [comment]
I mistakenly typed `fft` instead of `ifft` in my example.  Here is the updated code:
```
>> cfs = 1./(1 + (-10:10).^2);    % Coefficients for even Fourier expansion
>> vals = ifft(ifftshift(cfs));   % Get the corresponding values
>> norm(imag(vals))               % Imaginary part should be exactly zero
ans =
     0
>> norm(vals(2:end)-vals(end:-1:2))  % vals should be exactly even
ans =
     2.416190212695145e-17
```
Realness is exactly preserved, but not evenness.

**Comment by jrus** [comment]
Are there concrete/practical problems with lack of precise even/oddness? Rounding errors at the scale of `1e-16` seem inevitable in an approximate computation framework. Are there more severe consequences than potential confusion around some slightly scattered dots showing up at the `<1e-16` scale in `plotcoeffs`, or various sums not turning out identically zero?

@trefethen off topic note: in your top post here, some of your asterisks are being interpreted as italic markers. If you surround the code/math fragments in backticks (``​`...`​``), they will render character-for-character in a monospaced typeface.
