### ISSUE TITLE
Continuous analog of the Matlab sphere command

### ISSUE THREAD

**Issue by gradywright** [chebfun/chebfun#1821]
In matlab, `sphere` makes a surface plot of the unit sphere, whereas `[x,y,z]=sphere(n)` returns n-by-n gridded arrays `x`, `y`, and `z` such that `surf(x,y,z)` plots the unit sphere. 

I think we should have the continuous analog of this command as `cheb.sphere`, so that 
`[x,y,z] = cheb.sphere` gives spherefun objects `x`, `y`, and `z` representing the rank 1 functions `x=cos(lambda)sin(theta)`, `y=sin(lamba)sin(theta)`, and `z=cos(theta)`.

Similar to the proposed `cheb.xy` and `cheb.xyz` in #1816, this would save one from having to type
```
x = spherefun(@(x,y,z) x);
y = spherefun(@(x,y,z) y);
z = spherefun(@(x,y,z) z);
```
I am open to other names than `cheb.sphere`.

**Comment by trefethen** [comment]
My thinking is always about what's memorable.  How about this?
```
cheb.x    cheb.xy    cheb.xyz    cheb.xyzsphere
```
Note that the syntax should be just `cheb.xyzsphere`, not `[x,y,z] = cheb.xyzsphere`.
