### ISSUE TITLE
chebfun times a chebfun2

### ISSUE THREAD

**Issue by jaurentz** [chebfun/chebfun#1828]
Using the `cmatrix` analogy one should be able to left multiply a `chebfun2` by a row `chebfun`. This appears not to be implemented:
```matlab
>> f = chebfun('x');
>> f2 = chebfun2('x+y');
>> f'*f2
Error using * (line 88)
Undefined function 'mtimes' for input arguments of type chebfun and chebfun2. 
```
I think feature should be added but I'm not sure if it should be part of `chebfun/mtimes` or `separableApprox/mtimes`.

**Comment by ajt60gaibb** [comment]
The problem is that  `f'*f2` goes into `chebfun/mtimes`, not into 2D code.  In `chebfun/times`, if `f2` is an unknown object (like a `chebfun2` or `spherefun`), then I think it should essentially do:  
```
f'*f2 = transpose( transpose(f2)*f )
```
This way `chebfun/times` passes the buck onto the method implemented by the class of `f2`.

**Comment by nickhale** [comment]
Is the chebfun2 class not defined as superior to the chebfun class?
