### ISSUE TITLE
bug in label of trigfun `plotcoeffs`

### ISSUE THREAD

**Issue by trefethen** [chebfun/chebfun#1853]
When `plotcoeffs` is applied to a trigfun, the $x$ axis is labeled "wave number".  However, this is not the wave number as is universally understood.  For example, $\sin(x)$ should have wave number 1 on any domain.  In Chebfun, this only happens if the domain is $[-\pi,\pi]$.  Thus e.g. the commands
```
f = chebfun(@(x) sin(x),[-10*pi,10*pi],'trig'); plotcoeffs(f)
```
give the erroneous plot
![foo](https://cloud.githubusercontent.com/assets/3601488/14919454/d313540e-0e20-11e6-9bb2-a8193e5c18de.png)

This would cease to be an outright error if the $x$ axis were relabled to something like "normalized wave number".  However, please let's not do that.  I hope instead we can maintain the standard convention and keep the label but change the numbers: the numbers currently plotted need to be multiplied by $2\pi$ divided by the length of the domain.

**Comment by gradywright** [comment]
I agree @trefethen that the labeling of the coefficient plot is strange in the example you give.  Implementing the change you suggest is going to be a bit tricky (or messy depending on how you look at it) since currently the `chefun/plotcoeffs` code relies on the `plotcoeffs` code at the `tech` level to make the appropriate coefficient plots.  The `tech` levels are not suppose to know about domains.  Perhaps someone with a great knowledge of the Chebfun class structure can come up with a clean solution.  @nickhale or @aaustin141?

**Comment by nickhale** [comment]
@gradywright is right that technically this would break encapsulation. However, I think passing down a domain (or 'scaling' if we prefer to think that way) isn't too bad. I've implemented a quick version of that in #1854.

The only alternative I see is to adjust the x values in `chebfun/plotcoeffs` in the case of periodic techs, which seems just as (if not more) dirty.

**Comment by gradywright** [comment]
Thanks @nickhale!  I will take a look at #1854.

**Comment by gradywright** [comment]
It looks like #1854 does what @trefethen suggests.  However, the x-axis now says `Normalized wave number`.  @trefethen: you just want it to say `Wave number`, correct?  

Here is the new plot that is produced by #1854:
```
f = chebfun(@(x) sin(x),[-10*pi,10*pi],'trig'); plotcoeffs(f)
```
<img width="478" alt="fourcoeffplot" src="https://cloud.githubusercontent.com/assets/6304453/14988793/b656d530-1112-11e6-90af-73d48572de50.png">

**Comment by trefethen** [comment]
I had hoped either (a) we'd plot the true wave number to match the label "wave number", or
(b) we'd change the label to "normalized wave number" since what we were plotting was not the true wave number.  It looks as if *both* (a) and (b) have happened!  If we've really succeeded in plotting the true wave number, then yes, we no longer needed the word "normalized" and the label could revert to "wave number".
