### ISSUE TITLE
removing `display` from cheb.x, cheb.xy, cheb.xyzsphere

### ISSUE THREAD

**Issue by trefethen** [chebfun/chebfun#1861]
I have removed the `display` commands from `cheb.x`, `cheb.xy`, and `cheb.xyzsphere` in the development branch.  These commands led to output being generated whenever these commands are called, not suppressible with a semicolon.   I think such output is inappropriate and it makes examples using the codes look messy.  Since a code release is expected tomorrow, I've just gone ahead and made the change.  Of course if anybody sees a problem with this I'm happy to discuss it.

None of the guide chapters or examples currently call these codes  -- but in the case of `cheb.xy` and `cheb.xyzsphere`, which are particularly useful shortcuts, they should!

**Comment by ajt60gaibb** [comment]
OK. Thanks, @trefethen.
