### ISSUE TITLE
imag and conj needed for IVPs (treevar)

### ISSUE THREAD

**Issue by JFlry** [chebfun/chebfun#1901]
@trefethen and I have been working with simulations of electrons in orbit around a nucleus, using complex variables as usual for convenience.  For some of these computations we need `conj` and `imag`, but unfortunately they do not exist (in `treevar`).  This is a shame:

**Comment by asgeirbirkis** [comment]
I'm happy to look into this, @JFlry , could you please provide a minimum code example for me to study?

**Comment by JFlry** [comment]
@asgeirbirkis  , here is an example of a code that gives an error. 

> L = chebop(0,10);
> L.op = @(t,z) diff(z,2)+ z-conj(z);
> L.lbc = @(z) [z-1i; diff(z)-1];
> z = L\0; 

The error I get is the following one : 

> Undefined function 'conj' for input arguments of type 'treeVar'.

**Comment by asgeirbirkis** [comment]
@JFlry this now works on branch `fix-treeVar-imag-conj`, cf. 846cae6 . I get the following output from your example:
```
L = chebop(0,10);
L.op = @(t,z) diff(z,2)+ z-conj(z);
L.lbc = @(z) [z-1i; diff(z)-1];
z = L\0; plot(z)
z = L\0; subplot(1,2,1), plot(real(z)), subplot(1,2,2), plot(imag(z))
```
![treevar-imag-conj](https://cloud.githubusercontent.com/assets/3543429/15720164/1857288c-282b-11e6-98c3-5bb21c2576d1.png)

Have you got any more problems to test? If they work as you expect, I'll submit a PR!

**Comment by JFlry** [comment]
It seems to be working on my examples. 
Thank you for solving the problem !
