### ISSUE TITLE
eliminate `del2`

### ISSUE THREAD

**Issue by trefethen** [chebfun/chebfun#1911]
We have a command `del2` in Chebfun2 and separableApprox that just returns the Laplacian divided by 4.  It's not mentioned in the Guide or the examples or used in the Chebfun code anywhere as far as I can tell.  I propose that we eliminate it.  @ajt60gaibb and @gradywright, I'd be especially glad to hear if either of you sees a reason to keep it.  If nobody fights for `del2` in the next couple of days I hope @bhashemi will be so kind as to eliminate it.

**Comment by ajt60gaibb** [comment]
I probably added it a very long time ago as the continous analogue of the `del2` command in MATLAB. That's the only (non-)reason to keep it.  I am happy for it to be eliminated.

**Comment by gradywright** [comment]
I am also fine with it being removed.  I have never used it.

------------------------------------
Grady B. Wright
Professor
Department of Mathematics
Boise State University
1910 University Drive
Boise, ID 83725-1555, USA
http://math.boisestate.edu/~wright/

**Comment by bhashemi** [comment]
As of 8df1a4f this is fixed.
