### ISSUE TITLE
Chebfun2 should display "trig" when the chebfun2 is periodic

### ISSUE THREAD

**Issue by trefethen** [chebfun/chebfun#1915]
In Chebfun and Chebfun3, a "trig" indication is given by `disp` when the function is periodic.  Chebfun2, however, currently gives no such indication.  This should be fixed.  @ajt60gaibb, do you see any trouble with this?

**Comment by ajt60gaibb** [comment]
Sure. Please go ahead.

(This issue is the same as #1871.)
