### ISSUE TITLE
Use besselroots in diskfun.harmonic()

### ISSUE THREAD

**Issue by ajt60gaibb** [chebfun/chebfun#1953]

**Comment by ajt60gaibb** [comment]
`diskfun.harmonic()` still does not use besselroots, though.

**Comment by sfilip** [comment]
Oops, sorry. I was confused by the fact that there was no description for the issue.

**Comment by ajt60gaibb** [comment]
I believe we cannot use `besselroots` because of the inadequacy of the `besselroots` command when the Bessel parameter is `5<nu<11`, but I am not sure we have confirmed that. 

Is that the reason @heatherw3521?  If so, then this issue is really about the `besselroots` command.  I cannot remember why besselroots with `5<nu<11` is difficult (the Glaser-Lui-Rokhlin algorithm will definitely do it) any thoughts @LourencoPeixoto?

**Comment by heatherw3521** [comment]
Yes @ajt60gaibb , the reason we decided not to use `besselroots` is because for certain parameter choices (i.e., `5 < nu < 11`), `besselroots` does not always produce highly accurate approximations of the roots.  The issue is clearly documented in the `besselroots` help text.

**Comment by nickhale** [comment]
Do you only need integer nu values? If so, perhaps for this troublesome range you could just pre-compute the small roots and get the larger ones from large x asymptotics?

I attach my (very old) GLR implementation of `besselroots.m`, in case it is useful: [besselroots.txt](https://github.com/chebfun/chebfun/files/1306682/besselroots.txt)

**Comment by LourencoPeixoto** [comment]
Hi, @ajt60gaibb ! I agree with @heatherw3521. However recompute the Chebyshev series expansions from Piessens (http://www.sciencedirect.com/science/article/pii/0021999184900603) to full double precision could help.
