### ISSUE TITLE
Bug in separableApprox/median

### ISSUE THREAD

**Issue by bhashemi** [chebfun/chebfun#1969]
`separableApprox/median` contains a trivial bug that causes `chebfun2/median`, `diskfun/median` and `spherefun/median` to issue an error message:
```
>> f = chebfun2(@(x,y) cos(3*pi*(x.*y-1)));
>> g = median(f)
Function 'subsindex' is not defined for values of class 'chebfun2'.
Error in separableApprox/median (line 28)
vals = sample( f, sample, sample );   % sample on tensor grid.
Error in chebfun2/median (line 13)
[varargout{1:nargout}] = median@separableApprox(varargin{:}); 
```
Specifically, Lines 27-28 of `separableApprox/median` should be changed to something like:
```
grid = 2049;
vals = sample(f, grid, grid);   % sample on tensor grid.
```

**Comment by gradywright** [comment]
I propose we include a fix for this bug in the Diskfun pull request since it is a trivial change.

**Comment by bhashemi** [comment]
Sure, I agree.
