### ISSUE TITLE
Singfun does not support array-valued construction

### ISSUE THREAD

**Issue by seament** [chebfun/chebfun#1994]
Running the following code shows that singfun does not support array-valued construction.

``` matlab
f = @(x) [cos(x)./sqrt(1-x), cos(2*x)./sqrt(1-x)]; 
d = [0,1];
e = [0,-.5];
chebfun(f, d, 'exps', e)
```
For my project, this functionality is needed, and working around this issue becomes highly inefficient.
Can this be fixed internally?

**Comment by ajt60gaibb** [comment]
This makes the object that you want. One could put a piece of code like this into Singfun:

```
f1 = @(x) cos(x)./sqrt(1-x); 
f2 = @(x) cos(2*x)./sqrt(1-x); 
d = [0 1]; 
e = [0,-.5]; 
h1 = chebfun(f1, d, 'exps', e); 
h2 = chebfun(f2, d, 'exps', e); 
h = [h1 h2];
```
I believe that Chebfun will take care of the array-valued things after that.

**Comment by aaustin141** [comment]
There's nothing that theoretically prevents array-valued singfuns and deltafuns from existing, but implementing them is likely to take some work.  In the meantime, you can `horzcat()` indivdually-constructed singfun-based-chebfuns into a quasimatrix (array of chebfuns; see the code that @ajt60gaibb just posted), but as you've indicated, there will be some performance hit with this relative to a truly array-valued implementation.

Cross-ref. #671.

**Comment by seament** [comment]
Thank you! I will work around it with horzcat() in the meantime.
