### ISSUE TITLE
strict sign check in singleSignTest in Chebfun2 & Chebfun3

### ISSUE THREAD

**Issue by bhashemi** [chebfun/chebfun#1998]
When computing `abs`, `sqrt` and similar functions of `chebfun2`, `diskfun`, `spherefun` and `chebfun3` objects, we call the `singleSignTest` code. This checks whether the function values change sign in which case an error message is issued and that is reasonable. But, the check for positivity or negativity is too strict because it compares function values with `0` instead of a relative tolerance e.g., `chebfun2eps`. 

Assume that `f` is positive and we need `abs(f)`. The present implementation of `singleSignTest` causes unreasonable error messages when some of the values of `f` are smaller than zero though larger than 
`-1 x chebfun2eps` 
due to round-off errors. In such a case, a numerical person still expects `abs(f)` to work rather than giving an error message. 

The suggestion is to replace 
`if ( all( X >=0 ))`
with 
`if ( all( X >= -tol * vscale ))`
and similarly to replace 
`elseif ( all( X <= 0))`
with 
`elseif ( all( X <= tol * vscale))`
in `singleSignTest` of both `chebfun2` and `chebfun3`. A related issue is #1999 .

**Comment by oliviersete** [comment]
Closed by #2004
