### ISSUE TITLE
`singleSignTest` should not be called for complex-valued functions

### ISSUE THREAD

**Issue by bhashemi** [chebfun/chebfun#1999]
If `f` is a **complex-valued** `chebfun2`, `diskfun`, `spherefun` or `chebfun3` object and we need e.g. `abs(f)` or `sqrt(f)`, then there is no reason to call `singleSignTest`. We need a to add a line containing `iscomplex` e.g., in `abs(f)` before we call `singleSignTest`.

This issue is related to #1998 .

**Comment by oliviersete** [comment]
Closed by #2004
