### ISSUE TITLE
Wrong matrix multiplication in: f = toFunctionOut(disc, values, cutoff)

### ISSUE THREAD

**Issue by maxpolzin** [chebfun/chebfun#2021]
line 33:
% adjust size of cutoff if necessary
if ( length(m) ~= numel(values) )
    m = ones(numel(values),1)*max(m);   <- % in the current implementation this in the other way round
end

**Comment by maxinho** [comment]
I got the following error msg, when it is computed the other way round:

Error using  * 
Inner matrix dimensions must agree.

Error in chebcolloc2/toFunctionOut (line 33)
    m = max(m)*ones(numel(values),1);

Error in linop/linsolve (line 177)
    v = disc.toFunctionOut(values(:,k),cutoff);

Error in chebop/solvebvpNonlinear (line 90)
    [delta, disc, converged] = linsolve(L, res, pref, vscale(u));

Error in chebop/solvebvp (line 241)
    [u, info] = solvebvpNonlinear(N, rhs, L, u0, residual, pref, displayInfo);
