### ISSUE TITLE
Chebfun not constructed with Chebyshev coefficients of the second kind

### ISSUE THREAD

**Issue by seament** [chebfun/chebfun#2035]
I tried to create a chebfun using Chebyshev coefficients of the second kind. The 'chebkind' argument seems to be ignored when 'coeffs' is given as an option. I think this would be a sensible and convenient extension to chebfun's functionality. 

```
f = chebfun('exp(x)');

c1 = chebcoeffs(f, 'chebkind', 1);
c2 = chebcoeffs(f, 'chebkind', 2);

f1 = chebfun( c1, 'coeffs', 'chebkind', 1);
f2 = chebfun( c2, 'coeffs', 'chebkind', 2);

x = linspace(-1,1);
plot(x, f1(x), x, f2(x))
```

**Comment by kuanxu** [comment]
The property `chebkind` is for specifying which kind of Chebyshev points you use, when you construct a `chebfun` from values (of functions). The combination of `chebkind` and `2` means construction of a `chebfun` by sampling the given function at Chebyshev points of the first kind, i.e. the extreme points of Chebyshev polynomials of the first kind. It has nothing to do with the Chebyshev polynomials of the second kind. Currently, we don't have support for constructions using the Chebyshev polynomials of the second, third, and fourth kinds.

I think an error should be thrown when `chebkind` and `coeffs` are present at the same time in one construction line. It doesn't make much sense to construct a `chebfun` using values and coefficients simultaneously.
