### ISSUE TITLE
reopening adjoints for linear differential operators

### ISSUE THREAD

**Issue by trefethen** [chebfun/chebfun#2037]
The adjoints pull request #1795 got merged, but I am afraid this code, or least its documentation, is not ready for users.  I would like to reopen the pull request, but I think this is impossible at GitHub, so I'm creating this new issue instead, which I hope @jaurentz and @Hadrien-Montanelli can sort out for tomorrow's release.  

Problem 1: LINOPs vs CHEBOPs.  The former are not something we tell users about; the adjoint command is supposed to be used normally with chebops, isn't it?  Yet at the moment if I type `help adjoint` I get told about linops.  Weirdly if I type `help adjoint` a second time I get told about chebops, but `clear classes` reverts to linops again.  Anyway, one way or another users need to be pointed to useful information.  (Recall that we've had similar documentation problems with separableApprox, which users aren't normally supposed to be pointed to.)

Problem 2: users need examples!  That applies both in the help text for the code, and (we agreed at a recent chebfun meeting) the adjoint command should have something in our Examples collection.  At the moment to use `adjoint` I have to look at `tests/chebop/test_adjoint.m`, which is suboptimal.

**Comment by aaustin141** [comment]
Re. Problem 1:  On R2016b prior to merging #2038, I get the same behavior @trefethen reports wherein typing `help adjoint` once brings up the help text for `linop.adjoint()` and typing it a second time gives the text for `chebop.adjoint()`.  Updating my tree to include #2038 fixes this.

On R2016a, however, irrespective of whether I've updated for #2038, `help adjoint` comes up with _nothing_:

```
                            < M A T L A B (R) >
                  Copyright 1984-2016 The MathWorks, Inc.
                   R2016a (9.0.0.341360) 64-bit (glnxa64)
                             February 11, 2016

[...]

>> help adjoint

adjoint not found.

Use the Help browser search field to search the documentation, or
type "help help" for help command options, such as help for methods.
```

Doing `help chebop/adjoint`, however, works just fine.

**Comment by trefethen** [comment]
We'll make sure to point to `chebop/adjoint` in the release notes.  Meanwhile I am closing this issue as it is at least mostly addressed.  It would still be nice for somebody to write a Chebfun Example or two involving adjoints.  @jaurentz, are you tempted?
