### ISSUE TITLE
Can we vectorize, allow e.g. f*g instead of f.*g ?

### ISSUE THREAD

**Issue by trefethen** [chebfun/chebfun#2064]
I'd like to ask everybody, especially including @nickhale and @tobydriscoll and @aaustin141 since I think they may have well-thought-out opinions, an old question that I have asked before: can we adjust Chebfun so that things like  `f*g`  and  `x^2`  are allowed rather than forcing users to type  `f.*g`  and  `x.^2` ?  This has long been allowed in chebops, happily.

When I've raised this issue in past years, it has been argued that this would be dangerous, but not for the first time, I can't remember exactly what danger is realistically at issue here.  @nickhale, I'm guessing you know the code so well that you could very quickly try this and see if any tests fail.  What do you think?

As you all know, sticking close to Matlab syntax means a lot to me since it minimizes the Chebfun learning curve.  I favor deviation from Matlab only when there are substantial reasons.  My feeling is that a large fraction of the lines we type into Chebfun have things like  `f.*g`  and  `x.^2`  in them, and the convenience of being able to simplify that would indeed be substantial.

I am eager to see what people have to say on this.  Thanks.

**Comment by nickhale** [comment]
For multiplication and powers, I'm finally inclined to agree. I would be wary of division however, since `1/f` means something quite different to `1./f'.

In terms of implementation, it should be straightforwards. (`^` in particular would be trivial.)

**Comment by trefethen** [comment]
@nickhale, could you say more about division?  From a user point of view, I think it might increase rather than diminish confusion if we allowed * but not / .  For example, the good ol' Runge function would then be written 1./(1+x^2), which seems a bit of a chimera.

**Comment by nickhale** [comment]
Try the branch https://github.com/chebfun/chebfun/tree/feature-no-dots-in-times

```
>> cheb.x
>> x^2
ans =
   chebfun column (1 smooth piece)
       interval       length     endpoint values  
[      -1,       1]        3         1        1 
vertical scale =   1 
>> x.*x
ans =
   chebfun column (1 smooth piece)
       interval       length     endpoint values  
[      -1,       1]        3         1        1 
vertical scale =   1 
```

**Comment by nickhale** [comment]
At the moment `chebfun/mrdivide` does least squares
```
>> help chebfun/mrdivide
 /   Right matrix divide for CHEBFUN objects.
    B/A in general gives the least squares solution to X*A = B.
```

So either you'd have to lose that functionality (probably nobody is using it anyway) or for the scalar case (which is probably the 90%-use case) do division in `mrdivide` rather than the trivial least squares. I'm not sure I'm keen on the latter.

**Comment by nickhale** [comment]
I implemented the latter on the branch mentioned above:
```
>> 1/(1+16*x^2)
ans =
   chebfun column (1 smooth piece)
       interval       length     endpoint values  
[      -1,       1]      147     0.059    0.059 
vertical scale =   1 
```

**Comment by trefethen** [comment]
@nickhale, I notice (see below) that not everything is vectorized.  Is it easy to make this work too?

           Nick


```
>> f = chebfun('x*x');
Warning: Function failed to evaluate on array inputs.
Vectorizing the function may speed up its evaluation
and avoid the need to loop over array elements.
Use 'vectorize' flag in the CHEBFUN constructor call
to avoid this warning message.
> In chebfun>vectorCheck (line 904)
  In chebfun>parseInputs/parseOp (line 755)
  In chebfun>parseInputs (line 746)
  In chebfun (line 203)
```

**Comment by nickhale** [comment]
One can simply turn the warning off (i.e., delete it). The problem is then that something like `f = chebfun(@(x) sin(x')/x, [0 1])` will still construct and give a meaningful result. I guess we're just putting the onus on the user to ensure they give sensible input.
