### ISSUE TITLE
Diskfun feval not working for 3D arrays

### ISSUE THREAD

**Issue by gradywright** [chebfun/chebfun#2067]
I am working on some problems in cylindrical geometry and want to evaluate a function consisting of the product of a diskfun in `(r,theta)` and a function in `z` on a tensor-product grid.  For example:
```
f = @(x,y,z) feval(diskfun.harmonic(4,3),x,y).*sin(2*pi*z);
[tt,rr,zz] = meshgrid(linspace(-pi,pi,51),linspace(0,1,21),linspace(0,1,41));
xx = rr.*cos(tt);
yy = rr.*sin(tt);
```
I get the following error with `ff = f(xx,yy,zz)`:
```
Error using diskfun/feval (line 39)
The specified points to evaluate the function do not lie sufficiently close to the unit disk.
```
This does not fix the problem:
```
f = @(th,r,z) feval(diskfun.harmonic(4,3),th,r,'polar').*sin(2*pi*z);
ff = f(tt,rr,zz);
```
The issue appears to stem from the fact that by default `diskfun` evaluates in Cartesian coordinates and `separableApprox/feval` deals with tensor evaluations by flattening the tensor and then re-calling `feval`.

**Comment by heatherw3521** [comment]
You can tell diskfun to evaluate in polar coordinates in the feval command. Does this work?

`f = @(x,y,z) feval(diskfun.harmonic(4,3),x,y, 'polar').*sin(2*pi*z);
[tt,rr,zz] = meshgrid(linspace(-pi,pi,51),linspace(0,1,21),linspace(0,1,41));

xx = rr.*cos(tt);
yy = rr.*sin(tt);`

**Comment by gradywright** [comment]
Unfortunately, no.  That was what my second code segment pointed out.

------------------------------------
Grady B. Wright
Professor
Department of Mathematics
Boise State University
1910 University Drive
Boise, ID 83725-1555, USA
http://math.boisestate.edu/~wright/

**Comment by heatherw3521** [comment]
yes I missed that second part.
