### ISSUE TITLE
very small REMEZ bug

### ISSUE THREAD

**Issue by trefethen** [chebfun/chebfun#2073]
The following doesn't work (q is not set).
```
 cheb.x; f = abs(x-.5); [p,q,r] = remez(f,20); plot(f-p./q)
```
Presumable this should produce the same output as
```
 cheb.x; f = abs(x-.5); [p,q,r] = remez(f,20,0); plot(f-p./q)
```

**Comment by sfilip** [comment]
Such a change would break some code in ATAP ch.16 which asks for the output [p,err] when calling polynomial Remez. If this is not a problem, I'm happy to change the output format to be [p,q,r] even when a denominator degree is not given.

**Comment by trefethen** [comment]
Ah!  I see.  OK, I think we can leave it as is then.  I will close this issue.  Thanks for the clarification.
