### ISSUE TITLE
max2 fails for simple chebfun2 objects

### ISSUE THREAD

**Issue by trefethen** [chebfun/chebfun#2093]
If I execute `cheb.xy` then I can compute 2D maxima like these,
```
max(max(x));  max(max(0*x))
```
However, if I try 
```
max2(x);  max2(0*x)
```
they both fail.  @ajt60gaibb, would you be able to take a look at this?  I realize that in full generality this looks like a serious problem of algebraic geometry, but the cases that turn up in practice are probably simple functions of rank 1 for which a simple fix could presumably be introduced.

Curiously Chebfun3 does not have the same problem.

**Comment by ajt60gaibb** [comment]
Can you tell me more how they fail for you? 

I seem to get the following (which appears to be working): 
```
% In latest development: 
[mx, idx] = max2(x)
mx =
   1.000000000000000
idx =
   1.000000000000000  -0.999999331879020
```
and
```
% In latest development: 
[mx, idx] = max2(0*x)
mx =
     0
idx =
     0     0
```

**Comment by trefethen** [comment]
Thanks @ajt60gaibb.  These took so long that I did a ^C before noticing that eventually they succeed!  Regarding the first example,
```
>> cheb.xy
>> tic, max2(x), toc
ans = 1.000000000000000
Elapsed time is 6.073570 seconds.
```
Regarding the second, I misspoke: the problem is with `1+0*x`, not just `0*x`:
```
>> tic, max2(1+0*x), toc
ans = 1.000000000000000
Elapsed time is 11.329626 seconds.
```
Ten seconds to find the maximum of a constant seems very unfortunate... do you think something could be done?
