### ISSUE TITLE
Negative latitude output in spherefun2/max

### ISSUE THREAD

**Issue by Hadrien-Montanelli** [chebfun/chebfun#2119]
Spherefun uses a longitude/latitude representation with longitude in [-pi,pi] and latitude in [0,pi]. However, the following code returns a latitude outside [0,pi]:

`cheb.xyzsphere;
[m,loc] = max2(exp(x))`

**Comment by ajt60gaibb** [comment]
Underneath we use a longitude/latitude representation with longitude in [-pi,pi] and latitude in [-pi,pi] via double wrapping.  But, your right the `spherefun/max2` command check this.
