### ISSUE TITLE
Add an option to plot in the plane in spinsphere

### ISSUE THREAD

**Issue by Hadrien-Montanelli** [chebfun/chebfun#2120]
`spinsphere` plots a movie of the solution on the sphere. It'd be great to add an option to plot data in the lambda-theta plane.

**Comment by gradywright** [comment]
I've started a branch `feature-spherefun-plotting` that contains many different plotting options via `surf` on a `spherefun`.  Once this is ready to go, it may be useful for these movies.  I would appreciate any feedback on some of the plotting features and their functionality.

**Comment by trefethen** [comment]
Thanks! -- and indeed really this whole issue is about Spherefun, not just `spinsphere`.

**Comment by Hadrien-Montanelli** [comment]
Solved with #2162.
