### ISSUE TITLE
Multiplying a chebfun2 with prescribed rank by a negative constant

### ISSUE THREAD

**Issue by sfilip** [chebfun/chebfun#2143]
The following does not work as it should.

```
>> f = chebfun2('x.^2+y.^2',4)
f =
   chebfun2 object
       domain                 rank       corner values
[  -1,   1] x [  -1,   1]        4     [   2    2    2    2]
vertical scale =   2 
>> f.*(-4)
ans =
   chebfun2 object
       domain                 rank       corner values
[  -1,   1] x [  -1,   1]        4     [ NaN  NaN  NaN  NaN]
vertical scale = NaN 
```

Not specifying the rank works fine.
```
>> f = chebfun2('x.^2+y.^2')
f =
   chebfun2 object
       domain                 rank       corner values
[  -1,   1] x [  -1,   1]        2     [   2    2    2    2]
vertical scale =   2 
>> f.*(-4)
ans =
   chebfun2 object
       domain                 rank       corner values
[  -1,   1] x [  -1,   1]        2     [  -8   -8   -8   -8]
vertical scale =   8 
```
Thanks Abdul-Lateef Haji-Ali for pointing this out.

**Comment by haji-ali** [comment]
It was actually Dmitry Belyaev who pointed this out to me.

I suspect that some of the coefficients are NaN when specifying the rank. Possibly related to this is that fact that calling `coeffs2` on either function returns exactly the same coefficients. Moreover, there is no 'all' flag that returns all the coefficients as `coeffs` does in 1D.

**Comment by ajt60gaibb** [comment]
It's just that "zero" pivots need special care. The example "f = chebfun2('x.^2+y.^2',4)" made a rank-4 function from a rank-2 one, and did this by tagging on 2 zero pivots.
