### ISSUE TITLE
adding a circle to a Diskfun plot

### ISSUE THREAD

**Issue by trefethen** [chebfun/chebfun#2148]
I wish we could add a circle to a diskfun plot.  At the moment, for example,
```
plot(randnfundisk(.5), 'zebra')
```
gives the figure below.  I'd like to be able to type
```
plot(randnfundisk(.5), 'zebra', 'circle')
```
and get the unit circle included to give the image shape.
![foo](https://cloud.githubusercontent.com/assets/3601488/26240301/7082ef2a-3c78-11e7-89fb-6166247da8c7.png)

**Comment by heatherw3521** [comment]
I will add this option in the plot command.

**Comment by heatherw3521** [comment]
I notice that for contour plots, we always add the circle; it is the default option. Without the circle, the plot doesn't look very nice. 

 Perhaps it should be the same for the zebra plot?

**Comment by trefethen** [comment]
I'd be happy with that.
