### ISSUE TITLE
erf not symmetrical

### ISSUE THREAD

**Issue by oc-rodu** [chebfun/chebfun#2149]
With  Version 5.6.0 16-Dec-2016, erf does not preserve symmetry erf(z)=-erf(-z). For example:

>> t=chebfun('t',[0,10])
>> (2/sqrt(pi))*integral(exp(-t.^2),0,1.5)+(2/sqrt(pi))*integral(exp(-t.^2),0,-1.5)
ans =
 -82.027889411017114
>> erf(1.5)+erf(-1.5) % now try matlab's built in function
ans =
     0

problem remains with quadl:
>> (2/sqrt(pi))*quadl(exp(-t.^2),0,1.5)+(2/sqrt(pi))*quadl(exp(-t.^2),0,-1.5)
ans =
 -82.027889285504628

**Comment by aaustin141** [comment]
Try building your chebfun on [-10, 10] instead:
```
>> t = chebfun(@(t) t, [-10, 10]);
>> (2/sqrt(pi))*integral(exp(-t.^2),0,1.5)+(2/sqrt(pi))*integral(exp(-t.^2),0,-1.5)
ans =
     0
```

**Comment by oc-rodu** [comment]
Thanks for the prompt response, much better, I don't get exact zero like you did though, why could that be?

>> (2/sqrt(pi))*integral(exp(-t.^2),0,1.5)+(2/sqrt(pi))*integral(exp(-t.^2),0,-1.5)
ans =
  -1.1102e-16

**Comment by oc-rodu** [comment]
thanks, here are some examples:
t=chebfun(@(t)t,[-10,10]);
>> (2/sqrt(pi))*integral(exp(-t.^2),0,1.5)+(2/sqrt(pi))*integral(exp(-t.^2),0,-1.5)
ans =
  -1.1102e-16
>> t=chebfun(@(t)t,[-5,5]);
>> (2/sqrt(pi))*integral(exp(-t.^2),0,1.5)+(2/sqrt(pi))*integral(exp(-t.^2),0,-1.5)
ans =
     0
>> t=chebfun(@(t)t,[-2.5,2.5]);
>> (2/sqrt(pi))*integral(exp(-t.^2),0,1.5)+(2/sqrt(pi))*integral(exp(-t.^2),0,-1.5)
ans =
     0
>> t=chebfun(@(t)t,[-2,2]);
>> (2/sqrt(pi))*integral(exp(-t.^2),0,1.5)+(2/sqrt(pi))*integral(exp(-t.^2),0,-1.5)
ans =
  -2.2204e-16
