### ISSUE TITLE
chebfun3 constructor test takes over 6 minutes

### ISSUE THREAD

**Issue by nickhale** [chebfun/chebfun#2159]
Is this typical / expected?

`Test #003: chebfun3t/test_constructor.m ... passed in 392.5988s`

**Comment by trefethen** [comment]
I just tried it and it took 69 seconds on my desktop.  (Still too long! -- we should strive for speedy tests, especially in a corner of Chebfun as little used as Chebfun3t.)

**Comment by sfilip** [comment]
Tried it on my machine as well. It took 21 seconds.

**Comment by nickhale** [comment]
My laptop does a better job (approx 2 mins), where I get the following:

```
>> profile on, chebfun3t(@(x,y,z) 1./(1+x.^2.*y.^2.*z.^2), [-2 2 -2 2 -2 2]), profile off, profile viewer
 
ans =
 
   chebfun3t object 
   coeffs: 261 x 265 x 263 
   domain: [-2, 2] x [-2, 2] x [-2, 2]
   vertical scale = 1
```
![screen shot 2017-05-23 at 16 45 16](https://cloud.githubusercontent.com/assets/2035010/26360108/88274394-3fd7-11e7-9be9-b6fb8cc32492.png)

**Comment by nickhale** [comment]
Strangely I now cannot reproduce this.
