### ISSUE TITLE
spinsphere initial condition

### ISSUE THREAD

**Issue by trinh** [chebfun/chebfun#2166]
In the following code

```
clear
close all

% Parameters:
f = .8; E = 4;  epsilon = .075; 
m = 32;
tspan = [0:1:2]; % time interval

% Operator:
S = spinopsphere(tspan);
S.lin = @(u,v) [epsilon^2*lap(u); lap(v)];
S.nonlin = @(u,v) [epsilon^2*E-u+f*u.^2.*v; 1/(epsilon^2)*(u-u.^2.*v)];

% Initial condition:
u0 = spherefun(@(lam,th) epsilon^2*E/(1-f));
u0 = u0.*(1 + 0.02*randnfunsphere(0.1));
v0 = spherefun(@(lam,th) (1-f)/(epsilon^2*E));
v0 = v0.*(1 + 0.02*randnfunsphere(0.1));
U0 = chebmatrix([]); U0(1,1) = u0; U0(2,1) = v0;
S.init = U0;

% Solve:
[Uout, Tout] = spinsphere(S, 32, 0.01);
norm(Uout{1,1}-u0)
norm(Uout{2,1}-v0)
```

the norm of the t = 0 outputted solution seems to differ to the initial chebfun that's fed in. For instance `Uout{2,1}-v0` can give differences as large as O(1). 

It has something to do with an initial time step or processing that is applied to the initial condition.

**Comment by Hadrien-Montanelli** [comment]
The spinsphere code (and more generally any spin code) discretises the initial condition at the begging of the time-stepping, and then stores it. At the end of the time-stepping, it creates a spherefun (or chebmatrix) from the discrete data (discretised initial condition and intermediate/final solutions). 

In your case, you're not using enough grid points - 32 is too small. As a rule of thumb, don't go below 128. 


Hadrien

**Comment by trinh** [comment]
Thanks @Hadrien-Montanelli . It is still somewhat confusing for me to remember that the order of the chebfun2 object is different from the order (discretization) required in the spinsphere code. 

I think this issue is now resolved.
