### ISSUE TITLE
cummax command

### ISSUE THREAD

**Issue by trefethen** [chebfun/chebfun#2174]
Let's make a `cummax` command.  `g = cummax(f)` would make a chebfun `g` which is the cumulative maximum of the chebun `f`.  There is a `cummax` command for vectors in one of the Matlab toolboxes.

For example, I'd love to be able to do `plot(cummax(randnfun([0 10])))`.

An algorithm might go like this.  Make a vector of breakpoints by doing `[~,p] = max(f,'local')` and then extracting `cummax(b)`.  Now, on each interval `[p(i),p(i+1)]` defined by these breakpoints, compute the maximum of `f(p(i))` and `f(x)`.

And of course `cummin(f) = -cummax(-f)`.

**Comment by sfilip** [comment]
Implemented.
