### ISSUE TITLE
give a chebop the default domain [-1,1]

### ISSUE THREAD

**Issue by trefethen** [chebfun/chebfun#2178]
Since chebfuns have a default domain [-1,1], it seems to be that the same should be true of chebops.  This would be both (a) sometimes convenient and (b) what an experienced Chebfun user would expect.

**Comment by asgeirbirkis** [comment]
The chebop situation at the moment is similar to the one for chebfun I believe:
```
>> f = chebfun;
>> f.domain
ans =
     []
>> g = chebfun('x');
>> g.domain
ans =
    -1     1
>> N = chebop;
>> N.domain
ans =
     []
>> M = chebop(@(u) diff(u));
>> M.domain
ans =
    -1     1
```
Was your expected behaviour different?

**Comment by trefethen** [comment]
Ah, beautiful.  You guessed correctly the nature of my error!  Thanks very much.  I will close the issue.
