### ISSUE TITLE
Fredholm and Volterra operators not working for integro-DIFFERENTIAL equations

### ISSUE THREAD

**Issue by nickhale** [chebfun/chebfun#2179]
Note that pure integral operators seem to work, but mixed operators fail with a `treeVar`-related message.

The tests for these operators are very basic. As far as I can tell they only check linear integral operators in `tests/chebop/test_intops.m`. This is probably why this has gone unnoticed.

Sample:
```
K = @(x,y) exp(-(x-y));
A = chebop(@(x,u) diff(u) + fred(K,u));
A.lbc = 1;
A\1
```
Output:
```
Undefined function 'fred' for input arguments of type 'treeVar'.
Error in @(x,u)diff(u)+fred(K,u)

Error in treeVar.toFirstOrder (line 58)
    fevalResult = funIn(t, args{:});
Error in chebop/solveivp (line 130)
        treeVar.toFirstOrder(N.op, rhs, N.domain);
Error in  \  (line 49)
    [varargout{1:nargout}] = solveivp(N, rhs, pref, varargin{:}); 
```

**Comment by aaustin141** [comment]
Is this perhaps at all related to the problems @tobydriscoll was having with `volt()` in #2122?

**Comment by nickhale** [comment]
I think they are different issues, but I confess that my knowledge of `treeVar` is very limited.

**Comment by nickhale** [comment]
As a workaround one can do the following:
```
K = @(x,y) exp(-(x-y));
A = chebop(@(x,u) diff(u) + fred(K,u));
A.bc = @(x,u) u(-1);
```
i.e., impose the boundary condition via .bc rather than .lbc. 

Presumably the problem is somewhere in the conversion to first order problems for IVPs?
