### ISSUE TITLE
Compatibility issue: Matlab R2009a

### ISSUE THREAD

**Issue by pierslawrence** [chebfun/chebfun#2183]
Apparently, the ability to ignore output arguments of functions using a tilde ~ was only introduced in Matlab version R2009b. Since a number of Chebfun functions, specifically some of the newer codes, use the tilde, and thus do not work with R2009a. The occurrences of this issue are shown below:

- `aaa.m:[~, ~, V] = svd(A, 0);`
- `@chebfun/inufft.m:[~, p]  = chebfun.nufft(f, omega, 1);`
- `@chebfun/inufft.m:[~, pt] = chebfun.nufft(f, omega/N, 2);`
- `@chebfun/inufft.m:[~, pct] = chebfun.nufft(conj(f), N*x, 1);`
- `@chebfun/idlt.m:[~, ~, ~, t_leg] = legpts(n);                 % Legendre grid (in theta)`
- `@chebfun/ndct.m:[~, ~, ~, t_leg] = legpts(n);                 % Legendre grid (in theta)`
- `@chebfun/nufft.m:[~, t, ~, K] = algorithmicParameters(omega/N, size(c,1), tol);`
- `@chebfun/nufft.m:[~, t, ~, K] = algorithmicParameters(x, size(c,1), tol);`
- `@chebfun3/root.m:[~, ind] = min(abs(T(:)));`
- `@chebfun3/plotcoeffs.m:[~, fCols, fRows, fTubes] = tucker(f);`
- `@chebfun3/constructor.m:[~, ind] = find(r==min(r));`
- `@chebtech/trigcoeffs.m:[~, numCols] = size(f);`
- `diffmat.m:[~, idx] = min(abs(denom), [], 2);`
- `diffmat.m:[~, idx] = min(abs(denom), [], 2); `
- `diffmat.m:[~, idx] = min(abs(denom), [], 2);`
- `introw.m:[~,r] = chebpts(n,dom);`
- `tests/misc/test_jacpts.m:[~, w] = jacpts(114, -.5, 0);`
- `tests/misc/test_minimax.m:[~, ~, rbest] = minimax(f, 2, 2, 'tol', 1e-12, 'maxIter', 20);`
- `tests/misc/test_minimax.m:[~, ~, rbest] = minimax(f, 3, 2);`
- `tests/misc/test_minimax.m:[~,~,r1] = minimax(f1,1,3); sample1 = r1(.3)-f1(.3);`
- `tests/misc/test_minimax.m:[~,~,r2] = minimax(f2,1,3); sample2 = r2(.3)-f2(.3);`
- `tests/misc/test_minimax.m:[~, ~, ~,err,~] = minimax(f, 30, 30, 'silent');`
- `tests/misc/test_minimax.m:[~,~,r,err,~] = minimax(f,4,4,'silent');`
- `tests/chebfun/test_remez.m:[~, ~, rbest] = remez(f, 2, 2, 'tol', 1e-12, 'maxIter', 20);`
- `tests/chebfun/test_remez.m:[~, ~, rbest] = remez(f, 3, 2);`
`

**Comment by trefethen** [comment]
Thanks @pierslawrence.  We are aware of this but had assumed it was not such a big issue since tildes were introduced 8 years ago and we don't think there are many Chebfun users whose Matlabs are that old.  Of course, I would have no objection if you or another person reading this has the energy to change the codes to eliminates the tildes.

**Comment by pierslawrence** [comment]
Dear @trefethen. I was a bit miffed by the issue at first. I had indeed thought the tilde functionality has been around forever! I have a student from the African Institute for Mathematical Sciences in Rwanda interested in using Chebfun, and unfortunately he has a very ancient version of Matlab. Perhaps just changing the earliest compatible version to R2009b on the website would also solve this issue.

**Comment by sfilip** [comment]
This is now done.
