### ISSUE TITLE
bug in eigs

### ISSUE THREAD

**Issue by trefethen** [chebfun/chebfun#2193]
`eigs` seems to erroneously computing multiple copies of eigenvalues when you give it unusual boundary conditions.  @tobydriscoll, can you take a look?  Maybe it's just a tolerance that needs to be adjusted?  I ran into the trouble when attempting to add an exercise to the eigenvalues chapter of _Exploring ODEs_.

For example, this computation is successful:
```
L = chebop(@(y) diff(y,2),[0 pi]); L.lbc = 0;
L.bc = @(y) deriv(y,pi); eigs(L)
ans =
  -30.2500
  -20.2500
  -12.2500
   -6.2500
   -2.2500
   -0.2500
```
This computation, however, gives two doubled-up eigenvalues:
```
>> L.bc = @(y) deriv(y,pi)-deriv(y,0); eigs(L)
ans =
   0.0000 + 0.0000i
  -4.0000 + 0.0000i
  -4.0000 + 0.0000i
 -16.0000 - 0.0000i
 -16.0000 + 0.0000i
 -36.0000 + 0.0000i
```
So does this:
```
>> L.bc = @(y) sum(y); eigs(L)
ans =
  -36.0001
  -35.9999
  -16.0000
  -16.0000
   -4.0000
   -4.0000
```

**Comment by tobydriscoll** [comment]
Turns out this is not a bug. As pointed out by Yuji Nakatsukasa (for the middle case above), the problem has defective nonzero eigenvalues and Jordan blocks of size 2. So the repeated eigenvalues make sense.
