### ISSUE TITLE
The Newton method in Lagpts needs improving

### ISSUE THREAD

**Issue by ajt60gaibb** [chebfun/chebfun#2199]
@popsomer, any idea? 

```
[x,w,v] = lagpts(5001);
Error using lagpts>alg_rh (line 223)
Newton method may not have converged.
Error in lagpts (line 118)
    [x, w] = alg_rh(n, strcmpi(method,
    'RHW'), alpha);  % Nodes and weights
```

**Comment by sslchi** [comment]
I found that for `alpha = 3, n = 400`, Newton method may not have converged.
```
[x, w, v] = lagpts(400,3);
Error using lagpts>alg_rh (line 223)
Newton method may not have converged.

Error in lagpts (line 118)
    [x, w] = alg_rh(n, strcmpi(method, 'RHW'), alpha);  % Nodes and weights
 ```

**Comment by popsomer** [comment]
The error can be avoided by increasing the tolerances in lagpts, but there will always be an n above which the Newton step remains above the tolerance for the given maximal number of iterations. A better solution would be to use the explicit expansions in my pull request #2200 which avoid Newton iterations. Do you agree, @ajt60gaibb @sslchi ?
