### ISSUE TITLE
Mixed-tech row-times-column product runs away when the row is based on trigtech.

### ISSUE THREAD

**Issue by aaustin141** [chebfun/chebfun#2209]
The following computations all work just fine:
```
>> f = chebfun(@(x) sin(pi*x), 'tech', @trigtech);
>> g = chebfun(@(x) cos(pi*x));
>> f'*f
ans =
     1
>> g'*g
ans =
   1.000000000000000
>> g'*f
ans =
     7.409082265771725e-18
```
But if I do `f'*g`, the computation seems to hang.

This is with current development (7dec37a3) on MATLAB R2016b.

**Comment by gradywright** [comment]
It looks like there is an issue with the constructor when the input function is a `chebfun row`.  This simpler piece of code also causes the constructor to hang:
```
g = chebfun(@(x) cos(pi*x))';
h = chebfun(g);
```
While for `trigfuns`, a similar piece of code causes an error:
```
 g = chebfun(@(x) cos(pi*x),'trig')';
h = chebfun(g,'trig')
```

**Comment by trefethen** [comment]
Fascinating!  I confirm this problem -- including if you use the normal user-facing syntax `f = chebfun(@(x) sin(pi*x), 'trig')`.  @gradywright, is this something you could look at?

**Comment by gradywright** [comment]
What should be the result of constructing a chebfun from _chebfun row_, i.e.
```
g = chebfun(@(x) cos(pi*x))';
h = chebfun(g);
```
I'm assuming we want `h` to be a _chebfun column_?

**Comment by trefethen** [comment]
Fascinating question.  A column sounds reasonable but I haven't spotted a particularly ironclad argument in either direction.
