### ISSUE TITLE
Chebfun replaces built-in function EXPINT and breaks existing code

### ISSUE THREAD

**Issue by advanpix** [chebfun/chebfun#2223]
Chebfun replaces MATLAB's built-in function [EXPINT](https://www.mathworks.com/help/matlab/ref/expint.html) with its own class with the same name, but different semantic.

This breaks programs which uses the built-in [EXPINT](https://www.mathworks.com/help/matlab/ref/expint.html) function. After installing the Chebfun: 

```
>> expint(rand(100))
Error using expint (line 251)
Unrecognized scheme. 

>> which expint
[...]\chebfun\@expint\expint.m  % expint constructor
```

This is quite serious issue, as it breaks default and expected MATLAB behavior.
Would appreciate if you consider fixing it (e.g. by switching to non-intrusive name for your class).

**Comment by Hadrien-Montanelli** [comment]
On it.

**Comment by Hadrien-Montanelli** [comment]
#2224 fixes this.

**Comment by advanpix** [comment]
Thank you for the quick fix.
