### ISSUE TITLE
Spinsphere test fails

### ISSUE THREAD

**Issue by abigopal** [chebfun/chebfun#2234]
The second test in /tests/spinopsphere/test_spinsphere.m currently fails during the nightly test. 

```
%% GL:
tol = 1e-2;

% Solve with DT and DT/2:
S = spinopsphere('GL'); S.tspan = S.tspan/10;
N = 128; dt = 1e-1;
s = rng; u = spinsphere(S, N, dt, 'plot', 'off');
rng(s); v = spinsphere(S, N, dt/2, 'plot', 'off');

% Compare:
dom = S.domain;
[xx, yy] = meshgrid(linspace(dom(1), dom(2), 50));
scale = max(max(abs(v(xx,yy))));
max(max(abs(u(xx,yy) - v(xx,yy))))/scale < tol
 ```

Outputs:
```
ans =

  logical

   0

```

**Comment by Hadrien-Montanelli** [comment]
I can't reproduce this. Can you please elaborate? For example - is this pass(1) or pass(2) that is 0? How large is the numerical error you get compare to the tolerance?

**Comment by Hadrien-Montanelli** [comment]
Also - what versions of Chebfun/MATLAB are you using?

**Comment by abigopal** [comment]
It's pass(2) that is 0. MATLAB version 2016b and the development branch of Chebfun. Since a random number is generated with each execution, I can't give you an exact numerical error, but I have observed that it fluctuates from 0.02 to 0.1 depending on the run.

**Comment by Hadrien-Montanelli** [comment]
Thanks @abigopal. I ran the tests a dozen times on my machine, always passed - bizarre. Several options here:

1) change the initial condition;
2) decrease dt;
3) increase N.

Since your machine seems to be more sensitive to rounding errors than mine, I'd recommend 1. 

For example,
```
% Solve with DT and DT/2:
S = spinopsphere('GL'); S.tspan = S.tspan/10; 
S.init =  spherefun(@(x,y,z) cos(cosh(x.*z)-y));
N = 128; dt = 1e-1;
u = spinsphere(S, N, dt, 'plot', 'off');
v = spinsphere(S, N, dt/2, 'plot', 'off');
```

It works on my machine, let me know if it works on yours.

**Comment by abigopal** [comment]
@Hadrien-Montanelli , option 1 works on my machine--the code you gave me passes. Should we change the test?

**Comment by Hadrien-Montanelli** [comment]
Great. Sure, let's do this. Feel free to go ahead and implement it. (Usually we don't issue pull requests when we do minor changes in the tests.)

**Comment by abigopal** [comment]
I pushed the change and will close this issue.

**Comment by Hadrien-Montanelli** [comment]
Thanks @abigopal.
