### ISSUE TITLE
Small bug in MINIMAX input parsing

### ISSUE THREAD

**Issue by nickhale** [chebfun/chebfun#2244]
The following is wrong:
```
>> minimax(@exp, 5)
ans =
   chebfun column (1 smooth piece)
       interval       length     endpoint values  
[      -1,       1]        2        -1        1 
vertical scale =   1 
```
although this is fine:
```
>> minimax(@(x) exp(x), 5)
ans =
   chebfun column (1 smooth piece)
       interval       length     endpoint values  
[      -1,       1]        6      0.37      2.7 
vertical scale = 2.7 
```

The problem is that `@exp` (although being a valid function handle) is parsed as a string by `str2op` in `minimax` and converted to `@(exp) exp`. 

I think adding the following on line 103 is a fix:

```
    if ( ischar(f) )
        fHandle = str2op(vectorize(f));
    else
        fHandle = f;
    end
```

**Comment by sfilip** [comment]
Thanks @nickhale for spotting this! I agree with your fix suggestion. I'm issuing a pull request now.
