### ISSUE TITLE
Bug in lagpts for small n

### ISSUE THREAD

**Issue by nickhale** [chebfun/chebfun#2270]
I just discovered the following bug
```
>> lagpts(5) - lagpts(5, 'gw')
ans =
  -0.000000000000001
  -0.000000000000001
                   0
   0.000000000000004
  -0.965661467809641
```
Since this (or something similar) occurs for each of the `lagpts` `'method'` options other than `'gw'`, I suspect that the intial guess for this small value is not sufficient for the Newton-like approaches to converge.

Running the following, I find it's a problem for `n = 5,6,7,8`. I therefore suggest defaulting to the Golub-Welsch approach when `n <= 10`.
```
>> for k = 1:20, try, err(k) = norm(lagpts(k) - lagpts(k, 'gw'), inf) > 1e-4;, catch err(k) = 1; end, end, err
err =
     0     0     0     0     1     1     1     1     0     0     0     0     0     0     0     0     0     0     0     0
```

**Comment by LourencoPeixoto** [comment]
Hi

I've worked with REC (Newton iterations on the recurrence relation) for the zeros of Laguerre polynomials in the past. In fact this method is very efficient for such zeros when `n<365` with approximations in Stroud and Secrest. Less than 10 iterations are required. The same holds to Laguerre generalized polynomials. Furthermore REC is more faster than GW.

**Comment by LourencoPeixoto** [comment]
Hi @nickhale . 

I believe that there's the same problem for `n=190, 195, 200, 201, 210` too.

**Comment by nickhale** [comment]
On further investigation, it seems that there are some serious issues with the `lagpts` code in the master branch.

Here are my results (you can find the code below - where oldlagpts is an old version from before the GLR algorithm was removed):

![err](https://user-images.githubusercontent.com/2035010/44529725-1388ea00-a6ed-11e8-807e-c6b1f99441c1.png)
![time](https://user-images.githubusercontent.com/2035010/44529726-1388ea00-a6ed-11e8-8b28-07b0f028a506.png)

My conclusions are: 
- 'rec' seems to break after around n = 370 (overflow?)
- 'exp' is completely broken (the problem seems to be with a few of the larger roots)
- 'RH' gives reasonable accuracy, but only when n is sufficiently large.

My suggestions are (unless there are quick fixes):
- Reinstate 'glr'
- Disable 'exp'
- Use 'gw' for n < 128
          'glr' for 128 <= n < 512
          'RH' for 512 <= n.

```
nn = round(logspace(2, 3, 100));
for n = nn
    disp(n)
    
    tic
    x_gw = lagpts(n, 'gw');
    t_gw(n) = toc;
    
    tic
    x_rec = lagpts(n, 'rec');
    t_rec(n) = toc;
    
    tic
    x_RH = lagpts(n, 'RH');
    t_RH(n) = toc;
    
    tic   
    x_exp = lagpts(n, 'exp');
    t_exp(n) = toc;
    
    tic
    x_glr = oldlagpts(n, 'glr');
    t_glr(n) = toc;
    
    err_rec(n) = norm(x_gw - x_rec, inf);
    err_RH(n) = norm(x_gw - x_RH, inf);
    err_exp(n) = norm(x_gw - x_exp, inf);
    err_glr(n) = norm(x_gw - x_glr, inf);
end

figure(1)
loglog(NaN, NaN, nn, err_rec(nn), ...
    nn, err_RH(nn), nn, err_exp(nn), nn, err_glr(nn), 'LineWidth', 3)
shg
legend('GW - GW', 'REC - GW', 'RH - GW', 'EXP - GW', 'GLR - GW', 'Location', 'NW')
title('error (inf norm) vs GW')
print -dpng err

figure(2)
loglog(nn, t_gw(nn), nn, t_rec(nn), ...
    nn, t_RH(nn), nn, t_exp(nn), nn, t_glr(nn), 'LineWidth', 3)
legend('GW', 'REC', 'RH', 'EXP', 'GLR', 'Location', 'NW')
title('time (secs)')
print -dpng time
```

**Comment by LourencoPeixoto** [comment]
Yes, in fact 'rec' breaks due to overflow. However I believe that is important to recall that the algorithm 'rec' as in Stroud and Secrest (or in Numerical Recipes) is faster and more accurate than 'gw' until the overflow occurs.

**Comment by nickhale** [comment]
My experiment above suggests that the `gw' option is actually marginally faster than `rec' for n < 129, but that might be because the `rec' code doesn't seem to be vectorised. But yes, if `rec' is more accurate then I agree it should be used for this small n regime.

**Comment by LourencoPeixoto** [comment]
I made some comparasions between 'GW', 'REC', and 'REC_{new}' (its function is attached) as introduced in Stroud and Secrest for `n=[10:100 110:10:360]`. The exact value is GW in quadruple precision.

![untitled](https://user-images.githubusercontent.com/12887346/44883042-2e7ad180-ac8c-11e8-812a-b13e7608161b.jpg)

![untitled2](https://user-images.githubusercontent.com/12887346/44883089-59fdbc00-ac8c-11e8-8b69-bc93be190cb1.jpg)

![untitled3](https://user-images.githubusercontent.com/12887346/44883096-62ee8d80-ac8c-11e8-9e4b-3e4873cce017.jpg)

```
function [x,w] = lag_rec(n,alpha)
% This code computes the zeros and the weights for Gauss-Laguerre
% quadrature. See Stroud and Secrest (also in NUMERICAL RECIPES p. 146).
for i=1:n
    % Initial approximations
    if i==1
        z = (1+alpha)*(3+.92*alpha)/(1+2.4*n+1.8*alpha); 
    elseif i==2
        z = x(1)+(15+6.25*alpha)/(1+.9*alpha+2.5*n);
    else
        ai = i-2;
        z = x(i-1)+((1+2.55*ai)/(1.9*ai)+1.26*ai*alpha/(1+3.5*ai))*(x(i-1)-x(i-2))/(1+.3*alpha);
    end
    % Newton iterations:
    for k=1:10
        p1 = 1; p2 = 0;
        % recurrence relation:
        for j=0:n-1
            p3 = p2; p2 = p1;
            p1 = ( (-z+alpha+2*j+1)*p2 - (alpha+j)*p3 )/(j+1); 
        end
        pp = (n*p1 - (n+alpha)*p2)/z; % derivative
        z1 = z;
        z = z1 - (p1/pp);
        if abs(z-z1) < 1e-15
            break
        end
    end
    % the zero: 
    x(i) = z;
    
    % once more for derivative:
    p1 = 1; p2 = 0;
    % recurrence relation:
    for j=0:n-1
        p3 = p2; p2 = p1;
        p1 = ( (-z+alpha+2*j+1)*p2 - (alpha+j)*p3 )/(j+1);
    end
    pp = (n*p1 - (n+alpha)*p2)/z; % derivative
    
    % the weight:
    w(i) = exp(gammaln(alpha+n+1)-gammaln(n+1))/(z*pp.^2); 
    %TODO: use the ratio of gamma functions when n>100. 
    
    % breaks the code if the weight is smaller than realmin. Then returns 
    % the zeros and the weights already computed. Without this break, the
    % code can returns NaN in the weights starting from on n=366 because p1
    % becomes NaN.
%     if w(i) == 0
%         break
%     end
end
x=transpose(x);

```
Although the algorithm of the 'REC_{new}' is not vectorised, it is faster than the 'REC'. According to the comparasions, I think that the points and weights are considerable better in 'REC_{new}'. Also, my experiments have shown that this method works normally in whole range `1<=n<=365`. 

I don't have any suggestions about 'REC' code in 'lagpts' because I haven't studied it properly yet so I can't comment in any detail. I couldn't use 'GLR' because I don’t have it.

**Comment by nickhale** [comment]
The commit above implements the following choice of methods:
% Determine default method (heuristic):
n < 300 = rec
n < 1000 = gw
n < 3000 & alpha ~= 0 = gw
n < 3000 & alpha = 0 = glr
n > 3000 = RH

Since the 'exp' method is giving garbage in the largest nodes I have disabled it. Is this a bug?

I've also tidied some of the code (although it is still quite/very messy.)
