### ISSUE TITLE
bug in `chebop/matrix` when domain has internal breakpoints

### ISSUE THREAD

**Issue by trefethen** [chebfun/chebfun#2278]
The chebop `matrix` command allows you to instantiate a spectral discretization of a specified size.  For example,
```
L = chebop(@(u) diff(u,2), [-1 0 1]);
L.lbc = 0; L.rbc = 0;
matrix(L,[10,10]))
```
should produce a 24x24 matrix: 20x24 for the differential operators on the subintervals [-1,0] and [0,1], plus an addditional 4x24 matrix whose rows correspond to the left BC, the right BC, and the coupling conditions of order 0 and 1 at x=0.  The bug, however, is that the coupling conditions are missing, so you get a matrix of order 22x24 instead.

@tobydriscoll suggests (private email communication) that a fix may be to insert the line

```L = deriveContinuity(L);```

after line 40 of `chebop/matrix.m`.  Hopefully one of us can find the time to check this a bit, e.g. on the examples in my _SIAM _Review paper "Block operators and spectral discretizations" coauthored with @jaurentz, and issue a pull request.  Probably very little depends on `matrix`, so it's a low-risk fix.  

I regard this fix as unimportant for Chebfun's functionality but quite important for its educational role, i.e., in teaching Chebyshev spectral methods.

**Comment by nickhale** [comment]
Closed by #2279.
