### ISSUE TITLE
Assigning to entry of chebmatrix wraps value in cell...?

### ISSUE THREAD

**Issue by aaustin141** [chebfun/chebfun#2280]
Say we have a chebmatrix, such as one we get from computing multiple eigenfunctions with `eigs()`:
```
>> L = chebop(-1, 1);  
>> L.op = @(u) diff(u, 2);
>> L.bc = 0;
>> [V, D] = eigs(L, 2);
>> V
V =
   1 x 2 chebmatrix of block types:
    'chebfun'    'chebfun'
>> V{1}
ans =
   chebfun column (1 smooth piece)
       interval       length     endpoint values  
[      -1,       1]       20  -1.1e-15  1.3e-15 
vertical scale = 0.99 
```
So far so good.  But let's say I want to adjust the normalization of one of the eigenfunctions, e.g., for plotting purposes:
```
>> V{1} = -V{1}
V =
   1 x 2 chebmatrix of block types:
    'cell'    'chebfun'
>> V{1}
ans =
  1x1 cell array
    {Infx1 chebfun}
```
For some reason, the chebfun that has been inserted into the first block has been packed in a cell array.  To get to it, I have to do this:
```
>> V{1}{1}
ans =
   chebfun column (1 smooth piece)
       interval       length     endpoint values  
[      -1,       1]       20   1.1e-15 -1.3e-15 
vertical scale = 0.99 
```
Surely this is a bug... or am I misunderstanding something?

**Comment by nickhale** [comment]
As a workaround, `V(1) = -V(1)` appears to work fine.

The offending line seems to be line 17 of `@chebmatrix/subsassign`, but removing the `{}` there breaks other things.

Maybe one solution is to convert `{}` inputs to `subassign` to `()` before they are passed down.
