### ISSUE TITLE
`x = cheb.x` and `x = chebfun(@(x) x)` change Gibbs overshoot!

### ISSUE THREAD

**Issue by bhashemi** [chebfun/chebfun#2300]
In my present Chebfun version, the amount of overshoot related to the Gibbs phenomenon with even degree Chebyshev interpolation _depends_ on how the sign function is constructed! 

```
>> x = cheb.x; % Similar issue if x = chebfun(@(x) x) or x = chebfun('x') is used!
>> f1 = sign(x);
>> f2 = chebfun(@(x) sign(x), 'splitting', 'on');
>> pn1 = chebfun(f1, 101);
>> overshoot1 = max(pn1)
overshoot1 =
    1.2823

>> pn2 = chebfun(f2, 101);
>> overshoot2 = max(pn2)
overshoot2 =
    1.0658
```

`overshoot1` is wrong according to Chapter 9 of ATAP.  I observe that the domain of the two funs of f1 and f2 are not quite the same.

**Comment by nickhale** [comment]
I can't reproduce this:
```
overshoot1 =
   1.065759625135009
overshoot2 =
   1.065759625135009
```

Current Chebfun master branch, MATLAB R2018b, Ubuntu Linux.

**Comment by nakatsukasayuji** [comment]
Same as @nickhale , but I suspect what's happening is the splitting point in f1 on @bhashemi 's machine is slightly off from 0 (say -1e-16), and hence f1(0) is not 0 but 1 (or -1). For example, in the correct f2 if we had the splitting point -1e-16

 f2 = chebfun(@(x) sign(x), 'splitting', 'on'); 
 xx = chebpts(101);
 F = f2(xx); pn2 = chebfun(F);
 overshoot2 = max(pn2)  
 F(51) = 1; % now suppose splitting point was -1e-16
 pn3 = chebfun(F);
 overshoot3 = max(pn3) 

overshoot2 =
    1.0658

overshoot3 =
    1.2823

I personally don't consider this a 'bug', the jump in sign(x) was identified with 1e-16 accuracy so it performed in a "backward stable" way.

**Comment by bhashemi** [comment]
I cannot reproduce the error myself now! I did nothing beyond restarting MATLAB and now `overshoot1` is also correct! I therefore close this issue. 
I believe what happened previously was exactly like what @nakatsukasayuji explains: the splitting points of `f1` were non-zero.
