### ISSUE TITLE
chebfun3t parseInputs fails when dom and 'vectorize' are specified

### ISSUE THREAD

**Issue by APaganini** [chebfun/chebfun#2309]
This code
```
chebfun3t(@(x,y,z) 1, [-2 2 1 2 1 3], 'vectorize')
```
returns
```
Error using chebfun3t/constructor>parseInputs (line 288)
Domain not valid or fully determined.

Error in chebfun3t/constructor (line 14)
[op, dom, pref, vectorize] = parseInputs(op, varargin{:});

Error in chebfun3t (line 61)
            f = constructor(f, varargin{:});
```

The error is in the function `parseInputs` of the chebfun3t constructor.

**Comment by trefethen** [comment]
I think `chebfun3t` works if you omit the `vectorize` flag.  Since such a flag is not advertised as a feature, and indeed the help takes says that users much do vectorization themselves, I will close this issue.
