### ISSUE TITLE
Instability in exponential function

### ISSUE THREAD

**Issue by trinh** [chebfun/chebfun#2312]
Dear Chebfun team, 

I encountered a weird numerical instability in the simple plotting of an oscillating exponential. 

Test code: 
```
F1 = chebfun(@(x) exp(1./x).*cos(1./x), [0.05, 1]);
F2 = chebfun(@(x) exp(1.5./x).*cos(1./x), [0.05, 1]);
F3 = chebfun(@(x) exp(1.8./x).*cos(1./x), [0.05, 1]);
F4 = chebfun(@(x) exp(2./x).*cos(1./x), [0.05, 1]);

plot(F4); hold all
plot(F3); plot(F2); plot(F1); 
ylim([-10, 10])

```
You can see oscillations on the scale of the axis develop when the exponential number goes to about 1.8. It should continue to be relatively smooth and slowly varying around the x = 1 edge. 

![Image here](https://i.imgur.com/RzgE2kw.png)

I suppose this has something to do with the very large numbers near the left boundary, but it was still difficult for me to catch this error, and it is odd for it to appear in a sudden manner. 

Not sure if this is something that requires a fix, but an automated warning might be useful. 

Best,
Phil

**Comment by trefethen** [comment]
Thanks Phil.  I agree the curves are startling.  The explanation is that F4 is 16 orders of magnitude bigger at the left end than at the right end.  Chebfun only gives you accuracy relative to the global size of the function, so at the right end of this interval, it's garbage.  Startling garbage, undeniably!
