### ISSUE TITLE
Clenshaw's algorithm implemented with backslash

### ISSUE THREAD

**Issue by ajt60gaibb** [chebfun/chebfun#2323]
Clenshaw's algorithm is backward substitution on an upper-triangular matrix. This observation allows us to use MATLAB's inbuilt linear system solver to perform Clenshaw's algorithm. The code below is nearly as fast as the highly optimized `chebtech/clenshaw` code. I am sharing if someone wishes to see if a small tweak speeds up `chebtech/clenshaw`: 
```
function y = ClenshawForScalarX(x, c)
% Clenshaw scheme for scalar point evaluation.
    n = size(c, 1);
    Ln = spdiags(ones(n,1)*[1 -2*x 1], 0:2, n, n); 
    Ln(1, 2) = -x; 
    bk = Ln\c;
    y = bk(1, :); 
end
```

**Comment by aaustin141** [comment]
Out of curiosity, have you tried this with using the options input to linsolve() to inform MATLAB of the triangular structure?  This can have a huge impact, at least on larger problems:
```MATLAB
>> n = 1000;
>> Ln = spdiags(ones(n,1)*[1 -2*1 1], 0:2, n, n);
>> tic(); for (i = 1:1:100), x = A\b; end; toc()
Elapsed time is 0.128310 seconds.
>> tic(); for (i = 1:1:100), x = linsolve(A, b, struct('UT', true)); end; toc()
Elapsed time is 0.023787 seconds.
```
Does this make a difference to your comparisons with the current implementation?

**Comment by ajt60gaibb** [comment]
I don't think `linsolve` is supported for sparse matrices. Notice your times are on `A`, not `Ln`.

**Comment by aaustin141** [comment]
You're right---my bad.

**Comment by nickhale** [comment]
In my experiments it's somewhat slower than what we have, although most of the cost is in forming the sparse matrix. 

![image](https://user-images.githubusercontent.com/2035010/60815416-e4aa2400-a197-11e9-8da1-ac4f4190906c.png)

`orig` is the basic implementation, `nh` is my 2014 implementation* of doing two steps at once, `at` is @ajt60gaibb 's suggestion.

* Actually, with the small improvement in #2324.

**Comment by ajt60gaibb** [comment]
Slight speed up. Obviously, closes the gap in timings when 
```
function y = ClenshawForScalarX(x, c)
% Clenshaw scheme for scalar point evaluation.
    n = size(c, 1);
    ii = [1:n 1:n-1 1:n-2];
   jj = [1:n 2:n 3:n];
   s = [ones(1,n) -x -2*x*ones(1,n-2) ones(1,n-2)];
   Ln = sparse(ii, jj, s, n, n, 3*(n-1));
   bk = Ln\c;
    y = bk(1, :); 
end
```

**Comment by nickhale** [comment]
> Slight speed up. Obviously, closes the gap in timings when the chebfun is array-valued.
> 
> ```
> function y = ClenshawForScalarX(x, c)
> % Clenshaw scheme for scalar point evaluation.
>     n = size(c, 1);
>     ii = [1:n 1:n-1 1:n-2];
>    jj = [1:n 2:n 3:n];
>    s = [ones(1,n) -x -2*x*ones(1,n-2) ones(1,n-2)];
>    Ln = sparse(ii, jj, s, n, n, 3*(n-1));
>    bk = Ln\c;
>     y = bk(1, :); 
> end
> ```

This is what I used in my experiment above.

**Comment by jrus** [comment]
If you want to speed up Clenshaw evaluation, running vectorized C code is significantly faster than using Matlab.

https://github.com/alkashani/numcrunch/blob/master/src/clenshaw_vector.c

Back in 2015 I got this running in chebfun on my machine, but nobody seemed too interested.

**Comment by trefethen** [comment]
Hi @jrus! Yes, agreed, but as you know we have a policy of confining Chebfun to core Matlab, without toolboxes and without links to other languages.

**Comment by jrus** [comment]
I did not know that was your policy. I guess that precludes getting you stuck maintaining code in other languages.

Do note that a precompiled matlab library can just be dropped in and works fine, or a source file can be put there and users told to run their local compiler. No other code changes are needed. If both a compiled binary and a matlab source file have the same name, matlab will run the compiled version, so there’s no need to replace anything, the two can sit next to each-other.

Anyhow, if clenshaw evaluation ever turns out to be a bottleneck for anyone (and especially if they are running on Intel hardware from the past few years with very wide SIMD), the code is sitting there for anyone who wants it...
