### ISSUE TITLE
Several warnings when first defining a Chebfun

### ISSUE THREAD

**Issue by oc-rodu** [chebfun/chebfun#2350]
I have the latest version of chebfun (Version 5.7.0 02-Jun-2017) and MATLAB Version: 9.7.0.1296695 (R2019b) Update 4.

I get several warnings when defining a chebfun variable for the first time. 
Thanks.

>> y=chebfun('y',[0 1])
Warning: In the 'chebtech' class, the 'compose' method
has both the Abstract attribute and a function body. 
> In chebfunpref/subsref (line 360)
  In smoothfun.constructor (line 57)
  In onefun.constructor (line 71)
  In bndfun (line 103)
  In classicfun.constructor (line 100)
  In fun.constructor (line 51)
  In chebfun.constructor>getFun (line 276)
  In chebfun.constructor>constructorNoSplit (line 110)
  In chebfun/constructor (line 63)
  In chebfun (line 219) 
y =
   chebfun column (1 smooth piece)
       interval       length     endpoint values  
[       0,       1]        2         0        1 
vertical scale =   1

**Comment by abigopal** [comment]
Hi Rodrigo,

The length refers to the number of Chebyshev coefficients necessary to represent the solution, not the length of the interval. You are constructing a degree 1 polynomial so you need 2 coefficients (one for T_0(x) and one for T_1(x)) e.g. running ``y=chebfun('y^2',[0 1])`` should give you length 3.

I can't reproduce the warnings you're getting. Could you confirm that if you open MATLAB, add chebfun to path, and then run ``y=chebfun('y',[0 1])`` you get warnings?

Best,
Abi

**Comment by oc-rodu** [comment]
Hi Abi, 

Yes I realized what the length means in this case, so I edited my issue. 

I can confirm I get the warnings every time I use chebfun for the first time. Just opened Matlab again, chebfun is added to directory automatically through startup.m, and I get the same warnings as above. This has been happening since I upgraded to some version of Matlab (don't remember which at the time).
Thanks.
