### ISSUE TITLE
Phaseplot color

### ISSUE THREAD

**Issue by NBoulle** [chebfun/chebfun#2376]
I'm wondering if there is an issue with the colorbar scale of phaseplot due to this line: https://github.com/chebfun/chebfun/blob/master/phaseplot.m#L80
Below is the current phaseplot on the function f(z)  = z, indicating that the angle is -pi on the positive real line while it should be 0.
![current_phaseplot](https://user-images.githubusercontent.com/31421323/108983519-dd929b00-7686-11eb-99fe-b379f05c47ae.png)

I found that to match the description (i.e. having the colorbar ranging from [0,2*pi]), one should replace the line by
```
h = surf(real(zz), imag(zz), -ones(size(zz)), phi(angle(-f(zz)))+pi);
caxis([0,2*pi])
```
**Edit:** It might still not be correct, probably the easiest is `mod(phi(angle(f(zz))), 2*pi)`
![match_description_phaseplot](https://user-images.githubusercontent.com/31421323/108983780-1f234600-7687-11eb-8a68-a4830fc9a1e7.png)

However, if we prefer to have the angle ranging from [-pi,pi], then the line should be changed to
`h = surf(real(zz), imag(zz), ones(size(zz)), phi(angle(f(zz))));
`
![angle_normalized_phaseplot](https://user-images.githubusercontent.com/31421323/108983881-3e21d800-7687-11eb-8877-094d575d91f5.png)

A nice feature would be to add an option to choose the angle normalization ([-pi,pi] by default or [0,2*pi] if asked by the user).

**Comment by trefethen** [comment]
@NBoulle, that's interesting.  I've never put a colorbar on a phaseplot, so I hadn't noticed.

Would you be prepared to fix this?  Just now I have a dropbox problem that keeps me from updating Chebfun code until my next visit to the office.

**Comment by NBoulle** [comment]
@trefethen Sure, should I add an option to change the axis from [-pi,pi] to [0,2*pi] ? And if so do you have any name suggestion ?

I think that the default should be plotting from [pi,pi] (the latest picture) so the description will change a bit as well as the color scheme your are used to see (0 will be blue by default instead of red).

**Comment by trefethen** [comment]
Thanks!  I suggest maybe
`phaseplot(..., 'caxis', [theta1, theta2])`
to override the default.

**Comment by jrus** [comment]
Irrespective of normalization for the scale, the colors should not be swapped around based on a parameter like this. If you are going to stick with Wegert's eye-searing color scheme, you should at least stay consistent with his mapping of phase to color.

**Comment by aaustin141** [comment]
Just noticed this issue.

> I think that the default should be plotting from [pi,pi] (the latest picture) so the description will change a bit as well as the color scheme your are used to see (0 will be blue by default instead of red).

I agree with @jrus that making zero-phase blue rather than red is a bad idea.  Associating red with zero phase is standard on these plots, even predating Wegert.

Why not just shift the color map instead?

```matlab
map = colormap('hsv');      % 256 entries by default.
map = circshift(map, 128);
colormap(map);

x = linspace(-1, 1, 512).';
y = linspace(-1, 1, 512).';
[xx, yy] = meshgrid(x, y);
zz = xx + 1i*yy;

surf(xx, yy, angle(zz), 'EdgeColor', 'None');
colorbar();
view(0, 90);
```
![phaseplot2](https://user-images.githubusercontent.com/3380006/109238592-a86e7180-7788-11eb-8c35-6a29f7bc563f.png)

**Comment by NBoulle** [comment]
I agree: it's better to have a consistent color scheme. In https://github.com/chebfun/chebfun/pull/2377 I shifted the colormap so that 0 mod [2*pi] is always red.
