### ISSUE TITLE
Removing 'Type <space> when ready' prompt

### ISSUE THREAD

**Issue by rafsanabir** [chebfun/chebfun#2378]
Hi, I want to use the Spin class to differentiate the viscous Burgers equation inside a loop. But every time it starts a new instance of solving the PDE inside the loop, it requires a user input (pressing any key/space/enter works). I want to run the loop a few thousand times, is there any way to get around that user input prompt every time, and execute the loop without any intervention from my part? Thanks!

**Comment by danfortunato** [comment]
Try the option `spin(..., 'plot', 'off')`, e.g.
```
>> u = spin('Burg', 'plot', 'off');
```

**Comment by rafsanabir** [comment]
Thanks! That worked a treat!
