### ISSUE TITLE
Minor typo in chebop documentation

### ISSUE THREAD

**Issue by bhashemi** [chebfun/chebfun#2390]
There is a typo in line 181 of the `chebop` documentation where the following example is explained:

``% Example (unknown parameter in differential equation):``
``%``
``%   % y'' + x.*y + p = 0, y(-1) = 1, y'(-1) = 1, y(1) = 1 can be solved via``
``%   N = chebop(@(x, y, p) diff(y,2) + x.*y + p);``
``%   N.lbc = @(y, p) [y - 1 ; diff(y)];``

In the third line above, `y'(-1) = 1` should be replaced with `y'(-1) = 0`.

**Comment by trefethen** [comment]
Fixed.  Thanks @bhashemi.
