### ISSUE TITLE
trigcoeffs does not respect domain

### ISSUE THREAD

**Issue by jeanluct** [chebfun/chebfun#2401]
Hi,

I think this is a small bug, or at least unexpected behavior?  If one extracts the Fourier coefficients of a chebfun, and then uses them to create a new chebfun, the new chebfun is different if the domain is not centered on zero,:

```
L = 1;
f = @(x) exp(sin(pi*x/L));

for i = 1:2
  dom = [-L L] + (i-1)*L  % domain [-L,L] then [0,2*L]
  F = chebfun(f,dom,'trig');
  c = trigcoeffs(F,10);

  F2 = chebfun(c,dom,'trig','coeffs');

  subplot(2,1,i)
  plot(F,'-',F2,'r-')
end
```
![chebfun_bug](https://user-images.githubusercontent.com/3310622/152146112-c343cc25-4584-4f12-bbb2-d9ec9bec4113.png)

This is pretty trivial and I could probably attempt a fix, but wanted to check first.

**Comment by trefethen** [comment]
Hello @jeanluct!  If I am understanding you, I think this is a feature not a bug, which we discuss in a footnote in the paper "Extension of Chebfun to periodic functions" by me together with @gradywright, @mhsnjvd, and @Hadrien-Montanelli. 

![image](https://user-images.githubusercontent.com/3601488/152147745-f76b80ad-699d-4060-b465-8f91aaf4e31c.png)

Does this make sense?  Or am I missing something?

In general, we prefer questions like this at the Chebfun user's group than here at the GitHub site.

**Comment by jeanluct** [comment]
Hi Nick,

Ah, ok.  I suspected that perhaps I was not appreciating the reasoning.  What you say sounds sensible.  The behavior can be a bit surprising when trying to use `trigcoeffs` and `chebfun` as inverses of each other, but I can see your point.

I'm in Cambridge at the Newton for several months.  Good to hear from you.

Best,

Jean-Luc
