### ISSUE TITLE
More efficient representation of trigonometric series possible?

### ISSUE THREAD

**Issue by andreasvarga** [chebfun/chebfun#2410]
I am a newcomer to `chebfun` and very impressed of its capabilities. Since I am working on implementing computational techniques for linear periodic systems, I am interested in the features provided in `chebfun` for handling periodic functions. I have a very basic question regarding the efficiency of the implementation of periodic functions, which concerns the number of coefficients used for approximation/representation.  Just a very simple example to illustrate what I mean.

Consider the periodic functions `pf1` of period `2*pi` and `pf2` of period `200*pi `below:
```
>> pf1 = chebfun(@(t) sin(t)+cos(t),[0,2*pi],'trig')

pf1 =

   chebfun column (1 smooth piece)
       interval       length     endpoint values trig
[       0,     6.3]        3         1        1 
vertical scale = 1.4 

>> pf2 = chebfun(@(t) sin(t)+cos(t),[0,200*pi],'trig')

pf2 =

   chebfun column (1 smooth piece)
       interval       length     endpoint values trig
[       0, 6.3e+02]      201         1        1 
vertical scale = 1.4 

```
The two functions are essentially the same, only the periods differ by an integer factor `k = 100`, but the numbers of stored coefficients differ significantly. However, from the zero/nonzero structure of the coefficients of `pf2` it is relatively straightforward to figure out that the basic period of `pf2` is `2*pi` and therefore, it is only necessary to store the same coefficients as for `pf1` and, of course, an additional information on, say, the number of subperiods which, in this case, is `k =100`. The nonzero coefficients for both `pf1` and `pf2` are the same (within a tolerance): 
```
>> c1=trigcoeffs(pf1); c1(abs(c1) > 1.e-13)

ans =

   5.0000e-01 + 5.0000e-01i
   5.0000e-01 - 5.0000e-01i

>> c2=trigcoeffs(pf2); c2(abs(c2) > 1.e-13)

ans =

   5.0000e-01 + 5.0000e-01i
   5.0000e-01 - 5.0000e-01i

```
I faced this issue when storing periodic matrices in a similar harmonic representation, where the storage issue is additionally worsened by the size of these matrices.

**Comment by trefethen** [comment]
Well you are certainly correct that Chebfun does not detect or take advantage of sparsity of coefficient vectors.  And of course there will be some applications where this is unfortunate.  Another example -- only a factor of 2, but very commonly arising -- is that we do not keep track of whether a function is even or odd, which would enable us to store only half as many coefficients.

**Comment by andreasvarga** [comment]
Thanks. In my applications it happens that a common commensurate period is necessary for several periodic matrices. In this case, it is sometimes easy to just adjust (usually increase) the period and adjust accordingly the number of subperiods. This does not involves any changes in the basic data of the representation.
