### ISSUE TITLE
AAA may return incorrect final error

### ISSUE THREAD

**Issue by WilliamRJohns** [chebfun/chebfun#2423]
For example if there are 2 support points and one is removed for having zero weight, interpolation is broken and the final error returned may be incorrect. In the following example the final l_inf error should be 1 but is returned as 0.
x=[1:1:5];
Fx=[ones(1,4) 2]
[aaa_aprox,~,~,~,zj,fj,wj,errvec,~]=aaa(Fx,x);
approx=aaa_aprox(x)
%Final error 0 returned but error is 1
errvec
%%

Fx =

     1     1     1     1     2

approx =

     1     1     1     1     1

errvec =

     1
     0

**Comment by trefethen** [comment]
[aaa03_supportpts.pdf](https://github.com/chebfun/chebfun/files/10981999/aaa03_supportpts.pdf)

William, I'd be pleased to be in touch directly about this if you're interested.  If so, would you send me an email at trefethen@maths.ox.ac.uk ?  Thanks.
