### ISSUE TITLE
how to fix the offset term in Vandermonde+Arnoldi polyfit ?

### ISSUE THREAD

**Issue by ZiadHatab** [chebfun/chebfun#2447]
Hi!

First of all, thanks for all the great work you guys are doing with Chebfun. I really like it, even though I program most of the time in Python. I still like to read your code and papers and program solutions in Python.

Today I came across a problem I have with Vandermonde+Arnoldi polyfit. I want to fix the constant term. In normal polyfit, I just subtract that term from the measurement vector, estimate the rest of the terms, and put that coefficient back. With the Arnoldi, the step of putting back the fixed constant in the polyval function is not clear to me because of the orthogonalization procedure.

For example, suppose I have data, y1,y2,....yn, and I decided to model it with this polynomial p(x) = a0 + a1x + a2x^2. I want to fix a0 to a constant and let the polyfit estimate the other coefficients. Can you guide me on how to define this in the polyval function with Arnoldi?

Thanks a lot!
Ziad

**Comment by trefethen** [comment]
Dear Ziad - Vandermonde with Arnoldi isn't part of Chebfun; it's part of my research (with @nakatsukasayuji  and others).  If you'd like to send a message to me at trefethen@maths.ox.ac.uk, that would be fine; I suggest a copy to nakasukasa@maths.ox.ac.uk.  Meanwhile I will close this issue.   - Nick Trefethen
