### ISSUE TITLE
chebfun.mat2cell() and chebfun.num2cell() do not conform to their built-in counterparts.

### ISSUE THREAD

**Issue by aaustin141** [chebfun/chebfun#30]
The syntax for `chebfun.mat2cell()` offers a shortcut `mat2cell(f)` which splits each fun of `f` into a cell in a cell array.  If `A` is a matrix, MATLAB `mat2cell(A)` puts the entire matrix `A` into a single cell, and a warning is issued indicating that single-argument calls to `mat2cell()` are deprecated.  If you want each element of A to be put into a cell of its own you must either pass the appropriate other arguments to `mat2cell()` or call `num2cell(A)` as a shortcut.

There is thus a discrepancy between `chebfun.mat2cell()` and the built-in `mat2cell()`.  Moreover, the existence of the shortcut syntax for `chebfun.mat2cell()` makes `chebfun.num2cell()` completely redundant.  We should either (A) decide that we don't want to worry about conforming to MATLAB on this and remove `chebfun.num2cell()` or (B) fix the syntax of these functions to be the same as their built-in counterparts.

This is not terribly important, and it can be fixed whenever someone has some spare time.

**Comment by nickhale** [comment]
I'm in favour of (A), and therefore closing this issue. 

Although these are `chebfun` methods, we don't really expect casual users to be making use of them and the expected behaviour is documented.

**Comment by aaustin141** [comment]
Agreed.  This most likely isn't worth worrying about.
