### ISSUE TITLE
pde15s taking an incredibly long time for Maxwell example

### ISSUE THREAD

**Issue by gradywright** [chebfun/chebfun#405]
The following code is used in the first part of the Maxwell's equation example (note it has been modified to use v5 syntax):

```
pdefun = @(t,x,E,B) [ diff(B), diff(E) ];
bc.left = @(t,x,E,B) E;
bc.right = bc.left;
d = [-2,2];
x = chebfun('x',d);
E0 = exp(-16*x.^2);
t = 0:0.05:5;
soln = pde15s(pdefun,t,[E0,-E0],bc,pdeset('plot','on'));
```
This code runs really fast in v4, but runs incredibly slow in v5.  In v5 on my machine, the solution is computed up to about t=0.5 in a reasonable amount of time, but then the code slows down considerably and appears to get stuck without advancing any further.  Eventually I had to kill the process.

**Comment by asgeirbirkis** [comment]
With the introduction of `pde23t`, are we happy to close this issue?

**Comment by nickhale** [comment]
:+1:

**Comment by asgeirbirkis** [comment]
The introduction of `pde23t` in #1481 now means that we can happily solve the problem above.
