### ISSUE TITLE
Implement FOURTECH/ROOTS with analogue of Colleague Matrix.

### ISSUE THREAD

**Issue by Hadrien-Montanelli** [chebfun/chebfun#875]
`FOURTECH/ROOTS` uses `CHEBTECH/ROOTS`: the `FOURTECH` is converted to a `CHEBTECH1`.

Ideally, we should implement the analogue of the Colleague Matrix in the Fourier basis.

**Comment by trefethen** [comment]
This might indeed be interesting from a research point of view but I don't think we need it as an unresolved issue on the tracker, so I am closing it.
