### ISSUE TITLE
The vscale of a chebfun in chebtech1 mode

### ISSUE THREAD

**Issue by ajt60gaibb** [chebfun/chebfun#904]
The following estimate of `vscale` is causing me some issues in Chebfun2: 

```
pref = chebfunpref();
pref.tech = @chebtech1;  
f = chebfun(@(x) 1e100*x, pref); 
vscale(f)
ans =
   7.0711e+99
```

In contrast since 2nd kind grids include the endpoints we have: 

```
pref = chebfunpref();
pref.tech = @chebtech2;  
f = chebfun(@(x) 1e100*x, pref); 
vscale(f)
ans =
  1.0000e+100
```

Could/should we always be evaluating a chebtech on 2nd kind grids when estimating `vscale`?

**Comment by nickhale** [comment]
Can this issue be closed?
