### ISSUE TITLE
`abs(x).^1.5` now resolved at 12 digits with 40895 points

### ISSUE THREAD

**Issue by trefethen** [chebfun/chebfun#941]
For years section 8.5 of the Guide has given `abs(x).^1.5` an an example of a function that could not be resolved with 65537 points, but could be resolved if you increased `maxdegree` (which has now become `maxLength`) to allow a larger number:

```
f = chebfun('abs(x).^1.5','maxdegree',1e6);
length(f)
ans = 127163
```

Now, however, this function is resolved with a chebfun one-third as long, and
the accuracy is only around 12 digits (see plot below)

```
f = chebfun('abs(x).^1.5','maxdegree',1e6);
length(f)
ans = 40895
f(.5) - .5^1.5
ans =   5.786815471253703e-12
```

My guess is that this is a consequence of our having changed "2/3" to "1" in the constructor.  If anyone has a different view and conceivably a fix, please let me know.  Assuming the 2/3 vs. 1 theory is correct, presumably there's no action we will take in a hurry, but this is grist for our mill in future discussions, and I will use a different example in the guide.  
![foo](https://cloud.githubusercontent.com/assets/3601488/3326184/cf03ceec-f799-11e3-8d1a-7a7ce74caf2d.jpg)

**Comment by aaustin141** [comment]
As a point of reference, now that #1562 has been merged, we now get that this function is resolved at about 10 digits with 13,319 points:
```
>> f = chebfun(@(x) abs(x).^1.5)
f =
   chebfun column (1 smooth piece)
       interval       length     endpoint values  
[      -1,       1]    13319         1        1 
vscale = 1.
>> f(0.5) - 0.5^1.5             
ans =
     9.520922938932586e-11
```
I don't really know what, if anything, to make of this.
