### ISSUE TITLE
Should we call simplify() at the end of chebtech/plus() and fourtech/plus()

### ISSUE THREAD

**Issue by gradywright** [chebfun/chebfun#962]
We call simplify at the end of `chebtech/times()` and `fourtech/times()`.  Should we also do this at the end of `plus()`?  This would fix the following:

```
>> f = chebfun(@(x) cos(pi*x));
>> g = chebfun(@(x) sin(pi*x));
>> h = f.^2 + g.^2

h =

   chebfun column (1 smooth piece)
       interval       length   endpoint values  
[      -1,       1]       27         1        1 
Epslevel = 1.110223e-15.  Vscale = 1.000000e+00.
```

Calling simplify() at the end of chebtech/plus() gives the desired result:

```
>> f = chebfun(@(x) cos(pi*x));
>> g = chebfun(@(x) sin(pi*x));
>> h = f.^2 + g.^2

h =

   chebfun column (1 smooth piece)
       interval       length   endpoint values  
[      -1,       1]        1         1        1 
Epslevel = 1.110223e-15.  Vscale = 1.
```

Note that a similar result holds for `fourtech` when using `simplify()` at the end of `plus()`

**Comment by aaustin141** [comment]
Now that #1562 has been merged, perhaps we should revisit this issue?  See also the more recent issue #1351.
